### ISSUE TITLE
FR: nixpkgs.flake.{source,setNixPath,setFlakeRegistry} settings

### ISSUE THREAD

**Issue by n8henrie** [LnL7/nix-darwin#1015]
These three settings seem like handy newish additions (24.05) for which it might make sense to have nix-darwin equivalents

- [nixpkgs.flake.source](https://search.nixos.org/options?channel=unstable&show=nixpkgs.flake.source&from=0&size=50&sort=relevance&type=packages&query=nixpkgs)
- [nixpkgs.flake.setNixPath](https://search.nixos.org/options?channel=unstable&show=nixpkgs.flake.setNixPath&from=0&size=50&sort=relevance&type=packages&query=nixpkgs)
- [nixpkgs.flake.setFlakeRegistry](https://search.nixos.org/options?channel=unstable&show=nixpkgs.flake.setFlakeRegistry&from=0&size=50&sort=relevance&type=packages&query=nixpkgs)

With a flake-based NixOS system, these are all set by default and result in registry settings in `/etc/nix/registry.json`; in contrast mine is empty by default on nix-darwin.

The implementation looks fairly trivial: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/misc/nixpkgs-flake.nix, I think a workaround is as simple as:

```nix
nix = lib.optionalAttrs pkgs.stdenv.isDarwin {
    nixPath = [ "nixpkgs=flake:nixpkgs" ];
    registry.nixpkgs.to = {
      type = "path";
      path = config.nixpkgs.source;
    } // {
# remainder of platform-independent nix config
}
```

**Comment by DaGenix** [comment]
@n8henrie - I think this was maybe done in https://github.com/LnL7/nix-darwin/commit/8714f9e28529183d65d9f42ac92cdc5d70dbb6f7 ?

**Comment by n8henrie** [comment]
Indeed! Thanks for the heads up!

```
$ nix eval .#darwinConfigurations.mymachine.config.nixpkgs.flake.source
"/nix/store/kjny8s47s35v10a4rcdyrir2dklbj0v9-source"
$ nix eval .#darwinConfigurations.mymachine.config.nixpkgs.flake.setFlakeRegistry
true
$ nix eval .#darwinConfigurations.mymachine.config.nixpkgs.flake.setNixPath
true
```
