### ISSUE TITLE
Is it possible to use sketchybar lua?

### ISSUE THREAD

**Issue by Demianeen** [LnL7/nix-darwin#1021]
I recently started to use nix and already moved all my configuration to it except sketchybar on lua. Is there some way to setup sketchybar with SbarLua with nix?

**Comment by khaneliman** [comment]
I'm using sketchybar with lua in my config, currently. I haven't upstreamed anything to make it easier from a home-manager module or anything, yet. But, you can take a look https://github.com/khaneliman/khanelinix/blob/60bc9ff5b65ca7e107de3b288e16998fd2b01c88/modules/home/programs/graphical/bars/sketchybar/default.nix

**Comment by Demianeen** [comment]
Thanks, @khaneliman! I do see a lot of useful stuff, I will try it in the next couple of weeks
