### ISSUE TITLE
How to disable Nix channels?

### ISSUE THREAD

**Issue by thecaralice** [LnL7/nix-darwin#1024]
I manage my system with flakes, so channels sometimes lead to surprising results.
I tried settings `nix.channel.enable = false` as it is on NixOS but found out that this is not an option.

**Comment by Enzime** [comment]
We don’t have an equivalent option, any PRs to add logic mirroring that from NixOS would be appreciated

The module can be found here: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/config/nix-channel.nix

**Comment by thecaralice** [comment]
Yeah, I'm already working on it!

**Comment by thecaralice** [comment]
@Enzime I stumbled upon https://github.com/LnL7/nix-darwin/blob/f7142b8024d6b70c66fd646e1d099d3aa5bfec49/modules/nix/default.nix#L753-L756 which is in contrary with what NixOS does. Is it really needed? I'm in favor of mirroring NixOS behavior here, i.e. demote it to `mkDefault` priority and move this default to the option declaration.
