### ISSUE TITLE
finder option to enable search in only in current folder

### ISSUE THREAD

**Issue by cschar** [LnL7/nix-darwin#1036]
<img width="639" alt="Screenshot 2024-08-16 at 10 08 03 PM" src="https://github.com/user-attachments/assets/b42ee278-1be8-45aa-859e-c702101224cc">

Basically this article
https://eshop.macsales.com/blog/86405-how-to-make-finder-search-only-the-current-folder-by-default-in-macos-sonoma-and-ventura/#:~:text=Navigate%20to%20the%20bottom%20of,Use%20the%20Previous%20Search%20Scope.

I want to use nix-darwin to configure be able to only search in the folder I am in

**Comment by Samasaur1** [comment]
To do this, you'll need to find how macOS stores this selection internally. I suspect it is stored in UserDefaults, probably under the `com.apple.Finder` domain.

Here's what I'd do:
1. Run `defaults read com.apple.Finder` and save the output
2. Change this setting
3. Run `defaults read com.apple.Finder` and save the output
4. Compare the two outputs you saved and see if you can identify the key that stores this preference

**Comment by cschar** [comment]
<img width="455" alt="Screenshot 2024-08-17 at 4 20 04 PM" src="https://github.com/user-attachments/assets/1fc98659-9527-4699-a16a-ced13ac11ddd">
 Awesome! this seems to be the line that was generated
 
 
 and this setting already exists in this repo... whoops. Thank you for pointing me to the defaults tool.

 https://github.com/LnL7/nix-darwin/blob/076b9a905af8a52b866c8db068d6da475839d97b/modules/system/defaults/finder.nix#L32

 I have added a little note in my config !
 
<img width="699" alt="Screenshot 2024-08-17 at 4 27 15 PM" src="https://github.com/user-attachments/assets/4609dc29-6ac9-4eb6-9dba-b7eac61694ab">
