### ISSUE TITLE
Nixpkgs config (e.g. allowUnfree) not being picked up properly?

### ISSUE THREAD

**Issue by tsteckenborn** [LnL7/nix-darwin#1045]
Hey there,

Currently in the process of setting up nix-darwin for the first time.

I specified
```
          nixpkgs.config = {
            allowUnfree = true;
            allowBroken = false;
            allowUnsupportedSystem = false;
          };
```

yet when reaching a packages such as Raycast I receive an error w.r.t. `allowUnfree`:
```
error: Package ‘raycast-1.81.2’ in /nix/store/p9sy5nf9jdwj69gmr3c3n03npzr5kkqi-source/pkgs/os-specific/darwin/raycast/default.nix:55 has an unfree license (‘unfree’), refusing to evaluate.
```

Exporting `export NIXPKGS_ALLOW_UNFREE=1` with `--impure` seems to work, but I'd have expected that I don't need that given the config above. Can someone shed some light on how this should behave?

Edit: Seems like atleast one other person has a similar issue in _Originally posted by @bglgwyng in https://github.com/LnL7/nix-darwin/issues/89#issuecomment-2122218235_

**Comment by Enzime** [comment]
What does your `nix-darwin.lib.darwinSystem` call look like?

**Comment by tsteckenborn** [comment]
```
    darwinConfigurations."HostName" = darwin.lib.darwinSystem {
      system = "aarch64-darwin";
      pkgs = import nixpkgs {system = "aarch64-darwin";};

      modules = [
  ```

**Comment by Enzime** [comment]
If you pass in `pkgs`, then it won't be constructed by nix-darwin and the `nixpkgs.*` options won't work. You can just remove the `pkgs = ...` line

**Comment by tsteckenborn** [comment]
Could you help me understand the use of the respective line? I'm asking as I've seen that in a lot of (older) guides and partially in other configurations I could find on GitHub (with partial inclusion of such nixpkgs config as well, which if the usage hasn't changed might indicate that a few people might run into this issue)

**Comment by Enzime** [comment]
If you're using that exact line, then there's no value in defining it that way because it won't allow you to use the `nixpkgs.*` options to configure Nixpkgs and you're not giving it any special options, so you might as well let nix-darwin instantiate Nixpkgs. The main use case would be if you're already instantiating Nixpkgs elsewhere in your `flake.nix` and want to share the same instance.

**Comment by valentinegb** [comment]
I seem to be having a similar problem, except `NIXPKGS_ALLOW_UNFREE=1` and `--impure` doesn't work as a workaround.

```
error: Package ‘roblox-studio-0.681.0.6810806’ in /nix/store/r6zhki1pczbvyj37868agb3hv4xk1n8d-source/pkgs/by-name/ro/roblox-studio/package.nix:26 has an unfree license (‘unfreeRedistributable’), refusing to evaluate.
```

That package is available through an overlay:

```nix
# flake.nix
overlays.default =
  final: prev:
  self.packages.aarch64-darwin
  // {
    # TODO: remove ↓ when NixOS/nixpkgs#421083 is merged
    apple-music-discord-rpc =
      nixpkgs-apple-music-discord-rpc-fork.legacyPackages.aarch64-darwin.apple-music-discord-rpc;
    # TODO: remove ↓ when NixOS/nixpkgs#424118 is merged
    roblox-studio = nixpkgs-roblox-studio-fork.legacyPackages.aarch64-darwin.roblox-studio;
  };
```

```nix
# configuration.nix
nixpkgs = {
  config.allowUnfree = true;
  overlays = [ inputs.self.overlays.default ];
};
```

Here's my attribute in `darwinConfigurations`:

```nix
# flake.nix
darwinConfigurations.Valentines-MacBook-Air = nix-darwin.lib.darwinSystem {
  modules = [
    ./configuration.nix
  ];
  specialArgs = { inherit inputs; };
};
```

Any advice? ^^'

**Comment by Alt-iOS** [comment]
Did you manage to solve it? Having a similar issue as well

**Comment by valentinegb** [comment]
@Alt-iOS I did actually! Here's what I have now that works, compared to the code I showed before:

```nix
overlays.default =
  final: prev:
  self.packages.aarch64-darwin
  // {
    modrinth-app =
      (import nixpkgs-modrinth-app-fork {
        config.allowUnfree = true;
        system = "aarch64-darwin";
      }).modrinth-app;
  };
```
