### ISSUE TITLE
darwin-rebuild edit causes error on Mojave

### ISSUE THREAD

**Issue by ktf** [LnL7/nix-darwin#107]
Doing:

```bash
> $(nix-build '<darwin>' -A system --no-out-link)/sw/bin/darwin-rebuild edit
```

results in:

```bash
dyld: Library not loaded: /usr/lib/system/libsystem_network.dylib
  Referenced from: /nix/store/yvkvyvc36l2dmwl22vajc8bdg7fv3p6b-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
```

Notice `rebuild` and `switch` actually work fine. Same issue also with a direct invocation of `darwin-rebuild`. Any idea of what I might be doing wrong?

**Comment by LnL7** [comment]
This is https://github.com/NixOS/nixpkgs/issues/42719, make sure you're using a recent enough version nixpkgs if you upgraded to 10.14.

**Comment by ktf** [comment]
I am using 18.09, is that the problem?

--
Ciao,
Giulio

**Comment by LnL7** [comment]
No, I backported the fixes so that should be fine as long as you updated it to a recent enough version.
