### ISSUE TITLE
Add Applications to Launchpad

### ISSUE THREAD

**Issue by sellout** [LnL7/nix-darwin#11]
The command mentioned on https://nixos.org/wiki/Nix_on_OS_X#Configuration isn’t quite right, but something similar to it would be useful to add applications from `/run/current-system/sw/Applications` to `/Applications` (and similar for `~/Applications` from user profiles).

Maybe behind a configuration option like `system.launchpad.enable = true;`

**Comment by LnL7** [comment]
The main thing that's a bit tricky for this is cleanup. OS X doesn't like `.app` bundles to be  symlinks IIRC, making it a bit more difficult to detect what applications are managed by nix-darwin.

**Comment by derimagia** [comment]
@LnL7 yep, see https://github.com/caskroom/homebrew-cask/issues/13201 which has been dealing with this for quite a while.

**Comment by matthewbauer** [comment]
I use symlinks in ~/Applications and haven't had a problem. They appear in launchpad and everything (although Launchpad shows their absolute path, not the symlinked one).

**Comment by LnL7** [comment]
I added some basic functionality in https://github.com/LnL7/nix-darwin/commit/290b1d8aad2c7e28a7fe51e1d7bbf145445da851, it doesn't show up in launchpad for me but that might be because my /nix/store is on a separate volume.

**Comment by LnL7** [comment]
n/m it showed up.
