### ISSUE TITLE
bash configuration conflicts with `nix run`

### ISSUE THREAD

**Issue by thefloweringash** [LnL7/nix-darwin#110]
My generated bashrc includes the line

```
export PATH=$HOME/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
```

Which overwrites the path specified by `nix run`. The result is that attempting to enter a shell with `nix run joe`, does not contain the path to `joe`.

**Comment by LnL7** [comment]
Hmm strange, nixos does something similar to break out of that case. https://github.com/NixOS/nixpkgs/blob/c941577dcb68ad413853ae744a458555b3209c21/nixos/modules/programs/bash/bash.nix#L186-L188

**Comment by thefloweringash** [comment]
It might be significant that I'm using zsh, so my environment contains:
```
__ETC_ZSHENV_SOURCED=1
```
but doesn't mention bash at all.

**Comment by thefloweringash** [comment]
NixOS has a common environment initialiser, which [sets `__NIXOS_SET_ENVIRONMENT_DONE`], and then the [bash setup] and [zsh setup] check this variable.

[sets `__NIXOS_SET_ENVIRONMENT_DONE`]: https://github.com/NixOS/nixpkgs/blob/c941577dcb68ad413853ae744a458555b3209c21/nixos/modules/config/shells-environment.nix#L181
[bash setup]: https://github.com/NixOS/nixpkgs/blob/c941577dcb68ad413853ae744a458555b3209c21/nixos/modules/programs/bash/bash.nix#L132
[zsh setup]: https://github.com/NixOS/nixpkgs/blob/c941577dcb68ad413853ae744a458555b3209c21/nixos/modules/programs/zsh/zsh.nix#L121

**Comment by thefloweringash** [comment]
So this needs a slightly deeper look into the shell initialization process and variables.

In my zsh process I have
- `__ETC_BASHRC_SOURCED`
- `__ETC_ZPROFILE_SOURCED`
- `__ETC_ZSHENV_SOURCED`
- `__ETC_ZSHRC_SOURCED`

The __exported__ set of variables is
- `__ETC_ZSHENV_SOURCED`

Each shell file has an internal variable to stop files running more than once. I don't yet know why this is necessary, but it's consistent between nixos and nix-darwin. Additionally, some of these variables are exported, which prevents them running more than once per shell _tree_. NixOS defines an additional file in `/etc/set-environment` that runs once per shell tree, but is checked in every shell. I don't yet have a good explanation for why in nixos `zshenv` is once per tree, but `zprofile` is once per shell.

Simply changing the `__ETC_BASHRC_SOURCED` variable to be `export`-ed will break things, since the kind of things that go into `/etc/bashrc`, like aliases and functions, cannot be inherited must be run on every shell.

Would you accept a PR porting the NixOS `/etc/set-environment` pattern to nix-darwin?

**Comment by peel** [comment]
Mind, that both nixos and nix-darwin do support fish, which is not a POSIX shell. I remember hitting the issue there as well. Might be a good idea to verify behaviour there as well.

**Comment by thefloweringash** [comment]
On NixOS, fish uses the same [setup check][], and if the setup hasn't been run, it handles it through a "foreign env" package. It looks like it requires a support hook from the package side too.

On nix-darwin, it always [clobbers the values], so I expect `nix run` to also not work.

[setup check]: https://github.com/NixOS/nixpkgs/blob/7d96d1502015877d12a816658f0bf3bfc7540129/nixos/modules/programs/fish.nix#L115-L117
[clobbers the values]: https://github.com/LnL7/nix-darwin/blob/e6a698a7011487f16dd061d65e36ec330465ed16/modules/programs/fish.nix#L112
