### ISSUE TITLE
[help] Start packages on login

### ISSUE THREAD

**Issue by realhackcraft** [LnL7/nix-darwin#1102]
I would like to start a package (sketchybar) on login. How can I achieve this using nix?

**Comment by Enzime** [comment]
https://daiderd.com/nix-darwin/manual/index.html#opt-services.sketchybar.enable

As there's already a service for sketchybar in nix-darwin, you just need to add:

```
services.sketchybar.enable = true;
```

**Comment by realhackcraft** [comment]
Do I have to add sketchybar to my env packages for this to work?

**Comment by Enzime** [comment]
No, it'll use the default `services.sketchybar.package`, which should be fine:

https://daiderd.com/nix-darwin/manual/index.html#opt-services.sketchybar.package

**Comment by vtu-dog** [comment]
I'll latch onto the question, maybe it will help somebody in the future if some app is not supported out-of-the-box.

First, an answer. I have the following snippet for Raycast, lifted from [this issue](https://github.com/LnL7/nix-darwin/issues/902) (oh hi Enzime):
```nix
launchd.user.agents = {
  raycast = {
    serviceConfig.ProgramArguments =
      [ "/Applications/Raycast.app/Contents/MacOS/Raycast" ];
    serviceConfig.RunAtLoad = true;
  };
};
```
Second, a question of my own. It works, but there's a 50-50 chance that _another_ instance of Raycast will be launched a few minutes after reboot. I don't even know where to start debugging this issue. Am I the only one? Any ideas?

**Comment by Enzime** [comment]
Have you disabled the `Launch Raycast at login` option in the Raycast settings?

**Comment by vtu-dog** [comment]
Yup, forgot to mention that. No entries in system settings' login items either.

**Comment by Enzime** [comment]
I would try ticking it and unticking it, as macOS has some hidden startup items that don’t show up in the settings
