### ISSUE TITLE
yabai update

### ISSUE THREAD

**Issue by aspauldingcode** [LnL7/nix-darwin#1127]
Hi,

Please update yabai window manager from v7.1.1 to v7.1.4 (latest).
Thanks!

**Comment by orzklv** [comment]
@aspauldingcode you should submit update request PRs at [nixpkgs](https://github.com/NixOS/nixpkgs/issues)

Unstable channel seems to have 7.1.3 version, you may consider adding unstable channel and use yabai from it.

**Comment by aspauldingcode** [comment]
Oh! 
That’s right. Thank you, I will do that.
