### ISSUE TITLE
LinuxKit integration

### ISSUE THREAD

**Issue by zimbatm** [LnL7/nix-darwin#113]
It would be sweet if nix-darwin was able to install the LinuxKit Nix remote builder from https://github.com/nix-community/linuxkit-nix

**Comment by yurrriq** [comment]
Maybe related: https://github.com/nix-community/linuxkit-nix/issues/7

**Comment by zupo** [comment]
linuxkit seems deprecated, @zimbatm should we close this issue?

**Comment by zimbatm** [comment]
good point
