### ISSUE TITLE
typo '&amp;&amp;' in module for karabiner-elements ?

### ISSUE THREAD

**Issue by bls-ibf** [LnL7/nix-darwin#1131]
here:
https://github.com/LnL7/nix-darwin/blob/b379bd4d872d159e5189053ce9a4adf86d56db4b/modules/services/karabiner-elements/default.nix#L103

This should be `&&` instead right?

(oops, should have used my personal account @bew)

**Comment by Enzime** [comment]
As it's inside an XML file and the string isn't inside a `<![CDATA[` section, the ampersands need to be escaped

**Comment by Enzime** [comment]
As we use `generators.toPlist` from Nixpkgs, I think this is an upstream issue and strings should probably be escaped here:

https://github.com/NixOS/nixpkgs/blob/9e88ad806a9333111d508a96287079f0ab349492/lib/generators.nix#L573

**Comment by bew** [comment]
Oh I see, I missed the part where it's an xml file in the end.

Since I have you here @Enzime, I opened a separate issue because the service (and package) is broken: #1132
