### ISSUE TITLE
pam_reattach support

### ISSUE THREAD

**Issue by alkimake** [LnL7/nix-darwin#1137]
It would be nice to have [pam_reattach](https://github.com/fabianishere/pam_reattach) support for Tmux users that wants to enable sudo with touch id

Config can be; `security.pam.enablePAMReattach`

There are 2 things needs to be added;

- installs the `pam_reattach` from nix packages with env packages;
```nix
  environment.systemPackages = [
    pkgs.pam-reattach
  ];
```
- adds itself into `/etc/pam.d/sudo`
```
auth       optional       ${pkgs.pam_reattach}/lib/pam/pam_reattach.so  # nix-darwin: security.pam.enablePAMReattach
```

**Comment by emilazy** [comment]
Agreed! https://github.com/LnL7/nix-darwin/pull/1020 will fix this in passing.

**Comment by alkimake** [comment]
Sorry, could not find the other issues and PR earlier. We can close this I guess ?

**Comment by Enzime** [comment]
Closing as a duplicate of #985
