### ISSUE TITLE
No fonts produced in the `/run/current-system/sw/share/fonts/` directory

### ISSUE THREAD

**Issue by terlar** [LnL7/nix-darwin#115]
No fonts end up in this directory, but I can see that the packages include the fonts. And then later when it is supposed to symlink these fonts it fails, e.g.:

```
resetting fonts...
updating fonts...
ln: failed to access '/run/current-system/sw/share/fonts/Arimo-Bold.ttf': No such file or directory
```

My configuration is very simple:
```
  fonts = {
    enableFontDir = true;
    fonts = [
      pkgs.iosevka-slab
      pkgs.noto-fonts
      pkgs.noto-fonts-extra
      pkgs.noto-fonts-cjk
    ];
  };
```

**Comment by terlar** [comment]
I wonder if it is a hen and egg problem, I got it working now, by setting the `enabledFontDir` to `false`, running `darwin-rebuild switch -Q` and then seeing that the fonts were generated to the `/run/current-system/sw/share/fonts/` directory and then enabling it and then all worked.

**Comment by LnL7** [comment]
Sounds like the activation is looking in current-system instead of the system that's being activated, current-system changes at the very end when everything is ready.

**Comment by abathur** [comment]
I ran into the same issue. Process described by @terlar worked.
