### ISSUE TITLE
Why are there no `userActivationScripts` like `system.activationScripts`?

### ISSUE THREAD

**Issue by minizilla** [LnL7/nix-darwin#1153]
I see that nix-darwin only have [activationScripts](https://daiderd.com/nix-darwin/manual/index.html#opt-system.activationScripts._name_.enable), why no `userActivationScripts`? what's the alternative?

**Comment by Enzime** [comment]
Some of the activation scripts run at user level, if you want to run things at user level you can set:

```nix
system.activationScripts.postUserActivation.text = ''
  echo test
'';
```

**Comment by Enzime** [comment]
The activation scripts run when you run `darwin-rebuild switch`

**Comment by minizilla** [comment]
Okay, so when things run at user level, I'm expecting the $HOME is correctly set, but turned out it's not.
