### ISSUE TITLE
Ability to disable specific checks in modules/system/checks.nix

### ISSUE THREAD

**Issue by kyren** [LnL7/nix-darwin#117]
So, the way I manage nixos machines (and now my macos laptop, thanks nix-darwin!) is pretty non-standard.

I don't use channels and I don't keep my system configuration in /etc/nixos.  Instead, I have a single git project with the configuration of all of my machines (including user-level configuration through home-manager) so they can share modules.  The goal is to absolutely minimize state and hidden inputs, so deploy scripts clear NIX_PATH before calling nixos-rebuild / darwin-rebuild and everything is specified via -I flags.

The `nixPath` checks in modules/system/checks.nix get in the way of this by looking at the resulting NIX_PATH and trying to make sure that I'll still be able to use darwin-rebuild with no extra options after switching, which I don't want.  NIX_PATH will contain a 'nixpkgs' entry only which is set to whatever nixpkgs was at the time the system was built and nothing else, so this check fails.

Currently I have something like this in my configuration as a hack:
```
nix.nixPath = [
  "nixpkgs=/etc/nixpkgs"

  # HACK: 'darwin' and 'darwin-config' must exist for checks to pass when
  # activating nix-darwin configurations, these will not work nor does it
  # matter if they work.
  "darwin=${<darwin>}"
  "darwin-config=${./configuration.nix}"
];
```

You can disable the entire checks.nix activation script in the same way the uninstaller does it with `system.activationScripts.checks.text = mkForce "";`, but this seems a bit extreme since the rest of the checks are very useful.  (I also currently do something similar to disable symlinking `~/Applications`, and this works fine).

I don't know how many of these checks are really sensible to disable, it may be that just the `nixPath` checks make sense to disable and none of the others, but it would be nice to have an option to disable the `nixPath` checks at least.

**Comment by kyren** [comment]
Thanks, seems to work great! 👍

**Comment by LnL7** [comment]
It's only this specific case at the moment since it's the main one where it makes sense to disable in some cases, but others could be added if there's a usecase for those.
