### ISSUE TITLE
enabling nix-gc for single-user install changes store ownership to root after each GC

### ISSUE THREAD

**Issue by abathur** [LnL7/nix-darwin#118]
I've been having a little trouble with nix-darwin and finally pinned it down this evening. Rough summary--nix and nix-darwin would work fine after install for a while, but a few hours/days later I'd notice I was getting lockfile permission failures.

After some testing, it looks like /nix/store is owned by root:nixbld after every automatic GC (I can run ser GC fine). I'm not too familiar with launchd/launchctl so I don't know the consequence of doing so, but a little reading made me wonder if nix-gc should be set up in `launchd.agents` for single-user installs, and added to `launchd.daemons` only for multi-user?

I've disabled the auto GC for now. Since I had trouble finding enough information to sort this out for a few days, I'll leave the error messages here on the off chance other searchers will find it. The most common form was:

`error: opening lock file '/nix/store/<...>.drv.lock': Permission denied`

**Comment by LnL7** [comment]
Yeah, the main problem here is the fact that agents and daemons have different startup behaviour. A daemon starts after boot while agents only start once a user is logged in, this has some problems problems. On a headless builder there's probably no user logged in so it would never run and if it's a system agent it would run for every user which won't work for a single user install either.

A better way to handle this is to make the daemon run as the user that owns the store instead of root, along with some validation to avoid this case.

```nix
{ pkgs, ... }:
{
  nix.gc.automatic = true;
  launchd.daemons.nix-gc.serviceConfig.UserName = "admin";
}
```

**Comment by abathur** [comment]
I agree. For UX, though, I wondered if the orientation could/should be inverted since single-user is the default.

In either case, I gave this a try but the check is always objecting. With config like:

	nix.gc.user = "abathur";
	nix.gc.automatic = true;

I get:

	09:51:52 ~$ darwin-rebuild switch
	building the system configuration...
	these derivations will be built:
	  /nix/store/fskk8z7w5bizvjv4lnpbidxvx8z6aa7c-org.nixos.nix-gc.plist.drv
	  /nix/store/nad3pibblz2n1xmk5phmwrdd5yng5hdl-launchd.drv
	  /nix/store/cfnag4pj6v8baw5mlxr1rxz590r0bwav-darwin-system-19.03pre-git.drv
	building '/nix/store/fskk8z7w5bizvjv4lnpbidxvx8z6aa7c-org.nixos.nix-gc.plist.drv'...
	building '/nix/store/nad3pibblz2n1xmk5phmwrdd5yng5hdl-launchd.drv'...
	building '/nix/store/cfnag4pj6v8baw5mlxr1rxz590r0bwav-darwin-system-19.03pre-git.drv'...

	CHANGELOG
	<snip>
	error: A single-user install can't run gc as root, aborting activation
	Configure the garbage collector to run as the current user:

	    nix.gc.user = "abathur";

	09:53:01 ~$ ls -la /nix/
	total 0
	drwxr-xr-x     4 abathur  wheel     128 Dec 27 21:35 .
	drwxr-xr-x    36 root     wheel    1152 Jan  1 15:32 ..
	drwxrwxr-t  3799 abathur  wheel  121568 Jan  3 09:52 store
	drwxr-xr-x     4 abathur  wheel     128 Dec 27 21:35 var

**Comment by LnL7** [comment]
My bad, the condition was wrong.

**Comment by abathur** [comment]
Seeing a failure with the check now. Commented inline at https://github.com/LnL7/nix-darwin/commit/28710738a3ca7c9a16d63b89c904588d030edf01#r31833454

**Comment by abathur** [comment]
Hmm. Back to seeing `error: A single-user install can't run gc as root, aborting activation` as in the previous post. I think I see the issue at `if test -O /nix/store; then` (https://github.com/LnL7/nix-darwin/commit/72b3648fa0e0a9ed165131381bab80fe51e72578#diff-89c05f497205568442da7cbb81718deaR139)

	16:10:33 ~$ ls -l /nix
	total 0
	drwxrwxr-t  3811 abathur  wheel  121952 Jan  3 16:02 store
	drwxr-xr-x     4 abathur  wheel     128 Dec 27 21:35 var
	16:10:37 ~$ test -O /nix/store; echo $?
	0
	16:11:24 ~$ test ! -O /nix/store; echo $?
	1
