### ISSUE TITLE
wrong shell and PATH inside tmux

### ISSUE THREAD

**Issue by MarkusLohmayer** [LnL7/nix-darwin#1181]
Regarding nix-darwin config I have `programs.zsh.enable = true;` and as HM config I have `programs.zsh.enable = true;`

If I open a terminal window, I get a ZSH prompt and PATH is, as desired, `/opt/homebrew/bin:/Users/markus/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin`

However, if I run `tmux`, the prompt says "sh-3.2$" and PATH is `/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/bin:/Users/markus/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin`, which is of no use to me.

The SHELL variable is `/bin/zsh`, inside and outside of tmux. I am not sure why it is not the zsh installed through Nix.

If I run `/bin/zsh` inside tmux, the PATH I get is `/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/bin:/Users/markus/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin`, which is better, but not the same as outside of tmux (desired behavior).

I am not sure why this changed recently, but I think it has nothing to do with my particular config.

Any help on this would be much appreciated!

**Comment by Enzime** [comment]
What's the output from `dscl . -read /Users/$USER UserShell`?

**Comment by MarkusLohmayer** [comment]
UserShell: /bin/zsh

**Comment by MarkusLohmayer** [comment]
I am very sorry for reporting the issue in the wrong place.
I just found out that using the tmux package from nixpgks stable solves the issue.
