### ISSUE TITLE
Build failing after a nix  flake update command, on Mac OS(intel): Sequoia 15.0.1 

### ISSUE THREAD

**Issue by Halloway-93** [LnL7/nix-darwin#1195]
nix run --extra-experimental-features "nix-command flakes" nix-darwin -- switch --flake ~/.config/nix-darwin
building the system configuration...
error: builder for '/nix/store/fa3wcxf0z8ny1rw9j6dm5v9q9pvm266g-darwin-system-25.05.20241122.8edf06b+darwin4.3c52583.drv' failed with exit code 1;
       last 7 log lines:
       >
       > In /nix/store/w8k3bpg96xawssqnq6b9mxlyngbm118m-darwin-system-25.05.20241122.8edf06b+darwin4.3c52583/activate line 80:
       > while read src; do
       >       ^--^ SC2162 (info): read without -r will mangle backslashes.
       >
       > For more information:
       >   https://www.shellcheck.net/wiki/SC2162 -- read without -r will mangle backs...
       For full logs, run 'nix-store -l /nix/store/fa3wcxf0z8ny1rw9j6dm5v9q9pvm266g-darwin-system-25.05.20241122.8edf06b+darwin4.3c52583.drv'.

**Comment by Enzime** [comment]
Check if `while read src` is in your configs and change it to `while read -r src`

**Comment by Halloway-93** [comment]
Thanks a lot it solved my problem.

**Comment by paixaop** [comment]
Hi, is there a permanent fix for this? I'm running in to the same error. It does get fixed with with the "while read -r src" but every time I update  it's back to the error.

**Comment by Samasaur1** [comment]
What do you mean that it goes back to the error every time you update? If the `while read src` line is in nix-darwin, let us know/open an issue/PR so that we can fix it permanently. If the line is in your config, changing it once should solve the problem.

**Comment by paixaop** [comment]
Thank you @Samasaur1  the issue was on my own flake file. Added the read -r and everything is working. Nothing wrong with nix darwin.  Sorry I’m a nix newbie
