### ISSUE TITLE
(attempt to) set environment vars globally

### ISSUE THREAD

**Issue by sellout** [LnL7/nix-darwin#12]
It would be fantastic if environment variables were set globally, not just for bash/zsh/etc. Unfortunately, Apple has made this extremely difficult.

Over the years/versions, environment variables have been set via /etc/environment, /etc/launchd.conf, and /Library/LaunchAgents/environment.plist (with probably some others along the way). I don’t think any of these work in Sierra (but I could be wrong). Maybe the last would work with `defaults write com.apple.dt.Xcode UseSanitizedBuildSystemEnvironment -bool NO`, judging by some googling.

[This](https://github.com/hschmidt/EnvPane#why-cant-i-set-path-with-envpane) also seems to indicate that `$PATH` is going to get trounced no matter what.

Anyway … trying all of these, or maybe even selectively choosing one based on OS X version, or something would be great.

**Comment by LnL7** [comment]
What about `launchctl setenv`? I think that might be a more reliable way to configure it for applications, etc...

**Comment by sellout** [comment]
@LnL7 Yeah, that is what “/Library/LaunchAgents/environment.plist” basically is – you put a bunch of `launchctl setenv` entries in there. Is there a way for nix-darwin to run those commands at startup/login without needing to use the plist file?

Clearly, my understanding of these things is a bit hand-wavy.

**Comment by LnL7** [comment]
I think it might be preserved across reboots. If that's not the case [`services.activate-system`](https://github.com/LnL7/nix-darwin/blob/master/modules/services/activate-system.nix) could be used to set it at boot time, just like the `/run/current-system` symlink.
