### ISSUE TITLE
Can't change user shell

### ISSUE THREAD

**Issue by tedbyron** [LnL7/nix-darwin#1209]
```
-sh-3.2$ cat /etc/shells
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh

# List of shells managed by nix.
/run/current-system/sw/bin/bash
/run/current-system/sw/bin/zsh

-sh-3.2$ echo $SHELL
/run/current-system/sw/bin/zsh

-sh-3.2$ dscl . -read /users/ted/ UserShell
UserShell: /run/current-system/sw/bin/zsh

-sh-3.2$ echo $0
-sh
```

Both dscl and $SHELL show the correct shell but any time I open a new shell it uses apple bash. Any idea why this could be happening? I'm using [`programs.zsh`](https://github.com/tedbyron/dotfiles/blob/main/users/ted/programs/zsh.nix) and have [`users.users.ted.shell = pkgs.zsh`](https://github.com/tedbyron/dotfiles/blob/main/users/ted/default.nix#L21). `chsh` also doesn't do anything because it's already set to the correct shell but running the wrong one

**Comment by Enzime** [comment]
What terminal are you using? Have you added yourself to `users.knownUsers`?

**Comment by tedbyron** [comment]
> What terminal are you using? Have you added yourself to `users.knownUsers`?

Tried both alacritty and apple's terminal program. I am not currently using `users.knownUsers`, am I supposed to be?

**Comment by tedbyron** [comment]
Gotcha thanks, can I ask why it says not to add admin users to knownUsers in the docs? I assumed I shouldn't add my account because it's the only account on the computer and is an admin

**Comment by Enzime** [comment]
Ah, I forgot to update that, basically it’s because adding a user to `knownUsers` means that nix-darwin manages them and if you delete them from the configuration, nix-darwin will delete the user, however I’ve added some protections to prevent deleting the user you’re running `darwin-rebuild switch` as so it should be fine

Have you tried restarting your computer?

**Comment by tedbyron** [comment]
I added myself to `knownUsers`, ran `darwin-rebuild switch ...`, fully power cycled my computer, still got the same issue. Issue first appeared when I switched to the 24.11 release of nixpkgs & home manager.

**Comment by Enzime** [comment]
Are you setting the `SHELL` environment variable somewhere?

**Comment by tedbyron** [comment]
Nope

**Comment by Enzime** [comment]
Have you tried quitting Terminal.app and opening it fresh?

**Comment by tedbyron** [comment]
Yeah I killed the tmux session too, no change

**Comment by Enzime** [comment]
In the menus there should be a New Command option and if you use that and put `/run/current-system/sw/bin/zsh` does it work?

**Comment by tedbyron** [comment]
No, that's what is currently entered in that setting
<img width="614" alt="image" src="https://github.com/user-attachments/assets/bdf9a84b-b9f6-4775-b311-ee9f1b7a0931">

**Comment by Enzime** [comment]
What happens if you change that back to `Default login shell`? Also what happens if you run `New Command` with `/bin/zsh`?

**Comment by tedbyron** [comment]
Thanks for the help, the issue has to do with something in my tmux config - just rebuilt without tmux and it's fine.

**Comment by tedbyron** [comment]
Looks like tmux just doesn't use my shell when I start it up

**Comment by Enzime** [comment]
I have no `tmux` configuration and it launches the correct shell. You can run a `tmux` server then run `tmux show -g`

**Comment by Enzime** [comment]
```
$ tmux show -g
...
default-command ''                                                              
default-shell /run/current-system/sw/bin/zsh
...

**Comment by tedbyron** [comment]
<img width="1086" alt="image" src="https://github.com/user-attachments/assets/79517c7a-9d2b-47f3-be62-cce1570dbc23">
there's the issue, trying to track down how the default-command is getting set now

**Comment by Enzime** [comment]
According to this commit, `reattach-to-user-namespace` is not necessary anymore:

https://github.com/LnL7/nix-darwin/commit/9a04aea8ea1e7e8a6382516e4ac1f8b9245c4b09

Maybe you can just override it with `set -g default-command ''` somewhere in your config?

**Comment by Enzime** [comment]
Looks like there's a pull request to fix this: https://github.com/tmux-plugins/tmux-sensible/pull/75

**Comment by Enzime** [comment]
It looks like `reattach-to-user-namespace` is only used if that command exists:

https://github.com/tmux-plugins/tmux-sensible/blob/25cb91f42d020f675bb0a2ce3fbd3a5d96119efa/sensible.tmux#L102-L104

So you can make sure the package is not installed and you don't need to set anything else

**Comment by tedbyron** [comment]
Thanks for the help!
