### ISSUE TITLE
Uninstalled package still exist

### ISSUE THREAD

**Issue by jiezhuzzz** [LnL7/nix-darwin#1217]
Hi all, I know this question may seem silly, but I searched around and couldn't find an answer, so I need to ask it here. When I add a package `rio` (a terminal emulator) like

```nix
environment.systemPackage = with pkgs; [
    ...
    rio
    ...
]
```

and then remove `rio` from the package list, I can still find it in my applications.

I have tried rebuilding my flake and performing garbage collection, but it is still there. Is there any way to completely delete it? Or I missed some steps? Thanks in advance!

**Comment by maxRN** [comment]
What's the output of `which rio`? Maybe you have installed as well through some other means.
What exact garbage collection commands did you run? Did you run them as root?

**Comment by jiezhuzzz** [comment]
Thank you for your response! I have the same question, so I will close this issue.
