### ISSUE TITLE
Nix-darwin install with flake on macOS Sequoia 15.2 fails. Requires enabling the nix-daemon service

### ISSUE THREAD

**Issue by teehemkay** [LnL7/nix-darwin#1221]
Trying to install nix-darwin (macOS Sequoia 15.2 (24C101) on a Mac mini M1) using flakes (after installing nix using Determinate Systems nix installer) yields the following error message:

```
~ % nix run nix-darwin -- switch --flake ~/.config/nix-darwin 
building the system configuration...
Password:
setting up /run via /etc/synthetic.conf...
error: The daemon is not enabled but this is a multi-user install, aborting activation
Enable the nix-daemon service:

    services.nix-daemon.enable = true;

or set

    nix.useDaemon = true;
```

See also: https://github.com/LnL7/nix-darwin/commit/5d1b7ac696c2c9cf4206d7fbd3ebe3daa3b9bbd2

Adding the following to the `flake.nix` solved the issue:

`services.nix-daemon.enable = true;`

**Comment by Enzime** [comment]
It should be enabled by default as of https://github.com/LnL7/nix-darwin/commit/a35b08d09efda83625bef267eb24347b446c80b8: https://github.com/LnL7/nix-darwin/blob/a35b08d09efda83625bef267eb24347b446c80b8/modules/services/nix-daemon.nix#L11-L15

Can you post your config?

**Comment by teehemkay** [comment]
@Enzime Oops, sorry for the bogus report. I hadn't updated my `flake.lock` which was still targeting  LnL7/nix-darwin/fd0e3ed30b75ddf7f3d94829d80a078b413b6244' (2024-10-12)
