### ISSUE TITLE
launchd.user.agents: ensure ~/Library/LaunchAgents is present before attempting to copy plist file

### ISSUE THREAD

**Issue by abathur** [LnL7/nix-darwin#134]
Ran into an issue with a missing path while standing up a fresh system after adding my first launchd.user.agents task:

    cp: cannot create regular file '/Users/abathur/Library/LaunchAgents/org.nixos.backup.plist': No such file or directory

In chat, you linked here: https://github.com/LnL7/nix-darwin/blob/9f18c937710854768ea8d437fe92f5e5bee92a92/modules/system/launchd.nix#L34-L48

:)

**Comment by LnL7** [comment]
Good catch. 😄
