### ISSUE TITLE
Changed <darwin-config> but target does not exist, aborting activation

### ISSUE THREAD

**Issue by NickSeagull** [LnL7/nix-darwin#137]
I'm trying to setup a [dotfiles repo](https://github.com/NickSeagull/dotfiles), where the main configuration file for my system Nix environment is there.

The idea is to have that repo cloned into `~/.dotfiles`, and then do a 

```bash
darwin-rebuild switch -I "darwin-config=/Users/nick/.dotfiles/nix/darwin.nix"
```

To start using the environment there. The issue is, that I cannot activate it, as it fails with a

```text
error: file 'darwin-config' was not found in the Nix search path (add it using $NIX_PATH or -I)
error: Changed <darwin-config> but target does not exist, aborting activation
Create ~/.nixpkgs/darwin-configuration.nix or set environment.darwinConfig:

    environment.darwinConfig = "/Users/nick/.dotfiles/nix/darwin.nix";

And rebuild using (only required once)
```

I went ahead and added that to the default file, as instructed, but still fails with the same error message.

I have tried uninstalling `nix-darwin`, then reinstalling `nix` and reinstalling `nix-darwin` again, with no satisfactory results, any idea?

I'm running MacOS Mojave 10.14.4

Thanks for this effort!

**Comment by yurrriq** [comment]
I found lots of inspiration from @peel: https://github.com/peel/dotfiles. My less fancy dotfiles for reference: https://github.com/yurrriq/dotfiles

**Comment by NickSeagull** [comment]
@yurrriq thanks for commenting! 😄 

Somehow, I'm uncapable of seeing the relation between the links and the error I'm getting 😅 .

As I can see, peel is using 

```
darwin-rebuild switch -j4 -I "darwin-config=$HOME/.config/nixpkgs/machines/darwin/configuration.nix" -I "nixpkgs-overlays=$HOME/.config/nixpkgs/overlays" -I "nurpkgs-peel=$HOME/.config/nurpkgs" -I "setup=$HOME/.config/nixpkgs/setup"
```

to setup his Nix setup. I'm doing more or less the same command, except that I'm not setting up nur, nor any overlays.

My issue is geared towards the fact that I cannot use Nix at all with a custom configuration file :(

**Comment by LnL7** [comment]
This is indeed strange. Activating a new system will validate that `darwin-config` exists to avoid problems but as far as I can see you configured that properly to also point to the new location. Perhaps the output of this command will give an idea why the config file can't be found.

```bash
nix-instantiate --eval --strict '<darwin>' -A config.nix.nixPath -I "darwin-config=$HOME/.dotfiles/nix/darwin.nix"
```

ps. I described here https://github.com/LnL7/nix-darwin/wiki/Changing-the-configuration.nix-location how to setup your configuration in a different location.

**Comment by NickSeagull** [comment]
Nope, still fails with the same error ☹️ 

Perhaps a clean install would work, but I'm doing something wrong in doing so? Currently I'm running a

```bash
sudo rm -rf /nix
rm -rf ~/.nix*
```

Any ideas?

**Comment by LnL7** [comment]
I don't see anything that indicates there's a problem with your nix installation, building the system itself works fine so reinstalling won't help. What's the output of that command?

You can also run this to see what it's doing exactly at that point.

```bash
darwin-rebuild build  # args...
bash -x ./result/activate-user
```

Alternatively this check can be disabled, but I would be very surprised if darwin-rebuild works like expected afterwards.

```
{
  system.checks.verifyNixPath = false;
}
```

**Comment by LnL7** [comment]
Oh, I see what the problem is. You configured both `environment.darwinConfig` and `nix.nixPath`, the latter takes precedence and doesn't include a `darwin-config` entry.

https://github.com/NickSeagull/dotfiles/blob/267d777ef20cf83fa65a6730fce82e43b27bd669/nix/darwin.nix#L59

**Comment by NickSeagull** [comment]
Ouch! I ported my config from my laptop and left that off, thank you so much!!! 😄

**Comment by LnL7** [comment]
Ideally the nixPath option would merge named entries by default instead. I might look into that, otherwise I'll make the check a bit more clear for this case.

**Comment by NickSeagull** [comment]
Thanks @LnL7 , you rock! 😄
