### ISSUE TITLE
bash 5

### ISSUE THREAD

**Issue by abathur** [LnL7/nix-darwin#142]
I finally got around to checking out bash 5 this afternoon and am interested in giving it a go as my default interactive shell. I'm not sure how easy this should/shouldn't be; wanted to bring it up for discussion.

I tried most naive version: adding the package to shells. This wasn't helpful; the setup for programs.bash steps all over it. Disabling programs.bash is enough to get it launching, but then the usual bashrc stuff built in by programs.bash is missing which causes its own problems.

I guess the usual idiom would be an option to set the package used, but I'm not sure it's "right" to add one here since the nixos version doesn't do this. If we did add an option, there's also some chance some nix shell script incompatibilities will cause problems. Making it easier to change could get more eyes on potential incompatibilities with bash 5. Not sure whether either of those _should_ affect the decision.

Related:
https://github.com/NixOS/nixpkgs/pull/53687
https://github.com/NixOS/nixpkgs/pull/53628

**Comment by LnL7** [comment]
This is already possible by overriding `bashInteractive` but overlays can cause unintended rebuilds, a package option would avoid that.

```nix
{ pkgs, ... }:
{
  nixpkgs.overlays = [
    (self: super: {
      bashInteractive = super.bashInteractive_5;
    })
  ];
}
```

**Comment by Enzime** [comment]
Closing this as setting `users.users.<name>.shell = pkgs.bashInteractive;` should set your default shell to Bash 5
