### ISSUE TITLE
manage openssh authorized keys for users

### ISSUE THREAD

**Issue by domenkozar** [LnL7/nix-darwin#152]
Seems like everyone has their own wrappers for this, would be best if it was supported in nix-darwin instead.

**Comment by jamiesteven** [comment]
I too would very much like this. Unfortunately, I couldn't find any way to accomplish this. I'd very much welcome any wrappers people have for this.

**Comment by jamiesteven** [comment]
@domenkozar Did you happen to find a way to do this? My attempt using Home Manager (https://github.com/LnL7/nix-darwin/issues/562#issuecomment-1344729748) only works if sshd config option StrictModes = false.
