### ISSUE TITLE
Can't install in macOS 10.11 : "dyld: Symbol not found: _clock_gettime"

### ISSUE THREAD

**Issue by m2habert** [LnL7/nix-darwin#164]
I'm using (El Capitan) 10.11.6 :  really positive that I read somewhere that El Cap was fine for nix-darwin...

(Anyway, I can't find the requirements. Searched for issues with "10.11", "el capitan", "_clock_gettime" to no avail. On the other hand, there's a post elsewhere about "clock_gettime not found on Mac OSX 10.11.6 "... )

¿Does nix-darwin requires Sierra and up?

Sorry, I'm probably more noob than knowledgable... but I thought that nix-darwin was the way to go...

Error:
`./result/bin/darwin-installer`

...outputs:
```
Installing nix-darwin...

Would you like edit the default configuration.nix before starting? [y/n] n
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /nix/store/q1l6qh8dgf4sa0zbja6d0ykybjs1fjvi-libc++-6.0.1/lib/libc++.1.0.dylib (which was built for Mac OS X 10.12)
  Expected in: /nix/store/0ikg6z03p88xir1m4q3540vvdiddqssb-Libsystem-osx-10.12.6/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /nix/store/q1l6qh8dgf4sa0zbja6d0ykybjs1fjvi-libc++-6.0.1/lib/libc++.1.0.dylib (which was built for Mac OS X 10.12)
  Expected in: /nix/store/0ikg6z03p88xir1m4q3540vvdiddqssb-Libsystem-osx-10.12.6/lib/libSystem.B.dylib

```

**Comment by eraserhd** [comment]
Nixpkgs itself bumped the minimum OS version to 10.12 a few months ago.  I'm surprised you got this far instead of getting a minimum version required error.

**Comment by m2habert** [comment]
When you say "nixpkgs", you're probably referring to the channel, right? ¿But why the channel would close up to a lesser OS version? Packages consolidated in the past should be perfectly all right for (slightly) older OS, no?

**Comment by LnL7** [comment]
The 19.03 release still supports 10.11 and older, but since May master and the unstable channel requires 10.12 as the minimum version. The apple SDK was updated along with a bunch of other things https://github.com/NixOS/nixpkgs/pull/47678.

This repository is currently not really tied to a specific os version, if you use the nixpkgs-19.03-darwin channel everything should work.
