### ISSUE TITLE
What's needed for Catalina?

### ISSUE THREAD

**Issue by dhess** [LnL7/nix-darwin#166]
What's required to get `nix-darwin` working with Catalina? Here, I mean just `nix-darwin`-specific issues, not the `nixpkgs` issues as discussed in https://github.com/NixOS/nix/issues/2925

In `#nix-darwin` on Freenode, user `cransom` suggested that a `/run` entry in `synthetic.conf` is needed. Also, he claims that `synthetic.conf` requires hard tabs, rather than spaces.

Any other issues? Let's catalogue them here.

**Comment by mroi** [comment]
Any details as to why `/run` is needed? It was not needed before Catalina.

Apart from the setup problems in NixOS/nix#2925, I don’t have any issues with my Nix setup on Catalina.

**Comment by dhess** [comment]
`nix-darwin` has relied on `/run` since I've been using it. Just grep the source tree for numerous examples of where and how it's used.

**Comment by dhess** [comment]
This seems relevant:

https://github.com/NixOS/nix/issues/3125

**Comment by alanpearce** [comment]
I added a line to `/etc/synthetic.conf` after following the instructions for nix like so:

```
run	/System/Volumes/Data/private/var/run/
```
I don't know if it's the correct destination, I just know it should be `private/var/run` from some `$PWD`, based upon this: https://github.com/LnL7/nix-darwin/blob/132a7f0a09d222df25604836893e3420b1c165cf/pkgs/darwin-installer/configuration.nix#L56

The installer worked, I'm just encountering some build issues switching to my real configuration.

**Comment by LnL7** [comment]
The main reason for using `/run` was consistency with nixos, it isn't strictly necessary and could be moved or even made configurable if needed.

**Comment by steshaw** [comment]
> I added a line to `/etc/synthetic.conf` after following the instructions for nix like so:
> 
> ```
> run	/System/Volumes/Data/private/var/run/
> ```

Yep, looks like that works.

> I don't know if it's the correct destination, I just know it should be `private/var/run` from some `$PWD`, based upon this:
> 
> https://github.com/LnL7/nix-darwin/blob/132a7f0a09d222df25604836893e3420b1c165cf/pkgs/darwin-installer/configuration.nix#L56

It seems that putting a relative directory into `synthetic.conf` works fine too:

```
run	/System/Volumes/Data/private/var/run/
```

`man synthetic.conf` states:

> synthetic.conf describes virtual symbolic links and empty directories to be created at the root mount point

The installer (and docs for manual installation) could use:

```bash
printf 'run\tprivate/var/run\n' | sudo tee -a /etc/synthetic.conf
```

However, that does require a reboot, so if `nix-darwin` can be changed to use `/private/var/run` directly, maybe that's the way to go?

**Comment by dhess** [comment]
`fonts.enableFontDir` fails on Catalina because the Nix store is now on a separate filesystem.

**Comment by srid** [comment]
Installation of nix-darwin is currently broken on Catalina:

```
error: the path '/nix' is a symlink; this is not allowed for the Nix store and its parent directories
```

**Comment by cmacrae** [comment]
@srid You can mitigate this by setting `NIX_IGNORE_SYMLINK_STORE=1` 🙃

**Comment by LnL7** [comment]
Yeah, the nix build from my installer branch will get overwritten with `pkgs.nix` by default.

**Comment by ashkan-leo** [comment]
I finally was able to install nix on Catalina.
I tried to install nix-darwin, but I have issues creating /run. I added `run /System/Volumes/Data/private/var/run/` to `/etc/synthetic.conf`, but I'm still unable to create `/run`.

I used the script in https://github.com/NixOS/nix/pull/3212 to install Nix (script is authored by @LnL7). Any chance a similar approach can be taken here?

**Comment by LnL7** [comment]
Yeah, except in this case a symlink is fine and was already the default in the installer.

```
echo "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf
/System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -B
```
