### ISSUE TITLE
User creation error on installation

### ISSUE THREAD

**Issue by herberteuler** [LnL7/nix-darwin#170]
I had this issue during installation:

```
creating user nixbld9...
<main> attribute status: eDSRecordAlreadyExists
<dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)
```

which was because user id 30009 was already taken by another user.

**Comment by maelp** [comment]
I have the same issue, how can it be fixed?

**Comment by herberteuler** [comment]
@maelp I simply manually created the user with another id. The issue was submitted as a reminder to create a patch for the user creation code. I may write a patch if I had time.

**Comment by maelp** [comment]
You created it with the System Preferences app?

**Comment by herberteuler** [comment]
No, by using the same command-line tool in the script but providing a manually filled id.

**Comment by maelp** [comment]
I'm not sure which command-line tool it is, could you show me the command you are using?

**Comment by herberteuler** [comment]
The code seems to have been changed a lot since the issue was submitted, but it looks like this is the code you are looking for: https://github.com/LnL7/nix-darwin/blob/master/modules/users/default.nix#L155

**Comment by Enzime** [comment]
Closing this as the `nixbld` users will be created by the Nix installer initially rather than `nix-darwin`, the default UID range for `nixbld` users is now `350-382` and a lot of the logic for handling user creation has changed
