### ISSUE TITLE
Unsetting `__NIX_DARWIN_SET_ENVIRONMENT_DONE` in tmux module?

### ISSUE THREAD

**Issue by herberteuler** [LnL7/nix-darwin#173]
I am having an issue that in a fresh tmux session, `PATH` is set in a way that `/run/current-system/sw/bin` comes after `/usr/bin`, `/bin` etc.

My `/etc/profile` looks like this:

```
# System-wide .profile for sh(1)

if [ -x /usr/libexec/path_helper ]; then
        eval `/usr/libexec/path_helper -s`
fi

if [ "${BASH-no}" != "no" ]; then
        [ -r /etc/bashrc ] && . /etc/bashrc
fi
```

It seems that `__NIX_DARWIN_SET_ENVIRONMENT_DONE` needs to be unset too in the tmux module. Otherwise, `set-environment`, which is already sourced in the shell in which `tmux` is executed, will not be sourced again and certain environment variables e.g. `PATH` will not be set properly in the bash session in tmux.

**Comment by herberteuler** [comment]
Nevermind, it was due to an existing tmux socket file.

**Comment by eraserhd** [comment]
I think the idea is that if this is set, the variables have already been initialized _and exported_, so subshells don't need to do this again.

This means that if you change your config, you won't see it until you log in again, unless you have something like [`:r`](https://github.com/eraserhd/dotfiles/blob/develop/bash/default.nix#L44-L63) to reload the shell, which I stole from @LnL7 I think?

**Comment by herberteuler** [comment]
Yes, that is the intention. But in the tmux setting, every new window starts a login shell, at least [by default](https://github.com/LnL7/nix-darwin/blob/da52dc006c42e25757f7b2f4aac398cf448a389d/modules/programs/tmux.nix#L119). This means `/etc/profile` will be loaded and the whole initialization process needs to be done for every such session.

**Comment by herberteuler** [comment]
My actual trouble was that I installed `coreutils` only with Nix, and in a tmux shell basic commands such as `ls` went to `/bin/ls` without my proposed change.
