### ISSUE TITLE
zsh: command not found: darwin-rebuild

### ISSUE THREAD

**Issue by idmyn** [LnL7/nix-darwin#177]
Hi, thanks for the project :)

I'm having two issues (which I expect are related). When I run `darwin-rebuild switch` I get the error `zsh: command not found: darwin-rebuild`. I also can't get packages listed in `~/.nixpkgs/darwin-configuration.nix` to install when I run `/run/current-system/sw/bin/darwin-rebuild switch`. I'm running Catalina and included `NIX_IGNORE_SYMLINK_STORE=1; export NIX_IGNORE_SYMLINK_STORE` in my `~/.zprofile` as per https://github.com/LnL7/nix-darwin/issues/166#issuecomment-558813578.

Output of `echo $PATH`:
```
/Users/david/.rvm/gems/ruby-2.6.3/bin:/Users/david/.rvm/gems/ruby-2.6.3@global/bin:/Users/david/.rvm/rubies/ruby-2.6.3/bin:/Users/david/.gem/ruby/2.6.3/bin:/Users/david/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/bin:/Users/david/.rubies/ruby-2.6.3/bin:/Users/david/.pyenv/shims:/Users/david/.nix-profile/bin:/Users/david/.nix-profile/bin:/Users/david/.nvm/versions/node/v12.6.0/bin:/Users/david/.pyenv/shims:/Users/david/.gem/ruby/2.6.3/bin:/Users/david/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/bin:/Users/david/.rubies/ruby-2.6.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/david/.nvm/versions/node/v12.6.0/bin:/Users/david/.yarn/bin:/Users/david/.config/yarn/global/node_modules/.bin:/Users/david/go/bin:/Users/david/.local/bin:/Users/david/.rvm/bin
```

Output of `echo $NIX_PATH`:
```
darwin-config=/Users/david/.nixpkgs/darwin-configuration.nix:/nix/var/nix/profiles/per-user/root/channels:/Users/david/.nix-defexpr/channels:/Users/david/.nix-defexpr/channels
```

Output of `/run/current-system/sw/bin/darwin-rebuild switch`:
```
building the system configuration...
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
user defaults...
setting up user launchd services...
Password:
setting up ~/Applications...
setting up /etc...
system defaults...
setting up launchd services...
configuring networking...
```

I've tried the steps described in https://github.com/LnL7/nix-darwin/issues/158#issuecomment-539220435 and my symlinks show up exactly the same as they appear in the screenshot there.

If I add a new package to `~/.nixpkgs/darwin-configuration.nix` (`pkgs.tldr`) and run `/run/current-system/sw/bin/darwin-rebuild switch`, I get this output:
```
building the system configuration...
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
these derivations will be built:
  /nix/store/8fmpn18l623fwqkm66z5bk4bj0vdcjrg-system-path.drv
  /nix/store/fyjcw2slj7klpmfix35yahh88kpp8hsa-system-applications.drv
  /nix/store/i4faqvpaxbvjj3yd54hpr0whpz9ig1qr-darwin-system-20.03pre202154.58fb23f72ad+darwin4.0000000.drv
these paths will be fetched (0.09 MiB download, 0.90 MiB unpacked):
  /nix/store/079adg7j53wgkabnr1rm2xzjf0dgca63-libzip-1.5.2
  /nix/store/bfsjfpv3vbdb0cai476647i8sl1nkhq6-tldr-1.3.0
copying path '/nix/store/079adg7j53wgkabnr1rm2xzjf0dgca63-libzip-1.5.2' from 'https://cache.nixos.org'...
copying path '/nix/store/bfsjfpv3vbdb0cai476647i8sl1nkhq6-tldr-1.3.0' from 'https://cache.nixos.org'...
building '/nix/store/fyjcw2slj7klpmfix35yahh88kpp8hsa-system-applications.drv'...
building '/nix/store/8fmpn18l623fwqkm66z5bk4bj0vdcjrg-system-path.drv'...
created 0 symlinks in user environment
created 261 symlinks in user environment
building '/nix/store/i4faqvpaxbvjj3yd54hpr0whpz9ig1qr-darwin-system-20.03pre202154.58fb23f72ad+darwin4.0000000.drv'...
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
user defaults...
setting up user launchd services...
Password:
setting up ~/Applications...
setting up /etc...
system defaults...
setting up launchd services...
configuring networking...
```
It looks like the package is being installed, but there's no sign of it in `~/.nix-profile/bin`.

If I run `nix-env -i tldr` I get this output:
```
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
installing 'tldr-1.3.0'
building '/nix/store/zkjs1qrkkxxxa6csy4bqyaagwj9asmnm-user-environment.drv'...
created 365 symlinks in user environment
```
It then shows up in `~/.nix-profile/bin` and `which tldr` shows `/Users/david/.nix-profile/bin/tldr`.

Any ideas what's gone wrong? Thanks!

**Comment by ericpashman** [comment]
Hmm ...
 
1. What's the output of `env | grep NIX`?
2. Are you on Catalina? If yes, how did you set up Nix? In particular, how did you setup `/env` to be writable (symlink vs mounting it as a new APFS volume)?
3. Is `zsh` support enabled by uncommenting the relevant line in your `darwin-configuration.nix`?
4. What do your `/etc/zshrc` and `/etc/zshenv` look like?

**Comment by idmyn** [comment]
1. output of `env | grep NIX`:
```
__NIX_DARWIN_SET_ENVIRONMENT_DONE=1
NIX_PATH=darwin-config=/Users/david/.nixpkgs/darwin-configuration.nix:/nix/var/nix/profiles/per-user/root/channels:/Users/david/.nix-defexpr/channels:/Users/david/.nix-defexpr/channels
NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
NIX_PROFILES=/nix/var/nix/profiles/default /Users/david/.nix-profile
NIX_IGNORE_SYMLINK_STORE=1
```

2. I am on Catalina, and I installed Nix for the first time on Catalina using the script hosted [here](https://static.domenkozar.com/install-catalina) (which I found here: https://github.com/NixOS/nix/issues/2925#issuecomment-552244858). I also added `NIX_IGNORE_SYMLINK_STORE=1; export NIX_IGNORE_SYMLINK_STORE` to my `~/.zshenv`

3. It should be! My `darwin-configuration.nix` is [here](https://github.com/idmyn/dotfiles/blob/master/nix/darwin-configuration.nix)

4. My `~/.zshrc` is [here](https://github.com/idmyn/dotfiles/blob/master/shell/.zshrc)
  My `/etc/zshrc` looks like this:
```
# /etc/zshrc: DO NOT EDIT -- this file has been generated automatically.
# This file is read for interactive shells.

# Only execute this file once per shell.
if [ -n "$__ETC_ZSHRC_SOURCED" -o -n "$NOSYSZSHRC" ]; then return; fi
__ETC_ZSHRC_SOURCED=1

# history defaults
SAVEHIST=2000
HISTSIZE=2000
HISTFILE=$HOME/.zsh_history

setopt HIST_IGNORE_DUPS SHARE_HISTORY HIST_FCNTL_LOCK

bindkey -e




# Tell zsh how to find installed completions
for p in ${(z)NIX_PROFILES}; do
  fpath+=($p/share/zsh/site-functions $p/share/zsh/$ZSH_VERSION/functions $p/share/zsh/vendor-completions)
done

autoload -U promptinit && promptinit && prompt walters

autoload -U compinit && compinit
autoload -U bashcompinit && bashcompinit







# Read system-wide modifications.
if test -f /etc/zshrc.local; then
  source /etc/zshrc.local
fi
```
...and my `/etc/zshenv`:
```
# /etc/zshenv: DO NOT EDIT -- this file has been generated automatically.
# This file is read for all shells.

# Only execute this file once per shell.
# But don't clobber the environment of interactive non-login children!
if [ -n "$__ETC_ZSHENV_SOURCED" ]; then return; fi
export __ETC_ZSHENV_SOURCED=1

# Don't execute this file when running in a pure nix-shell.
if test -n "$IN_NIX_SHELL"; then return; fi

if [ -z "$__NIX_DARWIN_SET_ENVIRONMENT_DONE" ]; then
  . /nix/store/447ymca87zbdydzm2vcjlm8rbn3q5hpp-set-environment
fi



# Read system-wide modifications.
if test -f /etc/zshenv.local; then
  source /etc/zshenv.local
fi
```
Thanks for your help!

**Comment by ericpashman** [comment]
OK, sorry for not noticing initially, but I think the only problem may be that you don't have `/run/current-system/sw/bin` in your system PATH. Add that and you should be able to run `darwin-rebuild` and the other `nix-darwin` commands without specifying the whole path.

That path, `/run/current-system/sw/bin`, is also where symlinks to binaries of packages specified in your `~/.nixpkgs/darwin-configuration.nix` will be created, not in `~/.nix-profile/bin` (the actual binaries in both cases are in subdirectories of `/nix/store/`). Look in there and you should see the `tldr` binary.

Other than that, I don't notice anything amiss. Your Nix-related environment variables are fine, as is your `zsh` configuration.

**Comment by idmyn** [comment]
Yup, that's fixed it! Sorry I didn't think to investigate `/run/current-system/sw/bin/` from the get-go, but I'm grateful to have everything set-up now :)

Thanks again.

**Comment by bestlem** [comment]
I have the same issue - what should be adding /run/current-system/sw/bin to the PATH?

**Comment by loganlinn** [comment]
In case it is helpful to anybody else who lands here:
If `env | grep NIX` output is empty, check that you have `programs.zsh.enable = true` in your configuration.
This sets up `/etc/zshenv`, `/etc/zshrc`  to add `/run/current-system/sw/bin` to PATH and set other NIX-related envs

**Comment by webhive** [comment]
> check that you have programs.zsh.enable = true in your configuration.

Seems this is a correct and most straightforward solution.

**Comment by aimestereo** [comment]
> In case it is helpful to anybody else who lands here:
> If env | grep NIX output is empty, check that you have programs.zsh.enable = true in your configuration.
> This sets up /etc/zshenv, /etc/zshrc to add /run/current-system/sw/bin to PATH and set other NIX-related envs

I want to iterate on correct answer from a noob perspective. Parameter
```
programs.zsh.enable = true;
```
exists in `home-manager` and on higher levels darwin/nixos configurations. In my case, setup was broken until I've put it to darwinConfiguration.

simplified example
```
# in flake.nix
nix-darwin.lib.darwinSystem {
  modules = [ ./configuration.nix ];
  specialArgs = { inherit inputs; };
}

# in configuration.nix
# Update the system environment.
programs.zsh.enable = true;
```

P.S. silly, but I spent half a day on solving it.

**Comment by yeoffrey** [comment]
For people who messed up, realized that they never enabled `zsh` like the above answer said, here is what you should run after you add `programs.zsh.enable = true;` to your flake:

```
/run/current-system/sw/bin/darwin-rebuild switch --flake path/to/flake
```

**Comment by mrjson79** [comment]
Awsome findings @aimestereo - i accidently did the same. And thanks to your findings i was able to solve it.
Ad thanks for the tips @yeoffrey regarding the PATH.

**Comment by andikayopr** [comment]
In my case, after add this line `programs.zsh.enable = true; `. I should restart my terminal and then darwin-rebuild command now available.
