### ISSUE TITLE
Allow installation to a prefix other than /etc

### ISSUE THREAD

**Issue by dhess** [LnL7/nix-darwin#20]
I'd love to use this system, but I'm loath to touch system-managed areas like `/etc`. It appears there are at least a few places in the current implementation where `/etc` is hard-wired. Would it be difficult to allow the user to specify an alternate install location?

**Comment by loskutov** [comment]
As [FHS states](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s07.html), `/etc` contains configuration files and thus it's user-managed by definition.

**Comment by dhess** [comment]
You know we're talking about a project for macOS here, right?

**Comment by loskutov** [comment]
Of course, and macOS developers also state /etc contains system configuration files and scripts (see [hier(7)](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man7/hier.7.html)). Obviously, configuration is supposed done by a user, so it appears to be just the right place for a package manager to store its files.

However, it wouldn't kill anyone to have more flexibility anyway 😃

**Comment by Enzime** [comment]
We don't plan to support this as macOS uses `/etc` and we need to manage some files in there
