### ISSUE TITLE
Getting started: check installation success and `darwin-rebuild` commands

### ISSUE THREAD

**Issue by thomasheartman** [LnL7/nix-darwin#202]
Hi,

I recently tried to get started with Nix Darwin, but ran into some issues. I think I got most of it set up, but I never got properly started because I ran into a few important issues.

This issue is mostly just reporting what I already left in [this comment](https://github.com/LnL7/nix-darwin/issues/2#issuecomment-618270486) on issue #2. I never got a response there, though, so I thought I'd open a separate issue in case it somehow slipped through the cracks.

There are a few questions in that comment, but the most relevant ones are:
- How do I check whether the installation has worked as expected?
- How do I get `darwin-rebuild` in my path? I've manually sourced `/etc/static/config.fish` in my config, but I still need to find and then provide the full path to run rebuild.

Appreciate all your hard work and I'm quite excited about this project. 

Cheers.

**Comment by LnL7** [comment]
There are a few quirks with etc files currently that are handled separately in the installer, but other than that and setting up the channel there's not really much of a difference with normal activation.

If you have issues with PATH it's generally one of the following issues.
- Your user shell wasn't enabled in configuration.nix (not the case here since /etc/static contains fish)
- Your user dotfiles change PATH and overwrite it instead of extending. User rc files are loaded after /etc so anything set there will have precedence.

**Comment by thomasheartman** [comment]
Thanks for getting back to me.

I don't think I'm overwriting my PATH anywhere in any of my config files, but I could very well be wrong. Is there an easy way to find out?

**Comment by thomasheartman** [comment]
Just a little update on my end. I tried removing and reinstalling Nix and then Nix-Darwin. Nix is working fine, but `darwin-rebuild` still isn't found.

On installation, I got this:
```
building the system configuration...
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
Would you like to manage <darwin> with nix-channel? [y/n] y
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
error: file 'darwin' was not found in the Nix search path (add it using $NIX_PATH or -I)
error: Changed <darwin> but target does not exist, aborting activation
Add the darwin repo as a channel or set nix.nixPath:
$ nix-channel --add https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin
$ nix-channel --update

or set

    nix.nixPath = [ "darwin=/nix/store/8xd2343m8p31r7vrsy2df9r7m18ypml2-master.tar.gz" ];
```

- What does 'Would you like to manage <darwin> with nix-channel?' mean? What's the alternative?
- How do I proceed? I added the channel and updated, but nothing. It doesn't say where (what file) to set `nix.nixPath`. Is this in the darwin-config file?

**Comment by LnL7** [comment]
I'm not familiar with fish so can't really help with details there, but with bash or zsh you could try to make enable tracing so you can see what's happening during shell setup and in what order.

```nix
{ lib, ... }:
with lib;
{
  environment.etc."zshenv".text = mkBefore ''
    set -x
  '';
}
```
```
+/etc/zshrc:35> setopt PROMPTSUBST
+/etc/zshrc:41> PS1='%F{red}%B%(?..%? )%b%f%# '
+/etc/zshrc:42> RPS1='$(_prompt_nix)%F{green}%~%f'
+/etc/zshrc:44> [ -n '' ']'
+/etc/zshrc:49> autoload -U compinit
+/etc/zshrc:49> compinit
```

**Comment by thomasheartman** [comment]
Thanks! I tried that (and using zsh) but it didn't seem to make a difference. I checked out the config files and realized there was a clause that checked for whether you're in a nix shell or not, which caused it to not work. When exiting the nix shell, zsh correctly picks up the commands.

Interestingly (or maybe as expected?), when launching fish from a zsh session with the commands, I get them in fish too. However, just launching straight into fish doesn't work.

Sadly I don't know how to enable tracing in fish either. I've spent some time searching, but I haven't been able to find anything. But then again, I wasn't able to find any information on `set -x` for zsh/bash by searching the web either. I don't actually know _what_ to search for in this case.

What I do know, though, is that all the `__fish_nix_darwin_*_config_sourced` variables are set to `1`, indicatiing that at the very least, `/etc/static/fish/config.fish` has been executed as expected.

**Comment by LnL7** [comment]
Definitively sounds like it's your user dotfiles then, only other suggestion I can give is to search for PATH or one of the entries that it still contains in your dotfiles.

A quick search did bring up fish_trace for me.
> The fish_trace variable may be set to trace execution (#3427). This performs a similar role as set -x in other shells.

```nix
{ lib, ... }:
with lib;
{
  environment.etc."fish/config.fish".text = mkBefore ''
    set fish_trace 2
  '';
}
```

**Comment by thomasheartman** [comment]
Actually, I think I might have figured it out. I was reading through the `nix-env.fish` file and noticed a comment that says:

```sh
  # nixpkgs-installed fish tries to set these up already if NIX_PROFILES is defined, which won't ...
```

And thought I'd give installing Fish via nix a go. When running this version of Fish, it works perfectly well. The old version was installed via Homebrew. Is this intended or is it just a weird coincidence?

It may well be that there is something in my dotfiles overwriting the PATH, though I don't think there is. I think I did a purge a while back, but I may be mistaken. 

After switching to Nix Fish, I'm running into some problems with tmux trying to start Zsh instead of Fish, but I don't think that's related to darwin-nix.

Thanks for the assistance! If I can't get tmux to work, I'll go back to brew Fish and try the tracing approach.
