### ISSUE TITLE
Multiple expressions don't build

### ISSUE THREAD

**Issue by WhatisRT** [LnL7/nix-darwin#209]
I'm not sure if I'm having a wrong channel selected or something, but on a fresh install on a newly setup machine, I have multiple expressions that fail to build:
- `gst-plugins-bid-1.16.2` fails with no error message, just the nix error message that the builder failed
- `texlive-core-big.bin-2019` fails because the clang linker cannot find the library for `-lzzip`

I've tried to switch to the stable 20.03 nixpkgs channel (from the default unstable) but that didn't help, and I while I could find some relation between tex and the linker error, it seemed unrelated to macos or nix, and it didn't really help with anything. I expect that this is an issue with `nix-darwin`, because it seems unlikely to me that the stable nixpkgs channel is that broken, but I wouldn't know how to test that.

**Comment by LnL7** [comment]
Unless you have overlays in your configuration.nix that do something special there's nothing in nix-darwin that would influence builds like this. You're most likely not using the channel you are expecting.

You can pass a channel straight to the build to ensure nothing else is going on.

```
$ darwin-rebuild build -I nixpkgs=channel:nixpkgs-20.03-darwin
building the system configuration...
these derivations will be built:
  /nix/store/mh1pbszi3lz3jlahqph43kfzm6r2cp11-options-db.xml.drv
  /nix/store/9988wfi0gl349bqfzzps65q49qpxbg0s-generated-docbook.drv
  /nix/store/10fwnvjbq5xxvhc5h18mddvdw245vp26-darwin-manual-combined.drv
  /nix/store/9xvag0i080cmb758zfs9j5f3rar4mh61-manual-olinkdb.drv
  /nix/store/4hfxg27kpz3jzx1i46cd0hzg4aqhmzqj-darwin-manpages.drv
  /nix/store/q0g9hlsgwjkvi52b1rhpycgg0h3kfqq5-darwin-manual-html.drv
  /nix/store/p2z24nhjbvzim7mlxfj1m5jq76n4cpvh-darwin-help.drv
  /nix/store/fhyc7sp5arn80wfwpd42a49jw3jy1gh0-system-path.drv
  /nix/store/la0imf8gd6dszq6xgfwgdw49v9d4p6fl-system-applications.drv
  /nix/store/frhl9a6sv1csxvs480zlmsz213wlr1z1-darwin-system-20.03pre215215.b3dcc2bfead+darwin4.47fe6db.drv
building '/nix/store/mh1pbszi3lz3jlahqph43kfzm6r2cp11-options-db.xml.drv'...
building '/nix/store/9988wfi0gl349bqfzzps65q49qpxbg0s-generated-docbook.drv'...
building '/nix/store/10fwnvjbq5xxvhc5h18mddvdw245vp26-darwin-manual-combined.drv'...
```

Note that the name of the resulting system is also darwin-system-20.03 compared to 20.09 as you'd expect based on the input.

**Comment by WhatisRT** [comment]
Thanks, that flag was helpful! I actually had the unstable channel selected even though `nix-channel --list` (as root and regular user) didn't show it...

**Comment by LnL7** [comment]
Did you run nix-channel --update after changing the channel? Adding a channel only changes the channel list, the expressions won't change until the next time they are updated.

**Comment by WhatisRT** [comment]
I'm pretty sure I did, I tried a bunch of stuff before posting this issue. I fixed it by removing, adding and updating the channel and that terminal is sadly gone, so I don't know what changed.
