### ISSUE TITLE
Viability for `nixpkgs.pkgs` option, similar to NixOS

### ISSUE THREAD

**Issue by jamesottaway** [LnL7/nix-darwin#211]
I'm looking to pin my `nixpkgs` set and went looking for inspiration. I found the [`nixpkgs.pkgs` option in NixOS](https://nixos.org/nixos/options.html#nixpkgs.pkgs) and where it [sets `_module.args.pkgs`](https://github.com/NixOS/nixpkgs/blob/release-20.03/nixos/modules/misc/nixpkgs.nix#L230-L232).

I poked around `modules/nix/nixpkgs.nix` and found a [comment indicating nix-darwin uses a different approach](https://github.com/LnL7/nix-darwin/blob/master/modules/nix/nixpkgs.nix#L112). The [commit in question](https://github.com/LnL7/nix-darwin/commit/b1a264c928fdb7e674c0e9f9fe2edbe5c04f5bb2) talks about overriding the `nixpkgs` argument in [`release.nix`](https://github.com/LnL7/nix-darwin/blob/master/release.nix), hence this issue.

Is there a reason that the `_module.args.pkgs` approach is incompatible with overriding the `nixpkgs` argument in [`release.nix`](https://github.com/LnL7/nix-darwin/blob/master/release.nix)? If not I'll put a PR up for the `nixpkgs.pkgs` option, but if not I'd love to know more about the motivation behind b1a264c928fdb7e674c0e9f9fe2edbe5c04f5bb2 and how to avoid the two goals clashing.

**Comment by jamesottaway** [comment]
I just saw the Flakes support so I think this issue is redundant now. Amazing work, by the way. I've already switched over and I love it: https://github.com/jamesottaway/nix-config/blob/master/flake.nix

**Comment by LnL7** [comment]
Apologies for not responding.  I'm not particularly opposed to adding this but I feel like it makes much more sense to to declare this kind of stuff top down instead of overriding it at such a late point.  So unless somebody needs it for a very specific use-case I would prefer to keep this simple.

**Comment by jamesottaway** [comment]
No worries about not getting back to me, I just wanted to throw the idea out into the ether while I was tinkering. I ended up wanting to pin my copy of this repo too and actually ended up doing something very similar to #231.

I totally agree about the top-down thing. I'd read a bit about Flakes before today but #235 finally got me to try it and it's definitely the right way to pin the package set.
