### ISSUE TITLE
Missing many options

### ISSUE THREAD

**Issue by jsravn** [LnL7/nix-darwin#218]
In the past I've used https://github.com/mathiasbynens/dotfiles/blob/main/.macos, since it sets a lot of reasonable defaults (especially in recent OSX versions which are trying to make it like iOS). nix-darwin is missing a good chunk of these - probably over half of the settings. For now I've stuck these in an activation script, but I'd much prefer it to be declarative.

If you're open to it, I can make a PR adding many/most of these options.

**Comment by LnL7** [comment]
I only started with the main things I use, but additions are welcome.  But if you want to add many it might be worth looking into generalising this a bit more to make that less cumbersome.
