### ISSUE TITLE
Add folder icon for Nix

### ISSUE THREAD

**Issue by matthewbauer** [LnL7/nix-darwin#23]
A while ago I made a folder icon to use for the /nix/ directory:

![folder-icon](https://cloud.githubusercontent.com/assets/19036/25260061/48775cb6-260f-11e7-9b92-69ff36494708.png)

It's just an old macOS folder with the Nix logo on top of it. Here's the script to set it up:

https://github.com/matthewbauer/macNixOS/blob/master/install-folder-icon.sh

Is there any way to integrate this into nix-darwin? I haven't looked much on the inner workings and I suspect that it would be "impure" because SetFile is closed-source and /nix, etc...

**Comment by LnL7** [comment]
There's a hook to add custom activation scripts, something like this probably works. Note that this will execute every time you run `darwin-rebuild switch` not sure if that's ideal.

```nix
{ config, lib, pkgs, ... }:

let
  icon = ./nix-mac-icon.rsrc;
in

{
  activationScripts.extraActivation.text = ''
    Rez -append ${icon} -o $"/nix/Icon\r"
    SetFile -a C /nix
    SetFile -a V $"/nix/Icon\r"
  '';
}
```
