### ISSUE TITLE
Installation without channels on multi-user install

### ISSUE THREAD

**Issue by felixscheinost** [LnL7/nix-darwin#231]
I'm trying to setup a configuration that is shared across several machines.
For perfect reproducability I don't want to use channels at all.
Therefore I used `niv` to pin `nixpkgs` and `nix-darwin`.

To do so I created a custom "installer" which looks like this:

```
    # Location of the darwin-configuration file
    config="$HOME/.nix-darwin/darwin-configuration.nix"

    # Modify NIX_PATH so that our nixpkgs and nix-darwin version are included
    export NIX_PATH=darwin=${sources.nix-darwin}:darwin-config=$config:nixpkgs=${sources.nixpkgs}:$NIX_PATH

    # Build and switch to configuration
    $(nix-build ${sources.nix-darwin} -A system --no-out-link)/sw/bin/darwin-rebuild build
    $(nix-build ${sources.nix-darwin} -A system --no-out-link)/sw/bin/darwin-rebuild switch
```

inside `darwin-configuration.nix` I added the same modifications to `NIX_PATH`:

```
  nix.nixPath = [
    { nixpkgs = "${sources.nixpkgs}"; }
    { darwin-config = "$HOME/.nix-darwin/darwin-configuration.nix"; }
    { darwin = "${nix-darwin-src}"; }
  ];
```

This seems to work! I can manage `nixpkgs` and `home-manager` using niv.
I developed and tested this on one machine and it seems that `~/.nix-defexpr/channels` was setup correctly there "accidentally".

Now I am trying to bootstrap a new machine. I did a fresh installation of macOS and a Nix multi-user install.
The multi-user install sets up `~/.nix-defexpr/channels` to point to `/nix/var/nix/profiles/per-user/root/channels`.

When I try to `switch` to the intial configuration I get:

```
The ~/.nix-defexpr/channels symlink does not point your users channels, aborting activation
```

My questions:

1) Would it make sense to manage `nix-darwin` like I want to?
2) Why does `nix-darwin` contain this check to `~/.nix-defexpr/channels`?
3) Is this check also required if I don't manage `nix-darwin` using `nix-channel`?

**Comment by LnL7** [comment]
1. Sure, channels are still the standard way of distributing expressions. Pinning is generally a better approach for deployment usecases. Note that this approach has a quirk that updating your sources won't apply until NIX_PATH has updated (eg. start a new shell after switching). So you'll have to switch, restart your shell and switch again or pass in the inputs manually.

2. The `~/.nix-defexpr/channels` check looks unrelated to all this, it doesn't have to exist but having it point to another user's channels doesn't make sense.  If I recall correctly this situation can happen when sudo is used incorrectly to update system channels, resulting in your local user not being able to update channels anymore.

3. There is another check to validate that NIX_PATH contains valid entries in order for darwin-rebuild to work. For usecases where the sources are always explicitly passed in this isn't really needed. So if you want to disable that you can use `system.checks.verifyNixPath = false;`.

**Comment by felixscheinost** [comment]
> Sure, channels are still the standard way of distributing expressions. Pinning is generally a better approach for deployment usecases. Note that this approach has a quirk that updating your sources won't apply until NIX_PATH has updated (eg. start a new shell after switching). So you'll have to switch, restart your shell and switch again or pass in the inputs manually.

Thanks! That's a good point, didn't think about that.

 We came up with a new approach now:
We have some directory, we called it `NIX_PATH` into which we symlink three files:

- darwin-config
- nixpkgs
- darwin

All three files import the respective packages from `sources.nix`.

Then we put just this directory (which isn't in the nix store) into the NIX_PATH.
This way we will use the updated nixpkgs immediately after doing a `niv update`

> The ~/.nix-defexpr/channels check looks unrelated to all this, it doesn't have to exist but having it point to another user's channels doesn't make sense. If I recall correctly this situation can happen when sudo is used incorrectly to update system channels, resulting in your local user not being able to update channels anymore.

Hmm, I still think the official nix installer sets it up that way. I'm trying to find the place in the source where this happens.

**Comment by felixscheinost** [comment]
Also we worked around the main issue by always running `darwin-rebuild` as root using sudo (we wrote a shell function to do that).

One reason is that this always works - even on a fresh installation of macOS + Nix (which currently doesn't #234)

More importantly, my opinion is that `nix-darwin` shouldn't modify $HOME at all! I notice that this is a pretty big thing to say so let me explain 😃 

My reasoning is that if nix-darwin modifies $HOME (e.g. [applications.nix](https://github.com/LnL7/nix-darwin/blob/master/modules/system/applications.nix)) then the state of the system depends on which user ran `nix-darwin`.

But as my machines are multi-user systems I want to have the same end result irregardless of which user ran darwin-rebuild.

This means that all user-specific configuration should happen using home-manager where the username is eplicitly specified. 

What do you think?

**Comment by LnL7** [comment]
Closing since `system.checks.verifyNixPath`, also used by the flake overrides, solves the problem here.

Regarding $HOME I mostly agree, but there is some grey area like user launch agents. Linking applications should probably be global, I've mentioned that before on one of the open issues related to that module.
