### ISSUE TITLE
Running into installation issues with channels

### ISSUE THREAD

**Issue by nathanshelly** [LnL7/nix-darwin#234]
First off thanks for all the work you've put into this project!

I'm having an issue running the installer via the instructions in the README on a multi-user Catalina install:

```log
> ./result/bin/darwin-installer
Would you like to edit the default configuration.nix before starting? [y/n] n
building the system configuration...
Would you like to manage <darwin> with nix-channel? [y/n] n
Would you like to load darwin configuration in /etc/bashrc? [y/n] n
grep: /etc/zshrc: No such file or directory
Would you like to load darwin configuration in /etc/zshrc? [y/n] y
if test -e /etc/static/zshrc; then . /etc/static/zshrc; fi
Would you like to create /run? [y/n] y
setting up /etc/synthetic.conf...
error: The ~/.nix-defexpr/channels symlink does not point your users channels, aborting activation
Running nix-channel will regenerate it

    rm ~/.nix-defexpr/channels
    nix-channel --update
```

When I tried to `rm ~/.nix-defexpr` it failed with permission denied so I ran `sudo rm ~/.nix-defexpr`. Running `nix-channel --update` then fails:

```log
> nix-channel --update
unpacking channels...
error: creating symlink from '/Users/loaner/.nix-defexpr/.0_channels' to '/nix/var/nix/profiles/per-user/loaner/channels': Permission denied
```

Any suggestions what I could do to fix this?

Also, if you don't mind two tangential questions:

1. Is there documentation somewhere for the implications of the choices for these two questions?
> Would you like to manage \<darwin\> with nix-channel? [y/n] n
> Would you like to create /run? [y/n] y
2. I noticed #231 asks about a reproducible multi-user installation without relying on channels via `niv`. Is that the current best way to get a reproducible install without channels? Is `nix-darwin` planning to add flake support going forward?

**Comment by LnL7** [comment]
That's unexpected, did you ever mess with permissions? The directories in `/nix/var/nix/profiles/per-user` should each be owned by the respective user. The permissions should look something like this:
```
drwxr-xr-x  4 root wheel .
drwxr-xr-x  6 lnl  wheel lnl
drwxr-xr-x  4 root wheel root
```

As for the other questions:
1. Not really, but almost every step is required unless you explicitly configured an alternative before.
2. I've done an experiment with flakes but nothing polished yet, I should probably make something that's good enough to be merged sometime.

**Comment by nathanshelly** [comment]
> That's unexpected, did you ever mess with permissions? The directories in `/nix/var/nix/profiles/per-user` should each be owned by the respective user. The permissions should look something like this:
> 
> ```
> drwxr-xr-x  4 root wheel .
> drwxr-xr-x  6 lnl  wheel lnl
> drwxr-xr-x  4 root wheel root
> ```

I'm not aware of ever having messed with permissions. `ls -l /nix/var/nix/profiles/per-user` gives me:

```log
❯ ls -l /nix/var/nix/profiles/per-user
drwxr-xr-x  9 loaner  wheel  288 Oct 18 14:14 loaner
drwxr-xr-x  5 root    wheel  160 Oct 17 21:46 root
```

Anything else I should check?

>     1. Not really, but almost every step is required unless you explicitly configured an alternative before.

So just to double check you're suggest that in the default case I should be answering `y` to both of them?

>     2. I've done an experiment with flakes but nothing polished yet, I should probably make something that's good enough to be merged sometime.

Gotcha, look forward to helping test whatever the eventual solution is.

**Comment by LnL7** [comment]
Yeah that looks good, I'm also a bit confused why you're getting an error then.

Accepting everything and removing the channel once you have the niv configuration setup is probably the easiest. As for flakes I actually worked on that today since I didn't really have anything planned for the NixCon hackathon. I'll probably merge it soon :smile:.

**Comment by nathanshelly** [comment]
Okay, will try wiping the machine and rerunning the installer to see what I get. Thanks for the prompt responses.

Will dig into the niv solution while eagerly looking forward to your flake work!

**Comment by nathanshelly** [comment]
So I tried on a bare install after wiping the machine and ran into the same symlink permissions issue:

```log
building '/nix/store/a0jx77yq81czp3m3k12k8f2l0wydqv37-darwin-system-21.03pre246624.cfed29bfcb2+darwin4.0000000.drv'...
building the system configuration...
warning: Nix search path entry '/Users/nathan/.nix-defexpr/channels' does not exist, ignoring
Would you like to manage <darwin> with nix-channel? [y/n] y
these derivations will be built:
  /nix/store/hbcb74pazjxfk4fvhn1xyn57cj6p5a0x-darwin.drv
building '/nix/store/hbcb74pazjxfk4fvhn1xyn57cj6p5a0x-darwin.drv'...
unpacking channels...
created 1 symlinks in user environment
error: creating symlink from '/Users/nathan/.nix-defexpr/.0_channels' to '/nix/var/nix/profiles/per-user/nathan/channels': Permission denied
```

`nix-channel --update` also gives me the same. Any suggestions on next steps? Otherwise will try wiping laptop again at some point and try to isolate `nix-channel` behavior before running the `nix-darwin` installer since I didn't think to this time.

**Comment by LnL7** [comment]
Actually come to think of it, I think I also ran into this with github actions. I assumed this was related to the the action but perhaps not? https://github.com/LnL7/nix-darwin/blob/8800c4717d242651d06654729f7bf17ce6026bb3/.github/workflows/test.yml#L21-L23

No idea what could be causing this however, only special thing I can think about is the umask . https://github.com/LnL7/nix-darwin/blob/77121650d42cbc11d5a62a9e466b0433324659fb/modules/system/activation-scripts.nix#L50-L51

**Comment by nathanshelly** [comment]
Interesting, thanks for the additional context! Don't know much about how `umask` works so if you have any tips for debugging/confirming that the `umask` is in fact the issue would be happy to test them out. Regardless will try and dig in more to see what I can figure out.

**Comment by nathanshelly** [comment]
I'm not entirely sure what the issue was here but I'm no longer experiencing it so closing this out. Thanks for the help!

**Comment by nathanshelly** [comment]
I recently set up a Github Action to test my dotfiles and it's made me realize this issue seems to still exist. I created a [minimal repro](https://github.com/nathanshelly/sandbox/tree/nix-darwin-installation). This repro runs [this setup script](https://github.com/nathanshelly/sandbox/tree/82dd49a0925318c1e4dfb1606b8e2a0cc596a196/setup.sh) which attempts to install Nix then `nix-darwin` and [fails with the same error message](https://github.com/nathanshelly/sandbox/runs/1585457429) mentioned above:

```log
building the system configuration...
warning: Nix search path entry '/Users/runner/.nix-defexpr/channels' does not exist, ignoring
...
created 1 symlinks in user environment
error: creating symlink from '/Users/runner/.nix-defexpr/.0_channels' to '/nix/var/nix/profiles/per-user/runner/channels': Permission denied
```

I found a workaround for the moment. Deleting [`~/.nix-defexpr` and recreating channels](https://github.com/nathanshelly/sandbox/commit/49f32a73938f317af44ac4ea0836b7bb30368446) between Nix and `nix-darwin` installation leads to a [successful `nix-darwin` installation](https://github.com/nathanshelly/sandbox/runs/1585465370).

**Comment by nathanshelly** [comment]
thanks for the quick fix!

**Comment by shaunsingh** [comment]
Just note for anyone else that might have this issue 

The instructions tell you to `rm -r ~/.nix-defexpr/channels` then run `nix-channel --update`
For me, I had to run `sudo rm -r ~/.nix-defexpr` then `sudo nix-channel --update` for it to work

**Comment by gak** [comment]
Just ran into this one. My fix was to reboot after the rm + update instructions. Worked immediately after the reboot.

**Comment by jensmeindertsma** [comment]
I'm running into this issue using nix-darwin in a flake. So channels are unrelated? If I delete `~/.nix-defexpr` I can run `darwin-rebuild switch --flake .` once, then it regenerates `~/.nix-defexpr` and the next invocation of `darwin-rebuild` will fail. I installed Nix using the Determinate Systems installer. What can I do to debug this issue?

**Comment by jadc** [comment]
For anyone still having this problem, try running darwin-rebuild with sudo and the user flag.

```
sudo -u $USER darwin-rebuild switch --flake .
```

I'm not sure if this has any negative repercussions, but it fixed the issue for me.

**Comment by rabejens** [comment]
I am running into this one too, but nothing helps for me. I am not using channels, only flakes.

**Comment by Enzime** [comment]
If you’re not using channels, you can add `nix.channel.enable = false;` to your configuration

**Comment by rabejens** [comment]
For now I forked nix-darwin, removed the check in my fork and installed it from there. It is a rather quick and dirty workaround, but for now that works.
