### ISSUE TITLE
error: file 'darwin' was not found in the Nix search path (add it using $NIX_PATH or -I)

### ISSUE THREAD

**Issue by PlumpMath** [LnL7/nix-darwin#239]
I'm reinstall macOS and install success nix-darwin.
I've used it before nix-darwin.
how to set $NIX_PATH in ~/.zshrc... I use Catalina default shell, zsh. and set ~/.zshrc.
but I install nix multi user. 
maybe would set /etc/static/zshrc?
help me~

Thanks.

**Comment by PlumpMath** [comment]
cat /etc/zshenv                                                       ~
# /etc/zshenv: DO NOT EDIT -- this file has been generated automatically.
# This file is read for all shells.

# Only execute this file once per shell.
# But don't clobber the environment of interactive non-login children!
if [ -n "$__ETC_ZSHENV_SOURCED" ]; then return; fi
export __ETC_ZSHENV_SOURCED=1

# Don't execute this file when running in a pure nix-shell.
if test -n "$IN_NIX_SHELL"; then return; fi

if [ -z "$__NIX_DARWIN_SET_ENVIRONMENT_DONE" ]; then
  . /nix/store/ldhzwk3zvj1gdj1n8yhlk0hdzl982c1e-set-environment
fi



# Read system-wide modifications.
if test -f /etc/zshenv.local; then
  source /etc/zshenv.local
fi


hmm g,.g
. /nix/store/ldhzwk3zvj1gdj1n8yhlk0hdzl982c1e-set-environment

**Comment by PlumpMath** [comment]
. /nix/store/ldhzwk3zvj1gdj1n8yhlk0hdzl982c1e-set-environment

I don't know if it's right to add this line. It does work. But I want to know how to do it properly.
Thanks!

**Comment by LnL7** [comment]
Did you open a new shell / terminal window? Environment loading is only executed once per shell as you can see in the snippet. It's only needed once since subshells will inherit the environment from their parent and prevents problems where the /etc overrides variables which can be pretty confusing.

```sh
__ETC_ZSHENV_SOURCED= NIX_REMOTE=local zsh -c 'echo NIX_REMOTE=$NIX_REMOTE'
NIX_REMOTE=local
```
```sh
__NIX_DARWIN_SET_ENVIRONMENT_DONE= __ETC_ZSHENV_SOURCED= NIX_REMOTE=local zsh -c 'echo NIX_REMOTE=$NIX_REMOTE'
NIX_REMOTE=daemon
```

This does mean that a fresh shell is needed when the environment changes, since it doesn't get refreshed otherwise.

**Comment by happysalada** [comment]
I also get the same error.
In order for the option `nix.nixPath` to work, a shell needs to be enabled right?
I have nix.nixPath set, and a shell defined with home manager (fish).
When I start a new terminal, $NIX_PATH is not defined. And when I try to run `darwind-rebuild switch` I get the error inn the title of this issue.

**Comment by PlumpMath** [comment]
Return to single mode. I hope all the operating systems will be tamed with nix. Happy happy happy ㅎ.ㅎ

**Comment by LnL7** [comment]
@happysalada Yes, if you use a non default shell the corresponding `programs.<shell>.enable` must also be enabled for everything to be configured. But in that case darwin-rebuild wouldn't be in your PATH either so this issue specifically should be either a stale environment or something else in dotfiles that overwrites NIX_PATH all-together.

**Comment by happysalada** [comment]
For those running into the same issue.

If you configure your shell with something like home-manager, you will also need to enable the shell in `darwin-configuration.nix`. I thought the shell config files would conflict with each other, but they don't (at least in the case of fish).
For my case (fish) `programs.fish.enable` in `darwin-configuration.nix` and in `home-manager.nix` solved the problems of not having my `PATH` and `NIX_PATH` set correctly.

@LnL7 Thanks a ton!
