### ISSUE TITLE
kwm/khdrc configs not being found

### ISSUE THREAD

**Issue by arnm** [LnL7/nix-darwin#24]
I'm using the lnl.nix kwm and khd configurations and I see that the files are being created in /etc/per-user/{user}/... However kwm and khd do not read from that location. When I copy the files to $HOME/.khdrc and $HOME/kwm/.kwmrc everything start working as expected.

Any ideas?

**Comment by LnL7** [comment]
Yeah, I have not added support for files in arbitrary locations yet because I also want those files to be removed correctly. For my configuration I manually created these symlinks one time as a workaround until this is implemented properly.


```
$ ls -l ~/.khdrc ~/.kwm
lrwxr-xr-x  1 lnl  staff  30 Jan  5 20:18 .khdrc -> /etc/per-user/lnl/khdrc
lrwxr-xr-x  1 lnl  staff  28 Jan  5 20:18 .kwm -> /etc/per-user/lnl/kwm
```

**Comment by arnm** [comment]
That workaround works fine for me. Is there an issue for this feature?

**Comment by LnL7** [comment]
You can now manage your khdrc/kwmrc.

```nix
{
  services.khd.enable = true;
  services.khd.khdConfig = ''
    # remap modifier only ctrl to escape.
    khd mod_trigger_timeout 0.2
    lctrl    :   khd -p "0x35"
  '';
}
```
