### ISSUE TITLE
Can't use nixFlakes & unknown setting 'experimental-features'

### ISSUE THREAD

**Issue by ihsanturk** [LnL7/nix-darwin#240]
I can't use nixFlakes as `nix.package` it didn't recognized and still the old version remains.

```sh
❯ nix --version
nix (Nix) 2.3.7
```

darwin-configuration.nix
```nix
{ config, lib, pkgs, ... }:
{
# ...
	nix.package = pkgs.nixFlakes; # NOTE: EXPERIMENTAL.
	nix.extraOptions = lib.optionalString (config.nix.package == pkgs.nixFlakes)
		"experimental-features = nix-command flakes";
#...
}
```

```sh
~
❯ darwin-rebuild switch
building the system configuration...
user defaults...
setting up user launchd services...
Password:
setting up ~/Applications...
applying patches...
setting up /etc...
system defaults...
setting up launchd services...
configuring networking...
configuring fonts...

~ took 5s
❯ nix --version
nix (Nix) 2.3.7

~
❯ nix develop
error: 'develop' is not a recognised command
Try 'nix --help' for more information.

~
❯ nix-channel --update
warning: unknown setting 'experimental-features'
warning: unknown setting 'experimental-features'
warning: unknown setting 'experimental-features'
unpacking channels...
warning: unknown setting 'experimental-features'
```

**Comment by onsails** [comment]
I had the same issue and I believe I've fixed it by installing `nixUnstable` via nix-env.

**Comment by LnL7** [comment]
Yeah that's what it looks like. You can run `nix doctor` which will show you a warning about it if that's the case.

**Comment by ihsanturk** [comment]
`nix doctor` outputs that I have two multiple versions of nix:
```
❯ nix doctor
warning: unknown setting 'experimental-features'
Store uri: local

Warning: multiple versions of nix found in PATH.

  /nix/store/5ira7xgs92inqz1x8l0n1wci4r79hnd0-nix-2.3.7/bin
  /nix/store/brjmcgkcgcsp66nxqgiw0vdjziq6qns3-nix-3.0pre20201020_e0ca98c/bin
```

**Comment by ihsanturk** [comment]
When I try `nix-env -iA nixUnstable` it gives me:
```
❯ nix-env -iA nixUnstable
warning: unknown setting 'experimental-features'
warning: name collision in input Nix expressions, skipping '/Users/ihsan/.nix-de
fexpr/channels_root/nixpkgs'
error: attribute 'nixUnstable' in selection path 'nixUnstable' not found
```

**Comment by onsails** [comment]
try `nix-env -f '<nixpkgs>' -iA hello` or `nix-env -f '<nixpkgs-unstable>' -iA hello` (depending on your `nix-channels --list`). I recommend installing nixUnstable from either 20.09 or nixpkgs-unstable. 20.03 has somewhat incomplete nixUnstable for flakes.

**Comment by ihsanturk** [comment]
Thanks so much! `nix-env -f '<nixpkgs>' -iA nixUnstable` worked for me. Warnings are also gone.

Additionally, is there a way to configure the system to install nixUnstable **declaratively** instead of nix-env?

**Comment by ihsanturk** [comment]
Should I delete the one in the nix profile? How so? Using `nix-env -e nix`?

**Comment by LnL7** [comment]
Yep it should be fine to get rid of the one in your user profile. FYI worst case you can always rollback since this is nix it didn't actually delete anything yet 😄.

```
$ readlink ~/.nix-profile
/nix/var/nix/profiles/per-user/lnl/profile
$ /nix/var/nix/profiles/per-user/lnl/profile-159-link/bin/nix-env --rollback
```

**Comment by ztlevi** [comment]
@LnL7 I got same issue on my system. But I couldn't uninstall the old nix version.

I install the nixUnstable with 
```
nix-env -f https://github.com/nixos/nixpkgs/archive/nixpkgs-20.09-darwin.tar.gz -iA nixUnstable
```
Then in my system
```
✖ nix --version
nix (Nix) 2.4pre20201201_5a6ddb3

➜ nix doctor
Running checks against store uri: local
[FAIL] Multiple versions of nix found in PATH:
  /nix/store/9y161f77hvdss5gaymz2vhmcxcbmj0a8-nix-2.4pre20201201_5a6ddb3/bin
  /nix/store/kzarisi0v8dd1khv17khwhajs3z25pqc-nix-2.3.9/bin

[PASS] All profiles are gcroots.
[PASS] Client protocol matches store protocol.
```

But when I try to uninstall nix 2.3.9 with `nix-env -e nix`, it will remove 2.4pre version. How can I uninstall 2.3.9 version?

It keeps popping :(
```
➜ darwin-rebuild switch --flake ~/.config/dotfiles
error: unrecognised flag '--experimental-features'
Try 'nix --help' for more information.
```

**Comment by nathanshelly** [comment]
@ztlevi have you tried [restarting the `nix-daemon`](https://zimbatm.com/NixFlakes/#other-systems)? I think that has resolved the same error message for me in the past. To restart it you just have to kill the currently running daemon and it will restart itself automatically:

```console
# kill the currently running daemon, will restart automatically
# sudo is needed here because `nix-daemon` runs as `root` on multi-user installs
> sudo pkill nix-daemon
# to view the current `nix-daemon` process 
> ps aux | grep nix-daemon
```

On uninstalling the old `nix` version I also have no idea how to do that 😅 hopefully LnL7 can enlighten us 😄

**Comment by ztlevi** [comment]
@nathanshelly I installed without daemon... `sh <(curl -L https://nixos.org/nix/install) --no-daemon`

**Comment by nathanshelly** [comment]
Ah whoops nvm on restarting the daemon. Hmm what does your `~/.config/nix/nix.conf` file look like?

**Comment by ztlevi** [comment]
@nathanshelly I don't have such file. I believe `darwin-rebuild` will use `nix` and passing `experimental-features` to as args. I also tried put `experimental-features = nix-command flakes` in `~/.config/nix/nix.conf`, still not working..

**Comment by LnL7** [comment]
@ztlevi User profiles are completely separate from nix-darwin, as the doctor command points out you end up with multiple versions of nix in that case. One from the system and one from your user. Building your system with darwin-rebuild will ensure it's internally consistent and only uses the version of nix defined by the system, regardless of whatever might be installed locally for your user.

So either configure `nix.package` properly like the example does. https://github.com/LnL7/nix-darwin/blob/2a60ef1956ed7d000d3941d720e17a25450c6923/modules/examples/flake.nix#L13 Note that this will still get shadowed for your user shell so unless you just want to use flakes within nix-darwin it's probably best removing the duplicate to keep the versions consistent.

Alternatively if you really want to update nix with nix-env separately it's possible to point `nix.package` to a profile instead of managing it directly, which would also resolve the duplicate but means that part isn't managed declaratively anymore.

**Comment by ztlevi** [comment]
@LnL7 Yeah, adding ` nix.package = pkgs.nixFlakes; ` this to my config doesn't solve the problem. My guess is darwin-rebuild still triggers the default system's nix rather the user's.

But how can I remove the system's or upgrade the system's nix.

I tried 
1. `sudo nix-channel --update` followed with `nix-env -u '*'`, still give me 2.3.9 nix.
2. removing nix with `nix-env -e nix`
```
~
➜ nix-env -e nix

~
➜ nix --version
nix (Nix) 2.3.9
```
Still 2.3.9.

**Comment by LnL7** [comment]
What I explained above exactly implies that the user's nix won't ever be used.

```
$ head $(command -v darwin-rebuild)
#! /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bash-4.4-p23/bin/bash
set -e
set -o pipefail
export PATH=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-nix-3.0/bin:/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-coreutils-8.31/bin:...
```

Note however that `darwin-rebuild` comes from your current system by default however. So if the current configuration doesn't use nixUnstable then that won't be able to build it and you'll need to bootstrap things using the commands from the flake system, similar to an initial install or restoring after a system upgrade.

```sh
nix build ".#darwinConfigurations.Johns-MacBook.system"
./result/sw/bin/darwin-rebuild switch --flake .
```

**Comment by ztlevi** [comment]
@LnL7 Thanks. This one works. But I encountered some build issue after a successful build.

I didn't change anything. But after restart a terminal, it failed to build. Doing `nix-store --verify --repair` suggested [here](https://github.com/NixOS/nix/issues/2244) didn't solve the issue. I tried remove `/nix` and build again, it's able to build but failed again after I start a new terminal.

```
dotfiles on  master [$+] took 2s
➜ ./result/sw/bin/darwin-rebuild switch --flake $HOME/.config/dotfiles#shiro

warning: Git tree '/Users/ztlevi/.config/dotfiles' is dirty
building the system configuration...
warning: Git tree '/Users/ztlevi/.config/dotfiles' is dirty
error: --- Error ------------------------------------------------------------------- nix
getting attributes of path '/usr/lib/libSystem.B.dylib: No such file or directory
(use '--show-trace' to show detailed location information)

dotfiles on  master [$+] took 3s
✖ nix --experimental-features 'flakes nix-command' build $HOME/.config/dotfiles#darwinConfigurations.shiro.system

warning: Git tree '/Users/ztlevi/.config/dotfiles' is dirty
error: --- Error ------------------------------------------------------------------- nix
getting attributes of path '/usr/lib/libSystem.B.dylib: No such file or directory
(use '--show-trace' to show detailed location information)

✖ nix doctor
Running checks against store uri: local
[FAIL] Multiple versions of nix found in PATH:
  /nix/store/9y161f77hvdss5gaymz2vhmcxcbmj0a8-nix-2.4pre20201201_5a6ddb3/bin
  /nix/store/j2s81abrzrcs105g84hilgir55n9pz9g-nix-2.4pre20201201_5a6ddb3/bin

[PASS] All profiles are gcroots.
[PASS] Client protocol matches store protocol.
```

**Comment by LnL7** [comment]
That is a macOS 11.0 Big Sur specific problem, but it's not clear to me if that's coming from a build or nix itself.

**Comment by ztlevi** [comment]
Thanks too bad.... I'll follow up in nix channel. Thanks for the great help!

**Comment by LnL7** [comment]
FYI these kinds of issues are usually easier to resolve on IRC or something else more interactive.

**Comment by ztlevi** [comment]
@LnL7 Hi, I'm still having this `/usr/lib/libSystem.B.dylib: No such file or directory` error. Would you mind to help me to do a live debugging? We can do it on Discord

**Comment by takuma-ynd** [comment]
@ztlevi Would you tell me if you could solve `/usr/lib/libSystem.B.dylib: No such file or directory` issue?
I'm having the same error when I just run `darwin-rebuild switch`.

**Comment by ztlevi** [comment]
No... LnL7 suggested a live debugging. I would like to do such thing. I pinged him in Discord as well but didn't get any feedback...

**Comment by takuma-ynd** [comment]
I see. I created a new issue specifically for this.
#349
