### ISSUE TITLE
Setting `nix.package` doesn't affect which nix executable is used

### ISSUE THREAD

**Issue by happysalada** [LnL7/nix-darwin#246]
using `    package = pkgs.nixFlakes;`
doesn't change which version of nix is used.

Perhaps this has to with the explanation
```
To keep the version of nix originally installed the default profile can be used.

eg. /nix/var/nix/profiles/default 
```

Does this mean that if the default profile is used, setting this variable has no effect?

What do I need to do to enable flakes?

(I also tried to add the 
`extraOptions = "experimental-features = nix-command flakes";`
but that didn't work either)

**Comment by ihsanturk** [comment]
See: #240

**Comment by happysalada** [comment]
@LnL7 When you have sometime. Can this paragraph be added to the documentation. I believe, we should be able to close the issue afterwards. Sorry for soliciting you, if I could add to the wiki, I would do it.

# Changing/upgrading nix

In order to upgrade nix, you first need to install the new version you are looking to use.
example: `nix-env -f '<nixpkgs-unstable>' -iA nixUnstable`

Then you need to remove the current nix package (this operation is reversible)
`nix-env -e nix`

Then finally editing your `darwin-configuration.nix` file and rebuilding your system (with `darwin-rebuild switch`) you will get the new nix version. You can check with `nix --version`
