### ISSUE TITLE
Yabai scripting addition needs update for MacOS 11.0

### ISSUE THREAD

**Issue by sullvn** [LnL7/nix-darwin#256]
nix-darwin's Yabai support needs an update for MacOS Big Sur. [The scripting addition now requires passwordless sudo to work.](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup)

Broken nix-darwin config [(source link)](https://github.com/LnL7/nix-darwin/blob/600bd4f9eda14fd1cd59fad45044aaa0b47022a3/modules/services/yabai/default.nix#L33):

```
services.yabai.enableScriptingAddition = true;
```

It's broken because `yabai --load-sa` now requires a passwordless `sudo`. [The current nix-darwin config without sudo:](https://github.com/LnL7/nix-darwin/blob/600bd4f9eda14fd1cd59fad45044aaa0b47022a3/modules/services/yabai/default.nix#L94)

```
      launchd.daemons.yabai-sa = {
        script = ''
          if [ ! $(${cfg.package}/bin/yabai --check-sa) ]; then
            ${cfg.package}/bin/yabai --install-sa
          fi
        '';
```

[Yabai recommends adding a sudoer's file.](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup) I've used nix-darwin for this as so:

```
# Change `<user>` to your username.
#
# Required afterwards:
#
#     sudo chown root:wheel /etc/static/sudoers.d/yabai
#
# WARNING: The trailing newline is super important. Otherwise it won't parse
# correctly and sudo will refuse to work.
#
environment.etc.yabai = {
  target = "sudoers.d/yabai";
  text = "<user> ALL = (root) NOPASSWD: ${pkgs.yabai}/bin/yabai --load-sa
  ";
};
```

I would make a PR for this, but I don't know how to solve the following in nix and nix-darwin:

* Automatically replace `<user>` in sudoers file with username
* Automatically adjust permissions on sudoers file to be `root:wheel`

**Comment by LnL7** [comment]
Fixed in https://github.com/LnL7/nix-darwin/pull/261.
