### ISSUE TITLE
“attempt to write a readonly database”

### ISSUE THREAD

**Issue by sellout** [LnL7/nix-darwin#29]
Running `darwin-rebuild switch` after updating this morning, I got this error.
```
writing defaults...
setting up user launchd services...
setting up accessibility programs...
Error: attempt to write a readonly database
```

**Comment by LnL7** [comment]
What version of OS X are you using?

**Comment by sellout** [comment]
10.12.4

I’m happy to update to 10.12.5 if that’s a known fix, but will keep .4 for now, in case it’s important for diagnosis.

**Comment by LnL7** [comment]
I doubt that's the issue, what are the permissions of `/Library/Application Support/com.apple.TCC/TCC.db`?

**Comment by sellout** [comment]
```
> sudo ls -l '/Library/Application Support/com.apple.TCC/'
-rw-r--r--  1 root  wheel  65536 May 23 08:39 TCC.db
```

**Comment by sellout** [comment]
So, is it possible that the sql commands just aren’t being run via sudo?

**Comment by LnL7** [comment]
I was thinking that, but it has the same permissions for me and the activation scripts [run with sudo](https://github.com/LnL7/nix-darwin/blob/master/pkgs/nix-tools/darwin-rebuild.sh#L125) except for user activation which only configures defaults and user services.

I have seen a database locked once so the module doesn't seem all that stable, I'll add an option to explicitly enable it.

**Comment by LnL7** [comment]
https://github.com/LnL7/nix-darwin/commit/fa843a70ca5760bfcb45b22e100e190a595055ef

**Comment by sellout** [comment]
Thanks, that seems to have fixed it! (And that change seems good, but I guess the consequence is that you either give accessibility access to all apps that want it or none.)

**Comment by LnL7** [comment]
Probably makes more sense, the dialog boxes are pretty annoying. 😄
