### ISSUE TITLE
question: Append to `/etc/shells` as opposed to overwriting it

### ISSUE THREAD

**Issue by bphenriques** [LnL7/nix-darwin#293]
Hello 👋 

I am attempting to set the nix package `zsh` as my default shell, however the activation fails as the `/etc/shells` already exists which is an expected error. However, I am not comfortable deleting the file 🤔 

Would it make sense to append the shell to the file if it is not present as part as opposed to "overwriting" it and appending additional ones ([ref](https://github.com/LnL7/nix-darwin/blob/6c6eb8ace6599a33eeb33e28453a601ab02e523e/modules/system/shells.nix#L25))?

Edit: I am aware that in addition to append if not present, it also needs to remove shells that were present in previous generation and aren't in the new one 🤯 
Edit2: Tested deleting `/etc/shells` on a laptop I had around and no issues occurred (_uff_). Notwithstanding, I wonder how this process can be more seamless to the user and avoid "destroying" files created by the system which is important when unnistalling nix.

**Comment by jakzale** [comment]
What you probably wanted was to move the `/etc/shells` out of the way:
```bash
sudo mv /etc/shells /etc/shells.orig
```

This way you will always have a backup.

**Comment by bphenriques** [comment]
Thank you! I am aware of (and using) that alternative, however having that set out-of-the-box provides a smoother experience.

**Comment by Enzime** [comment]
Closing this as nix-darwin should handle this automatically as of #837
