### ISSUE TITLE
Add programs.fish module

### ISSUE THREAD

**Issue by yurrriq** [LnL7/nix-darwin#3]
I'm making a separate issue for this.

I've done some hacking locally (and trashed my `/nix/store/` several times) and have a broken implementation I can push to my fork tomorrow or Wednesday.

The main issues are with `/`s in the etc config (see `nixpkgs/nixos/modules/programs/fish.nix`) and by extension the `foreign-env/` config. I'm guessing/hoping you can get it sorted once I push. :smile:

**Comment by LnL7** [comment]
Ah, I just noticed the issue with etc files myself. I'll push my fix soon.

**Comment by LnL7** [comment]
This https://github.com/LnL7/nix-darwin/commit/9081af7f422c6ebe8a2ddbc301ff638bb73a9337 should fix etc files with directories.

**Comment by yurrriq** [comment]
Great, thanks! I'll give it a go. I see I never pushed my WIP `fish.nix`... I'll be sure to do that today too.

I think with the `/` bit solved, the foreign-env part will follow.

**Comment by LnL7** [comment]
Also, do you know what went wrong that caused the issues with your store? Perhaps there's something I can do to make the activation scripts a bit safer so it fails instead.

**Comment by yurrriq** [comment]
I set `zsh.enable = false` and `fish.enable = true` and starting getting errors about Nix not being compiled with libsodium (false, afaik) and thus not being able to download signed binary caches. I was unable to build anything at that point, and just trashed my `/nix/store/` and reinstalled Nix. Since everything is reproducible and I've got a pretty fast connection, I was up and runnning in <10min.

**Comment by yurrriq** [comment]
My broken `programs.fish` module didn't set the right env vars and such. I probably could have solved it by setting ten manually, but after trying briefly, it seemed easier just to start over with a clean slate.

**Comment by yurrriq** [comment]
I've rebased on 9081af7 and pushed [`fish.nix`](https://github.com/yurrriq/nix-darwin/blob/feature/fish/modules/programs/fish.nix). I'm going to test it now.

**Comment by yurrriq** [comment]
Getting this error:

```
error: The option `environment.etc.fish/foreign-env/interactiveShellInit.source' is used but not defined.
```

**Comment by yurrriq** [comment]
I'm getting these errors again..

```
building the system configuration...
download-from-binary-cache.pl: Nix was not compiled with libsodium, required for signed binary cache support at /nix/store/7v21yd3qpv0nclcy5cqr5njj9bril12s-nix-1.11.4/lib/perl5/site_perl/5.22.2/darwin-2level/Nix/Manifest.pm line 479, <STDIN> line 3.
error: substituter ‘download-from-binary-cache.pl’ died unexpectedly
```

**Comment by yurrriq** [comment]
The following [advice from the NixOS manual](https://nixos.org/nixos/manual/index.html#sec-nix-network-issues) works for now:

```fish
darwin-rebuild build --option use-binary-caches false
```


Sounds like maybe I'm having trouble reaching https://cache.nixos.org/

**Comment by LnL7** [comment]
Ok, the issue here is the fact that you give it an empty string unless config.environment.interactiveShellInit is defined.

```
environment.etc."fish/foreign-env/interactiveShellInit".text = cfge.interactiveShellInit;
```

**Comment by LnL7** [comment]
But I can provide a proper error message.

```
building the system configuration...
error: evaluation aborted with the following error message: ‘environment.etc.fish/foreign-env/interactiveShellInit.text is empty but no source was defined.’
(use ‘--show-trace’ to show detailed location information)
```

**Comment by yurrriq** [comment]
So if I set a value in my `darwin-configuration.nix` this should be fine? Is there a better approach from the `programs.fish` side?

**Comment by LnL7** [comment]
use `mkIf` to only define the file when it has contents.

**Comment by yurrriq** [comment]
Hmm. I couldn't quite figure out the syntax there, but using dummy text (fish comments) I got it to build. It seems the environment is not getting set up correctly still.

**Comment by LnL7** [comment]
This should work, 

```
environment.etc."fish/foreign-env/interactiveShellInit".text = mkIf (interactiveShellInit != "")
  { text = interactiveShellInit; };
```

The config.fish script also has handle that case properly, I assume it will just continue if the file doesn't exist, otherwise it also has to be handled there.

```
{optionalString (interactiveShellInit != "") ''
  fenv source ${config.environment.etc."fish/foreign-env/interactiveShellInit".source} > /dev/null
''}
```

**Comment by LnL7** [comment]
I just realised that overriding the source works fine with just `mkDefault`, not sure why I had that [check](https://github.com/LnL7/nix-darwin/commit/fc2bc4e05b8eacbdf2fcc38ef8092eaedb666393) in the first place.

**Comment by yurrriq** [comment]
The `mkIf` suggestion didn't work, but [this did](https://github.com/yurrriq/nix-darwin/commit/ea89102d35a278b620570c2f2bdc504ada9454bc). Thoughts?

**Comment by yurrriq** [comment]
By the way, after [these changes](https://github.com/yurrriq/nix-darwin/compare/63ac760ef5b023cd2af29e44b31abb8342db7803...a13600b36abde55fdca64c76a4a383a97c20d373) I'm now able to set

```nix
programs.fish.enable = true;
```

without breaking everything.

**Comment by LnL7** [comment]
I think I didn't define all the environment options yet, that might be why you're seeing issues.
