### ISSUE TITLE
libSystem.B.dylib: no such file or directory

### ISSUE THREAD

**Issue by nrdxp** [LnL7/nix-darwin#302]
I'm brand new to OSX. Actually just experimenting with a Big Sur VM. After some searching, I've discovered that Apple made the decision to remove some libraries from the system in Big Sur, moving them to a linker cache instead. If that were all, I wouldn't be opening this issue.

My confusion comes in because, while trying to port some of my NixOS configs to nix-darwin, I suddenly got this error when trying to build a flake based nix-darwin system. The interesting bit is that, just moments before, I was able to build and deploy a nix-darwin configuration.

I thought it was because of some changes I made, so I reverted them and tried to rebuild the original configuration. No luck, same error. Rebooted, still same error. I'm not sure if maybe the system updated or something happened in those few minutes between builds, but I thought I'd ask if anyone has experienced and/or fixed this issue. 

I was considering [extracting](https://lapcatsoftware.com/articles/bigsur.html) the system libs manually, and putting them back in place, but atm at least, some of apples subdomains are down, preventing me from doing so.

**Comment by jokogr** [comment]
I am on Big Sur, too, on a MacBook Pro Late 2013, and I was getting such errors when I was using a sandbox. 

@nrdxp Could you check if sandbox is enabled and if so, check if the same error appears when sandboxing is disabled?

**Comment by nrdxp** [comment]
@jokogr, it seems that the sandbox is the culprit on this, as running `nix build --no-sandbox` fixed the issue. Although sandboxing is a pretty important feature, so perhaps we should leave this open.

**Comment by emilazy** [comment]
Linking this to https://github.com/NixOS/nix/issues/4658.

**Comment by rpearce** [comment]
@nrdxp's `nix build --no-sandbox` solution helped me get around it. Thanks!

**Comment by nrdxp** [comment]
should be fixed by NixOS/nix#4761
