### ISSUE TITLE
brew: could use option to pass `--no-upgrade`

### ISSUE THREAD

**Issue by emilazy** [LnL7/nix-darwin#324]
Currently, `brew.autoUpdate` defaults to `false`, but this controls only `HOMEBREW_NO_AUTO_UPDATE`, which I believe is separate to the up*grading* of packages, casks, and App Store apps managed by `brew bundle`. Of course, if you don’t update the package repositories, you’d ordinarily expect there to not be any updates to potentially install, but as `brew bundle` can also interface with `mas` for the Mac App Store, activating a configuration can currently cause unreproducible automatic updates even with the `autoUpdate` option turned off.

I’m not sure whether the best solution would be to make `autoUpdate` also control `--no-upgrade`, or to add another option specifically for that. If you don’t want the package manager and package repositories to update, I’d guess you don’t want other things to update themselves automatically on activation either.

**Comment by emilazy** [comment]
This is especially relevant in light of the issues causing `mas` to unnecessarily reinstall packages that don’t need upgrading, which has [recently been fixed upstream](https://github.com/mas-cli/mas/pull/346#event-4648375488) but not yet seen a release.

One possible solution would be to explicitly tell `brew` not to manage `mas` apps and use something like https://github.com/LnL7/nix-darwin/pull/229 instead, but I think it’d be good to handle this case anyway.

**Comment by malob** [comment]
@emilazy, I just went to implement this since I've been annoyed my the `mas` issue you mentioned, but the `--no-upgrade` flag doesn't seem to change `mas`'s behavior. I checked the `brew bundle` docs, and it looks like the `--no-upgrade` flag just makes is so that `brew upgrade` isn't run, and so wouldn't have any effect on the `mas` integration :(

**Comment by malob** [comment]
@emilazy, is this issue still relevant given my response?

**Comment by emilazy** [comment]
Sorry for leaving this issue hanging for so long!

The underlying `mas` issue was fixed so this is no longer as pressing a problem. However, I think that activating a configuration should be as idempotent as possible, so upgrading packages should at least be opt-out (I generally think it should be opt-in because of that). The interaction with `mas` is unfortunate but it'd still be an improvement over the status quo for people who don't manage App Store apps with the `brew` module. I'm not sure it makes sense to opt to not have the package index updated but still upgrade packages if the index *has* been updated, especially since `brew` updates the index itself quite aggressively.

That said, `brew` itself doesn't really like to support any kind of version pinning, and absent a Nix-native mechanism to e.g. control the commit of the various Homebrew repositories it would mean explicitly running `brew upgrade` separately to the nix-darwin configuration. But I still think reactivating the same configuration causing package upgrades is a misfeature that should be avoided where possible. `--no-upgrade` not applying to App Store apps feels like a bug that should probably be filed with Homebrew upstream rather than a reason to not handle this in nix-darwin.

**Comment by malob** [comment]
@emilazy, I've made changes to address this in the linked PR above.
