### ISSUE TITLE
`darwin-rebuild --help` runs `man darwin-rebuild` but no such manpage exists

### ISSUE THREAD

**Issue by lilyball** [LnL7/nix-darwin#327]
When I run `darwin-rebuild --help` it prints an option summary followed by running `man darwin-rebuild`. However, no such manpage exists. This doesn't appear to be a misconfiguration, I don't see any evidence of a `darwin-rebuild` manpage in the nix-darwin source.

**Comment by lilyball** [comment]
This issue was about the lack of a manpage, I don't understand why it was closed by a PR adding a `darwin-version` command.

**Comment by emilazy** [comment]
The `man` execution was removed from `darwin-rebuild`: https://github.com/LnL7/nix-darwin/pull/733/files#diff-88ec1ae379b05d4ec182ba6ac53e32cb7175df3557266492f19200c3ef1a5d09

I think we should ideally have manual pages regardless, but this specific bug no longer happens.

**Comment by lilyball** [comment]
Ah hah, I missed that line. Thanks!
