### ISSUE TITLE
Unable to interact with the system clipboard from terminal Vim

### ISSUE THREAD

**Issue by gj** [LnL7/nix-darwin#331]
Tested in iTerm 3.4.6 and Terminal.app 2.10 (433).

Minimal `~/.nixpkgs/darwin-configuration.nix`:

```nix
{ config, pkgs, ... }:

{
  environment.systemPackages = [ config.programs.vim.package ];

  services.nix-daemon.enable = true;

  programs.zsh.enable = true;

  programs.vim.package = pkgs.vim_configurable.override {
    python = pkgs.python3;
  };

  system.stateVersion = 4;
}
```

Steps to reproduce:

1. Open Vim.
2. Verify that the `+` register is empty: `:reg +`
3. Verify that the `*` register is empty: `:reg *`
4. Enter insert mode, type some text, return to visual mode, and try selecting and yanking the selection into the `+` or `*` register.

I've verified that Vim is compiled with the `+clipboard` and `+xterm_clipboard` features.

I have a feeling this is due to the Nix-managed Vim being isolated in Nixworld & interacting with the system clipboard in that isolated environment instead of the system clipboard in macOSWorld, but I'm not sure how to test that hypothesis.

Thanks for your hard work on this excellent tool @LnL7 !

**Comment by eraserhd** [comment]
I've had this when running under tmux or screen, and in that case I use `reattach-to-user-namespace` (which can be found in nixpkgs) as the shell to solve the problem.

**Comment by eraserhd** [comment]
I tried the pinned versions of vim and neovim from https://github.com/eraserhd/parinfer-rust's `shell.nix` (nixpkgs 20.09), and I'm able to paste the system buffer with both `"+p` and `"*p` without using `reattach-to-user-namespace`, inside Kitty.

**Comment by gj** [comment]
Thanks for the sanity check @eraserhd!

Your Nix config helped me figure out the issue: the `vim_configurable` package I was using comes with a ton of extra options enabled, including `+X11` and `+xterm_clipboard`. The `vim` and `vim-darwin` packages both do the trick for me, though the latter is compiled with `+python3`, `+ruby`, `+lua`, and a few other niceties.

Sorry for the noise!
