### ISSUE TITLE
Relative `private/var/run` path

### ISSUE THREAD

**Issue by kidonng** [LnL7/nix-darwin#336]
I noticed there are some code and instructions using relative `private/var/run` instead of the full `/private/var/run`, the most conspicuous example being the first command under the "Manual Install" section of the README: `sudo ln -s private/var/run /run`. From what I can tell, this won't work unless the user is at `/` or `/System/Volumes/Data`. Is this a mistake or intended?

Also, pardon me for being dumb here, how is the `$PWD` set so the code can run correctly?

**Comment by LnL7** [comment]
Symlinks can be relative, what a relative symlink points to depends on it's location not your working directory. So in this case it's equivalent, If you take a look at the root layout on macOS you'll see that builtin symlinks are created the same way.

```
lrwxr-xr-x   1 root admin   11 Dec  5  2019 etc -> private/etc
lrwxr-xr-x   1 root admin   11 Dec  5  2019 tmp -> private/tmp
lrwxr-xr-x   1 root admin   11 Dec  5  2019 var -> private/var
```

**Comment by kidonng** [comment]
Ohh you are right, I was being dumb and thinking about the relative links will be resolved to absolute path.

Still, I think the `sudo ln -s private/var/run /run` command will fail after 10.15, right? I think a note in the README is still beneficial.

**Comment by LnL7** [comment]
Ah indeed, the installer has been updated to handle this but the manual install section doesn't mention any of the new needed steps.
