### ISSUE TITLE
Fresh install of Nix 2.3.15 produced nix.conf file that nix-darwin doesn't know about

### ISSUE THREAD

**Issue by lilyball** [LnL7/nix-darwin#347]
A fresh multi-user install of Nix 2.3.15 on macOS produced a `nix.conf` file that looks like

```

build-users-group = nixbld
```

(note the blank line at the start)

nix-darwin doesn't recognize this and therefore won't replace it.

**Comment by rpearce** [comment]
Yep. I had to just remove this file on a brand new 14" M1 MacBook Pro for it to then link the right file.

**Comment by Enzime** [comment]
Fixed by #687
