### ISSUE TITLE
What does loginShell do?

### ISSUE THREAD

**Issue by pecigonzalo** [LnL7/nix-darwin#361]
Inspecting the code, I could not find what `loginShell` is used for except for `tmux`. For context, I'm trying to make macOS load the nix-darwin `zsh` instead of the system one, with an existing user (not created through nix-darwin).

I have tried:

```
  programs.zsh = {
    enable = true;
  };
  environment.variables = {
    SHELL = "${pkgs.zsh}/bin/zsh";
  };
  environment.loginShell = "${pkgs.zsh}/bin/zsh -l";
```

The only way to make it work is to either `chsh` or something like whats done in `dscl . -create '/Users/${v.name}' UserShell '${v.shell}'`.
I think it would be great if https://github.com/LnL7/nix-darwin/blob/master/modules/users/default.nix#L152-L168 did set the shell even if the user already exists.

**Comment by PhotonQuantum** [comment]
Any update to this? I assumed this option would do something like `chsh` for me which is incorrect. This is quite misleading.

**Comment by bestlem** [comment]
Also see #328 

The documentation is extremely misleading,
