### ISSUE TITLE
config.nixpkgs.overlays incorrectly disallows functors

### ISSUE THREAD

**Issue by lilyball** [LnL7/nix-darwin#374]
nixpkgs doesn't seem to care if an overlay is a function or a functor. But nix-darwin declares `config.nixpkgs.overlays` such that it uses `builtins.isFunction` instead of `lib.isFunction`. The latter supports functors while the former does not.

**Comment by emilazy** [comment]
Seems to have been fixed by https://github.com/LnL7/nix-darwin/pull/394.
