### ISSUE TITLE
Default $TERMINFO to "${pkgs.ncurses}/share/terminfo"?

### ISSUE THREAD

**Issue by jsoo1** [LnL7/nix-darwin#383]
I found I was missing some reasonable terminfo data when using nix-darwin. I think it might be reasonable to add TERMINFO to the default environment.variables option, what do you think?

Edit: nixpkgs does it differently than I was suggesting: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/terminfo.nix, but still does set TERMINFO_DIRS

**Comment by emilazy** [comment]
Should be solved in another way by https://github.com/LnL7/nix-darwin/pull/533.
