### ISSUE TITLE
Uninstaller does not restore linked files under `/etc`

### ISSUE THREAD

**Issue by kidonng** [LnL7/nix-darwin#390]
`/etc/bashrc` is moved to `/etc/bashrc.orig` during installation, but not restored during uninstallation.

If one uses `environment.shells` and decided to remove `/etc/shells` manually in order for nix-darwin to link a new one (since it won't overwrite existing one), the file are not restored during installation either, so that's probably out of scope.

**Comment by Enzime** [comment]
I'm closing this in favour of #338, as the uninstaller sets `environment.etc = mkForce {};` meaning that if #338 is fixed, this issue should be fixed as well.
