### ISSUE TITLE
No /etc/static/zsh*

### ISSUE THREAD

**Issue by willruggiano** [LnL7/nix-darwin#393]
There aren't any zsh files in /etc/static after running the nix-darwin installer. Bash seems to be set up correctly. This manifests in improperly initialized shell environments, such as when I `open -na kitty` using a keybind in skhd.

For example:
Opening a kitty terminal after opening iTerm using Spotlight:
```
$ which fd
/etc/profiles/per-user/<me>/bin/fd
```

But if I open a terminal using an skhd keybind:
```
$ which fd
fd not found
```

I'm not sure if this is nix-darwin specific or something environmental specific to my nix configuration. Also, I can't find a way to "fix" the situation in the latter (launching a terminal through an skhd keybind) case, e.g. I can't find a file to source which makes these missing commands usable.

**Comment by willruggiano** [comment]
I should add that I am configuring zsh using home-manager.

**Comment by willruggiano** [comment]
The /etc/static files are put in place by the installer, which is long before any home manager configuration is built. But also yes, I have zsh enabled via hm. I use the same configuration on a nixos host and everything works fine.

**Comment by domenkozar** [comment]
Then the installer needs that line to prepare the zsh static files.
