### ISSUE TITLE
Add programs.emacs module

### ISSUE THREAD

**Issue by yurrriq** [LnL7/nix-darwin#4]
I've got a partially functioning version locally, but it's still very much in flux.

**Comment by LnL7** [comment]
One important thing about the program modules is that they [should be generic](https://github.com/LnL7/nix-darwin/blob/master/modules/programs/tmux.nix#L114-L118).
These are more focused on user configuration then what's currently in nixos, some of these might be added there or I might move them to a separate project that can be used on linux and darwin at some point.

**Comment by yurrriq** [comment]
:+1: My WIP conflates a bunch of config specific to me at the moment. I'll follow `tmux.nix` et al. as I make it generic.

**Comment by matthewbauer** [comment]
:+1: It would be great to get an Emacs daemon service working as well!

**Comment by yurrriq** [comment]
We have `services.emacs` now.
