### ISSUE TITLE
`sudo nix-channel --update` only leads to restart of the graphical system

### ISSUE THREAD

**Issue by loskutov** [LnL7/nix-darwin#40]
After the restart, I'm unable to use `darwin-rebuild`:
```
% darwin-rebuild build
building the system configuration...
warning: Nix search path entry ‘/nix/var/nix/profiles/per-user/root/channels’ does not exist, ignoring
error: file ‘darwin’ was not found in the Nix search path (add it using $NIX_PATH or -I)
```
After fixing it manually, it starts to `build` but not `switch`:
```
% export NIX_PATH=darwin=$HOME/.nix-defexpr/darwin:darwin-config=$HOME/.nixpkgs/darwin-configuration.nix:nixpkgs=$HOME/.nix-defexpr/channels/nixpkgs:$HOME/.nix-defexpr/channels
% darwin-rebuild switch
building the system configuration...
warning: Nix search path entry ‘/nix/var/nix/profiles/per-user/root/channels’ does not exist, ignoring
error: file ‘darwin’ was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:1
error: Changed <darwin> but target does not exist, aborting activation
Add the darwin repo as a channel or set nix.nixPath:
$ sudo nix-channel --add https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin
$ sudo nix-channel --update

or set

    nix.nixPath = [ "darwin=/Users/ignat/.nix-defexpr/darwin" ];

```
If I follow the advice, the graphical systems restarts once again with no noticeable effect.

Before 1d0ecb8914fa91d1dd68651b71894c0f3842ae80 it used to work. What can I do now to get it working back?

**Comment by LnL7** [comment]
Could you clarify what the problem is, re you still running into after following the instructions?

**Comment by loskutov** [comment]
Yes, by "no noticeable effect" I mean I still get `error: file ‘darwin’ was not found in the Nix search path`. As a temporary workaround, I've switched to 6d91e5b565f89507089fdc5de6d5e3c8336950d9 which works like a charm.

**Comment by LnL7** [comment]
And `darwin-option nix.nixPath` includes the extry for darwin you added?
This should be exactly the same as the previous behaviour:

```nix
{ config, options, ... }:
{
  nix.nixPath = [ "darwin=$HOME/.nix-defexpr/darwin" ] ++ options.nix.nixPath.default;
}
```

**Comment by loskutov** [comment]
I also had to specify `nixpkgs`:
```  nix.nixPath = [ "darwin=$HOME/.nix-defexpr/darwin" "nixpkgs=$HOME/.nix-defexpr/channels/nixpkgs" ] ++ options.nix.nixPath.default;
```
After performing that, everything works.

Anyway, is it now required to specify the paths manually? [examples/simple.nix](https://github.com/LnL7/nix-darwin/blob/master/modules/examples/simple.nix) doesn't contain anything like that. Am I doing something wrong?

**Comment by LnL7** [comment]
The defaults should work when you use the bootstrap script, I'm assuming that's what most people will use.

**Comment by spease** [comment]
I'm getting this error after following the instructions in the readme on the front page of the nix-darwin repo. I have to use
```
export NIX_PATH="darwin-config=$HOME/.nixpkgs/darwin-configuration.nix:darwin=$HOME/.nix-defexpr/channels/darwin:nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs:/nix/var/nix/profiles/per-user/root/channels"
```

to be able to darwin-rebuild. I also tried:
```
nix.nixPath = [ "darwin=$HOME/.nix-defexpr/channels/darwin" ] ++ options.nix.nixPath.default;
```

Note that this is different from above - note that I had to add the `channels` subdirectory.

In spite of that, my NIX_PATH is still
```
nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs:/nix/var/nix/profiles/per-user/root/channels
```

**Comment by tshearman** [comment]
I'm having this same issue:

% darwin-rebuild switch                                                                                                                                                     
building the system configuration...
error: file 'darwin' was not found in the Nix search path (add it using $NIX_PATH or -I)

Adjustments to nix.nixPath don't seem to solve the problem
Adjusting /etc/bashrc also doesn't solve the problem

**Comment by spease** [comment]
I think I may have gotten past it by doing nix-channel —update as regular user, then I got another error (I think relating to a symlink), then I ran it with sudo again. However it’s been long enough that I don’t remember exactly; try at your own risk.
