### ISSUE TITLE
`evalModules` now warns when passing `args`

### ISSUE THREAD

**Issue by lilyball** [LnL7/nix-darwin#405]
Nixpkgs now warns when using the `args` (or `check`) parameter to `lib.evalModules` (see https://github.com/NixOS/nixpkgs/pull/148315). nix-darwin is using `args` in `eval-config.nix` and in `modules/documentation/default.nix`. It should avoid this and pass args using `_module.args` instead. The various commits in the aforementioned PR can probably be used as a template for the changes in nix-darwin.

**Comment by lilyball** [comment]
The current effect of this is building my system logs

```
trace: warning: The args argument to evalModules is deprecated. Please set config._module.args instead.
trace: warning: The args argument to evalModules is deprecated. Please set config._module.args instead.
```

and running `darwin-option` logs that same warning as well.

**Comment by jsoo1** [comment]
I found this as well, but it is complicated because of #392 and #397.

**Comment by lilyball** [comment]
Check is deprecated, but it's deprecated in favor of `_module.check` so that can be adapted just as easily as args.
