### ISSUE TITLE
When nix-daemon is configured and an existing nix.conf exists, the configuration is not applied

### ISSUE THREAD

**Issue by jsoo1** [LnL7/nix-darwin#407]
I know the desire for most of /etc in nix-darwin is to leave the original.  But in my mind, I would like to have the nix configuration be taken from the configuration. Perhaps symlinks should have an optional `force` option?

**Comment by LnL7** [comment]
The introduction of the hashes is essentially a force option. An alternative would be to introduce a fixed whitelist or blacklist for files that can be "owned" by the system configuration. Messing with certain files or even just converting them to a symlink without valid content until the nix store volume is mounted can cause problems for the macOS base system. And even if they don't currently there's no guarantee that this might change after an update.

I would really like to avoid supporting things that could result in cases where a user might have to recover through single-user boot, or worse...
