### ISSUE TITLE
Wrong profile used on new install.

### ISSUE THREAD

**Issue by sellout** [LnL7/nix-darwin#41]
I got a new MacBook, so the first thing I did was

open Terminal
> curl https://nixos.org/nix/install | sh

open new Terminal
> bash <(curl https://raw.githubusercontent.com/LnL7/nix-darwin/master/bootstrap.sh)

But bootstrap.sh fails with
```
Copying example configuration to ~/.nixpkgs/darwin-configuration.nix...
cp: /Users/greg/.nix-defexpr/darwin/modules/examples/simple.nix: No such file or directory
```
and this is because [line 141](https://github.com/LnL7/nix-darwin/blob/9f0507cf7d62472650bb3f2d936d0d43ef6009b4/bootstrap.sh#L141) seems to install the channel under “/nix/var/nix/profiles/per-user/greg/channels/darwin” (“greg” instead of “root”), so the symlink created at [line 145](https://github.com/LnL7/nix-darwin/blob/9f0507cf7d62472650bb3f2d936d0d43ef6009b4/bootstrap.sh#L145) is pointing at nothing.

**Comment by LnL7** [comment]
I forgot about the bootstrap script when switching to user channels.
