### ISSUE TITLE
Flake: Run in different working dir for darwin-rebuild switch have different behaviour even path is specified

### ISSUE THREAD

**Issue by soulomoon** [LnL7/nix-darwin#410]
![image](https://user-images.githubusercontent.com/14073857/146916438-586792a6-8000-4d25-954c-3145440b7507.png)

darwin arm 64

I seems to trying to create a tmp file in the working dir, but sometimes it is readonly dir.

**Comment by emilazy** [comment]
Should be fixed by https://github.com/LnL7/nix-darwin/pull/310.
