### ISSUE TITLE
Documentation: switch freenode->libera?

### ISSUE THREAD

**Issue by jsoo1** [LnL7/nix-darwin#415]
The readme mentions freenode.net as the primary irc network for contact. It seems like #nix-darwin on freenode is quite empty. Is the libera #nix-darwin the new place to go?

**Comment by LnL7** [comment]
I'm not sure there are still that many people from the nix community in general on irc since moving away from freenode. The macOS channel on the official matrix is probably a better option.

**Comment by jsoo1** [comment]
Ok That's `#macos:nixos.org`?

**Comment by LnL7** [comment]
Yeah, I think so.
