### ISSUE TITLE
Something with /var/empty as a home directory is messing up home manager

### ISSUE THREAD

**Issue by devins2518** [LnL7/nix-darwin#423]
I was having an issue with GPG where `$GNUPGHOME` was set to `/var/empty/.gnupg` and caused all signing to fail since it couldn't read or write there. I attempted to fix this by adding this to my config:
```nix
  programs.gpg = {
    enable = true;
    homedir = "${config.xdg.dataHome}/.gnupg";
  };
```
However, this didn't fix the issue. `$GNUPGHOME` was being set to `/var/empty/.local/share/.gnupg` now. My fix is now this:
```nix
  programs.gpg = {
    enable = true;
    homedir = "/Users/devin/.local/share/.gnupg";
  };
```
This is obviously not ideal and not portable. 

I suspect that this is an issue with nix-darwin as it hasn't happened with my NixOS system which doesn't require this fix.

**Comment by devins2518** [comment]
I found this issue <https://github.com/nix-community/home-manager/issues/2004> which alluded to the fact that `users.users.<username>.home` is set to `/var/empty` by default, but doesn't seem to be set to the proper directory unless you define a user account. Is there any way to send out a warning or error message if there's no user accounts defined? I'll close the issue, but the examples or documentation should show that this issue will be caused if you don't set user accounts.

**Comment by mattsawyer77** [comment]
@FlakM I ran into this as well. I think you need to add

```nix
users.users.mflak = {
  name = "mflak";
  home = "/Users/mflak";
};
```

I'm not sure why my configuration was working before without it, but essentially your home-manager user and users.user need to match, IIUC.
