### ISSUE TITLE
~/.nix-profile points to folder that doesn't exist

### ISSUE THREAD

**Issue by devins2518** [LnL7/nix-darwin#424]
```sh
❯ ls ~/.nix-profile
lrwxr-xr-x  1 devin  staff  44 Jan 13 09:49 /Users/devin/.nix-profile -> /nix/var/nix/profiles/per-user/devin/profile
❯ ls /nix/var/nix/profiles/per-user/devin/profile
ls: /nix/var/nix/profiles/per-user/devin/profile: No such file or directory
```

**Comment by LnL7** [comment]
I think this is normal, until you install something in your user profile nothing is created IIRC.

**Comment by devins2518** [comment]
Packages from `environment.systemPackages` should leave things in the user profile, no?

**Comment by LnL7** [comment]
No system packages are global, nix-darwin doesn't touch users profiles. You can still freely use `nix-env` or `nix profile` within the context of your user.
