### ISSUE TITLE
LD not found 

### ISSUE THREAD

**Issue by G3zz** [LnL7/nix-darwin#425]
I am trying to compile GHC using stack installed via my nix-darwin configuration file.
I see these messages in the error logs:

```
2022-01-07 10:07:17.240214: [warn] hashable                         > /run/current-system/sw/bin/ld: line 254: /nix/store/8fpyhncn4m4x1kifzjizy0h8s2696ibk-binutils-2.35.2/bin/ld: No such file or directory
2022-01-07 10:07:17.242092: [warn] hashable                         > `ld' failed in phase `Merge objects'. (Exit code: 127)
```
Upon a closer look, it looks as if there is no ld binary supplied by binutils on nix-darwin.
```
> readlink /run/current-system/sw/bin/ld
> /nix/store/6dg7m90fvbm69knws1mhix5q5bmfq13k-binutils-wrapper-2.35.2/bin/ld
```
which calls `/nix/store/8fpyhncn4m4x1kifzjizy0h8s2696ibk-binutils-2.35.2/bin/ld`, which does not exist on nix-darwin: https://github.com/NixOS/nixpkgs/blob/2320573b696600fc868e3cc35ce7fb4b56a10f8e/pkgs/os-specific/darwin/binutils/default.nix#L27

However, when I execute `nix-shell -p --pure which binutils`, `ld` is found:

```
> which ld
> /nix/store/a2sz5pfcilnp7hw9hhqipvs3rvq3s59v-clang-wrapper-11.1.0/bin/ld
```
Therefore, I assume that if I can get `ld` callable from my default shell, then it will work for the stack build.
How can I get my default system `ld` pointing to the binary in `clang-wrappe`r as is done by nix-shell?

Additional details (from `nix-shell -p nix-info --run "nix-info -m"`):

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(user): `"darwin, home-manager, nixpkgs-22.05pre343831.77fda7f6727"`
 - channels(root): `"darwin, nixpkgs-22.05pre343436.0432195a4b8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs
```

Output of find / -name ld:

```
/usr/bin/ld
/nix/var/log/nix/drvs/ld
/nix/store/s7bxbn7aw9rzndmslb1hi8h2daai8076-system-path/bin/ld
/nix/store/33xrfsvf08lmps2m53wd2dmms38fm2sa-system-path/bin/ld
/nix/store/xw1fr2bcyrb345gyymd884hsrc5cbq6d-system-path/bin/ld
/nix/store/bb64lgvd32fzbfhxribri0cpyyrcrg7a-cctools-binutils-darwin-wrapper-949.0.1/bin/ld
/nix/store/6xdzry1904imzascysl4xv1l80w73fah-system-path/bin/ld
/nix/store/zkn8c6529cmds0c6vp4f1x4wrfs53csl-gfortran-wrapper-9.3.0/bin/ld
/nix/store/6dg7m90fvbm69knws1mhix5q5bmfq13k-binutils-wrapper-2.35.2/bin/ld
/nix/store/a2sz5pfcilnp7hw9hhqipvs3rvq3s59v-clang-wrapper-11.1.0/bin/ld
/nix/store/smlqklbkz6byzabiha76zfl6s1ii90x6-cctools-port-949.0.1/bin/ld
/nix/store/lark52dswbrjdfvb26qwm320fgrdy71k-cctools-binutils-darwin-949.0.1/bin/ld
```

I have already tried posting in the nix discourse forum, but I got no response: https://discourse.nixos.org/t/ld-not-found-nix-darwin/17020

**Comment by LnL7** [comment]
I don't fully understand what's going on here, but in general "installing" build dependencies with nix isn't best practice.
When building things using nix build tools you want to use a `nix-shell` environment instead globally installing compilers, etc.

- https://nix.dev/tutorials/ad-hoc-developer-environments
- https://nix.dev/tutorials/declarative-and-reproducible-developer-environments
