### ISSUE TITLE
macOS High Sierra - computer freezes on "darwin-rebuild build"

### ISSUE THREAD

**Issue by joseph-long** [LnL7/nix-darwin#44]
Using a MacBook Air with a fresh install of 10.13 on an encrypted case-insensitive APFS volume. When following the manual install instructions, I get as far as `$(nix-build '<darwin>' -A system --no-out-link)/sw/bin/darwin-rebuild build` before the OS locks up and I have to reboot.

**Comment by joseph-long** [comment]
Per @LnL7 on IRC, this is this issue: https://github.com/NixOS/nix/issues/1583#issuecomment-333503266

**Comment by LnL7** [comment]
The kernel bug was fixed in macOS 10.13.2.
