### ISSUE TITLE
Supporting Builtin Float?

### ISSUE THREAD

**Issue by mtoohey31** [LnL7/nix-darwin#454]
As of [a while ago](https://github.com/NixOS/nix/pull/762), Nix has builtin floats. Would you be open to a PR that refactors everything that uses [this custom float type](https://github.com/LnL7/nix-darwin/blob/4fdbb8168f61d31d3f90bb0d07f48de709c4fe79/modules/system/defaults-write.nix#L8) to use the builtin float type?

**Comment by mtoohey31** [comment]
Actually, I suppose for backwards compatability we should refactor so that the custom float type accepts builtin float, as well as all the types it currently accepts.

**Comment by beetcb** [comment]
Yeah, a little bit frustrating that the `float`(in mannul) is actually `string`.
I think we can start with improving the documentation first @LnL7 

<img width="596" alt="Screen Shot 2022-08-10 at 11 04 32" src="https://user-images.githubusercontent.com/63141491/183801613-9a6067a7-5628-409b-bab9-3599a074db37.png">
