### ISSUE TITLE
Managing expectations

### ISSUE THREAD

**Issue by kolpav** [LnL7/nix-darwin#462]
Hi, after fresh Mac OS reinstall I decided to replace homebrew with nix after reading all the praise about it but there was always something off with how everything behaves even when having exact current year config as other people. After digging further I think I finally realised what nix-darwin does it tries to mimick what you can do when running NixOS but on mac meaning it will never be 1:1 and as newbie learning nix ecosystem you are always left wondering if you are doing something wrong or if its because you are not using NixOS. I had really good experience installing packages and using home manager to enable and configure programs. Most problems I encountered were when I tried to do anything with `services.*` mainly postgres where `authentication` option is not available. I think it would be great to better explain what you can expect when using nix-darwin in readme instead of being throw into installation.
I don't want to take anything from this project its great I just need to have some configuration outside of it to set up my machine. I am now thinking of running NixOS directly.
You can write your own modules but I am not there yet and its unreasonable to expect from one person managing the project to keep everything 100% in sync.

**Comment by jskrzypek** [comment]
@kolpav many people find it best to use a combination of this package and [home-manager](https://rycee.gitlab.io/home-manager/)

**Comment by kolpav** [comment]
@jskrzypek 
>  I had really good experience installing packages and using home manager to enable and configure programs.

Already do, after more time with nix on macos I must say the postgre service setup along with not having apps available in spotlight are only two problems I have everything else is much easier to do thanks to nix.

**Comment by jskrzypek** [comment]
Sorry missed that line :)
