### ISSUE TITLE
Set hostname could also set NetBIOSName

### ISSUE THREAD

**Issue by joseph-long** [LnL7/nix-darwin#47]
In my script to set up a new Mac, I have `sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $new_hostname`. I can't find anything saying whether this is still used in High Sierra (I assume it is?) but it does not produce an error. Could be a good thing to add at https://github.com/LnL7/nix-darwin/blob/ebc7f7b2dafea3fe4610baf2c3ef90811b193229/modules/networking/default.nix#L9-L13 ?

**Comment by LnL7** [comment]
I have no idea what the difference is, is there an advantage to use one over the other?

**Comment by joseph-long** [comment]
It's just another thing to set, and it's used as the name to announce file shares for Windows / SMB users

**Comment by joseph-long** [comment]
Just checked: If you go in to System Preferences -> Sharing and fill in your computer name there, `/Library/Preferences/SystemConfiguration/com.apple.smb.server` gets updated.

**Comment by LnL7** [comment]
And `scutil --set LocalHostName` doesn't? I thought that was just a cli interface that does essentially the same thing.

**Comment by joseph-long** [comment]
```
12:33:42 Anansi:~ jdl$ defaults read /Library/Preferences/SystemConfiguration/com.apple.smb.server
[...]
    NetBIOSName = Anansi;
    ServerDescription = Anansi;
[...]
12:40:38 Anansi:~ jdl$ scutil --set LocalHostName Tanuki
12:40:47 Anansi:~ jdefaults read /Library/Preferences/SystemConfiguration/com.apple.smb.server
[...]
    NetBIOSName = Anansi;
    ServerDescription = Anansi;
[...]
```

**Comment by joseph-long** [comment]
Hit submit too soon, but looks like no.

**Comment by LnL7** [comment]
Looks like you're right then and here's another place where it's mentioned.
https://github.com/herrbischoff/awesome-osx-command-line#hostname
