### ISSUE TITLE
How to contribute by upgrading a package

### ISSUE THREAD

**Issue by kinghrothgar** [LnL7/nix-darwin#472]
I would like to get a golang 1.18 package added to the repository. I am struggling to figure out how to go about this. Could someone point me in the right direction?

**Comment by ChrisPattison** [comment]
You will want to contribute to the main nixpkgs repository at https://github.com/NixOS/nixpkgs

**Comment by malob** [comment]
@domenkozar, I think this issue is resolved and can be closed.
