### ISSUE TITLE
Usage of `environment.pathsToLink` on newer versions of macOS

### ISSUE THREAD

**Issue by brendanzab** [LnL7/nix-darwin#474]
Searching the repository to see how `environment.pathsToLink` is used, I see lots of paths beginning with `/share/` in the values set by various modules. On macOS 12.4 it seems like this directory does not exist, while equivalents seem to live under `/usr/`, so should I be adding these myself? Eg.

```nix
{
  environment.pathsToLink = [
    "/usr/bin"
    "/usr/share/doc"
    "/usr/share/info"
    "/usr/share/locale"
    "/usr/share/man"
    "/usr/share/zsh"
  ];
}
```

Still a bit unclear as to what `pathsToLink` does, so I could be mistaken!

**Comment by Pablo1107** [comment]
Kinda a noob question but I'm having issues with darwin manpages not being properly configured and I think this may have to be related.

**Comment by lovesegfault** [comment]
They get linked relative to `/run/current-system/sw/`, not `/`.

So, `/run/current-system/sw/share` should exist :)

**Comment by brendanzab** [comment]
Funnily enough this was related to manpages too.

What about for system tools? ie. those not installed with Nix?

**Comment by brendanzab** [comment]
> They get linked relative to `/run/current-system/sw/`, not `/`.
> 
> So, `/run/current-system/sw/share` should exist :)

OOOOH! I get it now! These are paths from that are linked in each `environment.systemPackage`’s directory into `/run/current-system/sw/`. The path is given to `pkgs.buildEnv`’s [`pathsToLink` argument](https://github.com/NixOS/nixpkgs/blob/b52d335b98a80aea4878ab479492b33a31b8e857/pkgs/build-support/buildenv/default.nix#L24-L27) via [`system.path`](https://github.com/LnL7/nix-darwin/blob/54a24f042f93c79f5679f133faddedec61955cf2/modules/environment/default.nix#L179-L183).

**Comment by brendanzab** [comment]
One thing I am confused by though: will the paths from packages installed with home manager be linked based on this option? I see `environment.pathsToLink` [mentioned a bunch](https://nix-community.github.io/home-manager/options.html#opt-programs.bash.enableCompletion) in the docs.

**Comment by brendanzab** [comment]
Oh, it seems like these are linked under `/etc/profiles/per-user/$USER/`, and home manager just links all directories in the package by default.

**Comment by Pablo1107** [comment]
But maybe home manager sets the some paths (specifically man path) making them not available?

**Comment by brendanzab** [comment]
Just out of curiousity, what manpages are breaking for you that you are expecting to work? Might be worth making another issue. For me it seems like it isn’t picking up stuff from `/Library/Developer/CommandLineTools/usr/share`:

```command
$ man otool
No manual entry for otool
```

**Comment by brendanzab** [comment]
I managed to fix this for the command line tools: https://github.com/nix-community/home-manager/issues/2634#issuecomment-1222564133

Not sure if that’s of any use to you!
