### ISSUE TITLE
Nix fails to create some temporary symlinks

### ISSUE THREAD

**Issue by Sciencentistguy** [LnL7/nix-darwin#484]
On aarch64-darwin, I get the following output from nix:
```
<N> ➜ darwin-rebuild -L --flake /Users/jamie/Git/nixfiles switch
building the system configuration...
error: cannot link '/nix/store/.tmp-link-64480-79859421' to '/nix/store/.links/0i6ypwi0pzkgpxxqprlpyik72zxzkvkzrj7ahqj5b6hmhv2ldxm0': File exists
error: cannot link '/nix/store/.tmp-link-64480-1103639509' to '/nix/store/.links/0dwrq1sy5fawdjjvm0na718awbd10xn6dg3i0xxg9f7r5d9aa968': File exists
...
```

I have to pass `--fallback` to `darwin-rebuild` to get it to work.

**Comment by dj95** [comment]
Same for me on two systems. One is an intel MBP and the other one aarch64-darwin as well.

**Comment by malob** [comment]
This has also come up for me on `aarch64-darwin` from time to time. In my case running the command again solved the issue. Don't really have any idea what's causing it.

**Comment by Enzime** [comment]
I believe this is an issue when the Nix setting `auto-optimise-store` is enabled

See https://github.com/NixOS/nix/issues/7273
