### ISSUE TITLE
Make Nix-managed fonts available.

### ISSUE THREAD

**Issue by sellout** [LnL7/nix-darwin#49]
I imagine they could be linked into ~/Library/Fonts/ in much the same way the Applications are linked into ~/Applications.

They seem to consistently be in <derivation>/fonts, but there are a bunch of directories in there, and I’m not sure what should be in ~/Library/Fonts.

**Comment by LnL7** [comment]
I expect linking just stuff to ~/Library/Fonts will not be enough for macOS to detect the new fonts. However the `fontrestore(8)` manpage looks promising.

**Comment by pjan** [comment]
- Linking to `~/Library/Fonts` should be enough for the fonts to be visible to other applications (fontbook will probably not see it though, IIRC).
- `fontrestore` should remove all non-default fonts from that directory (move it to `~/Library/Fonts (Removed)`). It will also move the non-default fonts that aren't managed by nix-darwin
