### ISSUE TITLE
Add examples.mohacker (my username)

### ISSUE THREAD

**Issue by yurrriq** [LnL7/nix-darwin#5]
I use Emacs and fish, which might be a nice complement to `lnl.nix`'s Vim and zsh config.

**Comment by LnL7** [comment]
I would love to add some more examples, but they should be a bit more focused then the one that's in there now.
This project basically started out as my `config.nix` and left it in as an example because there is not enough documentation at the moment.

**Comment by yurrriq** [comment]
:+1: perhaps I'll just do some sample Emacs and fish configs. The rest is boring and probably overly personal.

**Comment by LnL7** [comment]
Once there is more documentation and examples, I'll simplify it so it's just a simple example that resembles my configuration.

**Comment by yurrriq** [comment]
I'm thinking this is pretty pointless now and I can just document any modules I add via their options.

**Comment by LnL7** [comment]
Having a practical example can be very helpful, even if has user specific configuration. I was mainly referring to the config files I added to the example.
