### ISSUE TITLE
undefined variable 'isFloat' since the latest commits

### ISSUE THREAD

**Issue by luxus** [LnL7/nix-darwin#500]
hello,
looks like i having some trouble with the latest commits from @malob 
https://github.com/LnL7/nix-darwin/blob/5af1aa51f63d734284bf6728a21d2c9c31eb7492/modules/nix/default.nix#L40

 i cannot run:
```
->> darwin-rebuild switch --flake .#emily 
warning: Git tree '/Users/luxus/Source/nix-config' is dirty
building the system configuration...
warning: Git tree '/Users/luxus/Source/nix-config' is dirty
error: undefined variable 'isFloat'

       at /nix/store/dxmv2y9d6p7z5i0wf8m9zlpn41s8fg6z-source/modules/nix/default.nix:40:17:

           39|         else if isBool v then boolToString v
           40|         else if isFloat v then floatToString v
             |                 ^
           41|         else if isList v then toString v
(use '--show-trace' to show detailed location information)
```
thats the flake i run https://github.com/luxus/nix-config/blob/mychanges/hosts/emily/darwin.nix
home-manager works fine, thats why i didn't notice the issue yet.

**Comment by malob** [comment]
Huh, interesting.

Could you rerun that same command with `--show-trace` and post the output here?

**Comment by malob** [comment]
Never mind, I just build you flake locally. I'll see what I can figure out, but I won't have much time until later today or tomorrow.

**Comment by luxus** [comment]
take your time.. most stuff is in my home-manager anyways :D

**Comment by malob** [comment]
`darwin-rebuild build --flake .#emily` succeeds if you make the following change:

```diff
diff --git a/flake.nix b/flake.nix
index d456fda..abd2f49 100644
--- a/flake.nix
+++ b/flake.nix
@@ -8,7 +8,10 @@
     nur.url = "github:nix-community/NUR";
     impermanence.url = "github:misterio77/impermanence"; # TODO change to upstream after #99 is merged
     nix-colors.url = "github:misterio77/nix-colors";
-    darwin.url = "github:LnL7/nix-darwin";
+    darwin = {
+      url = "github:LnL7/nix-darwin";
+      inputs.nixpkgs.follows = "nixpkgs";
+    };
     stylix.url = "github:danth/stylix";
     rust-overlay = {
       url = "github:oxalica/rust-overlay";
```

My guess as to why you were having the issue is because the `nix-darwin` flake uses `lib` from it's `nixpkgs` input when importing `eval-config.nix`,
https://github.com/LnL7/nix-darwin/blob/ef0e7f41cdf8fae1d2390c4df246c90a364ed8d9/flake.nix#L8


though I don't really understand why building your config failed where it did and I don't see a reason why the changes I made in #490 would be related to the failure ¯\_(ツ)_/¯.

**Comment by luxus** [comment]
it builds..  wow great i would stuck forever as a nixos noob 
thank you so much
