### ISSUE TITLE
wrong order of directories in PATH when using fish

### ISSUE THREAD

**Issue by jab** [LnL7/nix-darwin#502]
I just installed nix-darwin in a fresh macOS 11.6.8 environment. When I echo my PATH running the default shell `zsh`, I see nix-related PATHs *pre*pended, as I expect:
```console
> echo $PATH | tr : \\n                                                                                                
/Users/jab/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/Users/jab/.nix-profile/bin
/run/current-system/sw/bin
/nix/var/nix/profiles/default/bin
/usr/local/bin
/usr/bin
/usr/sbin
/bin
/sbin
```

However, after adding `pkgs.fish` to `environment.systemPackages` and setting `programs.fish.enable = true` in my `darwin-configuration.nix`, then configuring Terminal.app's "Shells open with" setting to `/run/current-system/sw/bin/fish`, the `PATH` that gets set for `fish` is wrong, with the nix-related directories occurring too late:
```console
❯ echo $PATH | tr ' ' \\n
/Users/jab/.local/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/jab/.nix-profile/bin
/run/current-system/sw/bin
/nix/var/nix/profiles/default/bin
```
Wondering if others can reproduce this, and what the best way to fix or work around this would be. Thanks!

**Comment by malob** [comment]
This is definitely annoying, though I believe there is already an issue for this: https://github.com/LnL7/nix-darwin/issues/122

**Comment by jab** [comment]
Thanks @malob, I'd searched the tracker but hadn't found that, sorry. Closing this and will follow #122.

Noticed that's been open since 2019, which I wouldn't have expected for an issue like this. Do you know if that's due to this being unexpectedly tricky to fix, lack of time/interest, something else? Thanks again.
