### ISSUE TITLE
Custom defaults/plist writes?

### ISSUE THREAD

**Issue by pshirshov** [LnL7/nix-darwin#517]
From what I can see, there is no way to define custom values to be written with `defaults`.
Though that would be very useful. Some time ago I've been using ansible to provision Macs and created a [long list](https://github.com/7mind/mac-configurator/blob/master/configs/config-settings.yml) of various customisations, not all of them are currently supported by `nix-darwin`.

**Comment by ForsakenHarmony** [comment]
@pshirshov is your list still available somewhere? That repository seems to have been set to private or deleted
