### ISSUE TITLE
GUI Emacs path isn’t set correctly.

### ISSUE THREAD

**Issue by sellout** [LnL7/nix-darwin#52]
Not really sure where this issue should live, so I’m starting here.

Looking at it in more detail, there are some other differences, but the key thing here is that “/run/current-system/sw/bin” isn’t in the paths seen by Emacs. I’m not sure if this is an issue from the Emacs side or the way that nix-darwin sets up Mac applications (running `emacs` from the command-line gives paths _with_ “/run/current-system”).

path|shell|emacs `$PATH`|emacs `exec-path`
----|-----|-------------|-----------------
/nix/store/wqcaqhb3xx6gl8h68w2ws7d9zx3qwpkp-emacs-packages-deps/bin|||✔
~/.nix-profile/bin|✔|✔|✔
~/.nix-profile/sbin||✔|✔
~/.nix-profile/lib/kde4/libexec||✔|✔
**/run/current-system/sw/bin**|✔|cli|cli
/nix/var/nix/profiles/default/bin|✔|✔|✔
/nix/var/nix/profiles/default/sbin||✔|✔
/nix/var/nix/profiles/default/lib/kde4/libexec||✔|✔
/usr/local/bin|✔|✔|✔
/usr/bin|✔|✔|✔
/usr/sbin|✔|↓|↓
/bin|✔|↑|↑
/sbin|✔|✔|✔
/nix/store/55rl77707n7wvxwf4qqpz2n92agris3y-emacs-mac-25.3-6.7/libexec/emacs/25.3/x86_64-apple-darwin16.6.0|||✔

**Comment by yurrriq** [comment]
FWIW `/run/current-system/sw/bin` *is* in my `exec-path` :/

**Comment by sellout** [comment]
@yurrriq Interesting – if you don’t mind I’d like to try to figure out what’s different between our setups …

* Do your paths otherwise look similar to the ones I put in the table?
* Are you running Emacs by double-clicking on the icon? (I am)
* Are you using emacs-with-packages? (I am)
* Are you using emacs25Macport? (I am)

Thanks!

**Comment by yurrriq** [comment]
@sellout:

> Do your paths otherwise look similar to the ones I put in the table?

More or less. It looks like it's reading my `$PATH` that I set up in `config.fish`


> Are you running Emacs by double-clicking on the icon?

No.

```fish
emacsclient -cna ""
```

> Are you using emacs-with-packages?
> Are you using emacs25Macport?

No.

```nix
{
  environment.systemPackages = (with pkgs; [
    emacs # NOTE: emacs = emacs25;
  ]);
}
```

**Comment by yurrriq** [comment]
Also possibly relevant is this part of my `.spacemacs`:

```elisp
(defun dotspacemacs/layers ()
  (setq-default
   dotspacemacs-configuration-layers
   `((shell :variables
            shell-default-term-shell "/run/current-system/sw/bin/fish"
            shell-default-height 30
            shell-default-position 'bottom)))
```

**Comment by sellout** [comment]
@yurrriq So, my guess is that it has to do with launching via the Finder (but I’m not ruling out the macport or anything else). For me `emacsclient -cna ""` doesn’t start anything. If I drop the `n`, I get Emacs in the terminal with the correct paths, so that doesn’t really help.

I might try again toggling other bits – `with-packages`, `Macport`, etc.

**Comment by LnL7** [comment]
This might help, I'm pretty sure GUI applications use the users bootstrap context and won't load anything from you shell environment.

```nix
{ config, lib, pkgs, ... }:
{
  config.launchd.user.envVariables.PATH = config.environment.systemPath;
}
```

**Comment by sellout** [comment]
Cool, I’m trying this now …

To make sure we’re on the same page, this should be the default behavior, right? I.e., the PATH for Nix-managed Applications should be the same as the path for Nix-managed shells (modulo darwin-configuration.nix overriding one or the other – which I haven’t done).

**Comment by sellout** [comment]
Hrmm, nope. My new Emacs sees the same paths as before.

**Comment by sellout** [comment]
I _did_ modify the entry a bit, `launchd.user.envVariables.PATH = config.environment.systemPath;
`
because the original gave me an error:
> error: Module `/Users/greg/.nixpkgs/darwin-configuration.nix' has an unsupported attribute `environment'. This is caused by assignments to the top-level attributes `config' or `options'.

**Comment by LnL7** [comment]
Assuming this is fixed in https://github.com/LnL7/nix-darwin/pull/252.
