### ISSUE TITLE
Packages are not present in PATH (home-manager as nix-darwin module)

### ISSUE THREAD

**Issue by DavSanchez** [LnL7/nix-darwin#521]
Hello all,

I am trying to set up `home-manager` as a `nix-darwin` module (fresh install of `nix-darwin` just a few days ago) and I noticed this way the location where the packages are installed is not added to `$PATH`. Setting `home-manager.useUserPackages = false;` makes the user packages available, but the system packages installed as part of `environment.systemPackages` are not.

```console
$ which bat # User package
/Users/david/.nix-profile/bin/bat

$ which xh # System package
xh not found
```

Looks there is a path somewhere that is not added to `$PATH` at some point, or perhaps being rewritten? (for example, I see `starship` is activated in my terminal, but if I try to reach the `starship` location I get a `not found` 🤷‍♂️ .

Using `home-manager` in standalone mode works, as the user packages are installed elsewhere (same as when using `home-manager.useUserPackages = false`.

If I do `. /etc/static/zshrc` in a terminal session nothing happens, and I see this very line is included at the end of `/etc/zshrc` (added by `nix-darwin` IIRC).

Could you please help me figure this out? Thanks!

**Comment by v3s1e** [comment]
How did you manage to solve this?

**Comment by DavSanchez** [comment]
Hey, sorry, I’m afraid I stopped worrying for this as I switched to stand alone home-manager for other reasons.

**Comment by DavSanchez** [comment]
Sadly that didn’t work for me back then 😅
