### ISSUE TITLE
error: The option `programs.zsh.enableAutosuggestions' does not exist.

### ISSUE THREAD

**Issue by champignoom** [LnL7/nix-darwin#527]
Newbie user trying to set up zsh.

`~/.nixpkgs/darwin-configuration.nix`:
```
{ config, lib, pkgs, ... }:
{
  environment.systemPackages = [ pkgs.zsh-autosuggestions ];
  services.nix-daemon.enable = true;
  programs.zsh.enable = true;
  programs.zsh.enableAutosuggestions = true;
  system.stateVersion = 4;
}

```

```
$ darwin-rebuild switch
error: The option `programs.zsh.enableAutosuggestions' does not exist.
...
```

This happens to `programs.zsh.plugins = [];` as well. It seems that only a fixed set of options (listed in `man configuration.nix`) are available on nix-darwin.

**Comment by DavSanchez** [comment]
Hi,

As far as I can tell,  `programs.zsh.enableAutosuggestions` is an option from [`home-manager`](https://nix-community.github.io/home-manager/options.html#opt-programs.zsh.enableAutosuggestions), so only if you are using that you'll be able to use it. `nix-darwin` does not provide this option _per se_ [according to its manual](https://daiderd.com/nix-darwin/manual/index.html#sec-options).
