### ISSUE TITLE
State of support for multiuser mode nix installs

### ISSUE THREAD

**Issue by eqyiel** [LnL7/nix-darwin#53]
Should the `nix-daemon` service be enabled by default now that the nix installer is in multi-user mode?

If not, this is probably something that needs documentation.

~Currently `services.nix-daemon` does not set the variables `NIX_BUILD_HOOK` or `NIX_REMOTE_SYSTEMS` when `nix.buildMachines` or `nix.distributedBuilds` is set.~

Maybe this is nothing to worry about right now?  We've deliberately stayed on Sierra at work because of problems with High Sierra (https://github.com/NixOS/nix/issues/1583), I suppose anyone else who is aware of that issue is holding back too.

**Comment by eqyiel** [comment]
Sorry, a correction: `services.nix-daemon` gets environment variables from `nix.nixEnv`, which include the variables `NIX_BUILD_HOOK` and `NIX_REMOTE_SYSTEMS` when `nix.buildMachines` and `nix.distributedBuilds` is set.

I didn't notice because I had the `nix-daemon` service from the nix installer running.

That one needs to be clobbered by the one that `nix-darwin` makes in order for distributed builds to work.  I just ran `darwin-rebuild switch` and rebooted in order to do that because `launchctl` is not very intuitive to me.

**Comment by eqyiel** [comment]
I don't think this is a thing anymore, and probably won't trip people up since https://github.com/LnL7/nix-darwin/commit/9792b08fdf049524742143f4f788e3eb61a769fd

**Comment by LnL7** [comment]
This is only partially true, the nix package and daemon are not managed by default to support both single and mutli-user installs. However this is kind of unexpected behaviour from something that's supposed to manage everything declaratively.
