### ISSUE TITLE
`[oh-my-zsh] Can't update: not a git repository.`

### ISSUE THREAD

**Issue by zupo** [LnL7/nix-darwin#532]
Since upgrading to macOS 12.6, I've been seeing this error when opening up a new Terminal session: `[oh-my-zsh] Can't update: not a git repository.`

Today I decided to investigate a bit, and it seems the reason is that `/usr/bin/git` is getting called, instead of `git` provided by nix-darwin. The culprit seems to be that `/usr/bin/git` takes precedence over `/run/current-system/sw/bin/git`. I believe that it used to be the other way around, that whatever nix-darwin built took precedence in my shell over system provided stuff. 

Here's my `$PATH`:

```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/zupo/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/Users/zupo/bin
```

And [here](https://github.com/zupo/dotfiles/blob/af8c9546c5abed6c2b36b8e25f6e3d9d0c61eac7/darwin-configuration.nix)'s my `darwin-configuration.nix`.

How do I make `/run/current-system/sw/bin/` take precedence over `/usr/bin/`? Is this a bad idea?

**Comment by zupo** [comment]
I've updated `nix-darwin` to latest master and nixpkgs to latest 22.05. All relevant files are in https://github.com/zupo/dotfiles, including `zshrc`, `zprofile`, etc.

**Comment by zupo** [comment]
Seems to be related to https://github.com/LnL7/nix-darwin/issues/122.

**Comment by zupo** [comment]
Browsing related issues above I found a workaround that works for me: comment out `path_helper` in `/etc/zprofile`:

```sh
#if [ -x /usr/libexec/path_helper ]; then
#	eval `/usr/libexec/path_helper -s`
#fi
```

https://github.com/zupo/dotfiles/commit/687e8a2123982621e65dbb9013b64eb4c1456d46

**Comment by philcruz** [comment]
I'm also having this problem. In my case `/etc/zprofile` doesn't have `path_helper` so I can't comment it out. 

```
# /etc/zprofile: DO NOT EDIT -- this file has been generated automatically.
# This file is read for login shells.

# Only execute this file once per shell.
if [ -n "$__ETC_ZPROFILE_SOURCED" ]; then return; fi
__ETC_ZPROFILE_SOURCED=1

# Read system-wide modifications.
if test -f /etc/zprofile.local; then
  source /etc/zprofile.local
fi
```
I'm looking at ~/.zshenv and ~/.zprofile and and ~/.zshrc and I don't see `path_helper` in any of those files.

**Comment by zupo** [comment]
Still using this workaround, seems to work fine.
