### ISSUE TITLE
'runCommandNoCC' has been renamed to/replaced by 'runCommand'

### ISSUE THREAD

**Issue by Boelensman1** [LnL7/nix-darwin#538]
After updating to nix 2.11.0, I get the following error when running darwin-rebuild switch:
```
'runCommandNoCC' has been renamed to/replaced by 'runCommand'
```

This happens even with an (almost) empty configuration file, currently just:
```
{ pkgs, ... }:
{
}
```

I tried running with --show-trace but it didn't really seem to lead to the problem, in case its helpful I copy pasted it here:
<details>
  <summary>Click me</summary>

       building the system configuration...

       error: 'runCommandNoCC' has been renamed to/replaced by 'runCommand'

       … while evaluating 'checkInPkgs'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/pkgs/top-level/aliases.nix:21:20:

           20|   # Make sure that we are not shadowing something from all-packages.nix.
           21|   checkInPkgs = n: alias:
             |                    ^
           22|     if builtins.hasAttr n super

       … from call site

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/pkgs/top-level/aliases.nix:30:12:

           29|         (removeRecurseForDerivations
           30|           (checkInPkgs n alias)))
             |            ^
           31|       aliases;

       … while evaluating 'removeRecurseForDerivations'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/pkgs/top-level/aliases.nix:8:33:

            7|   # to appear while listing all the packages available.
            8|   removeRecurseForDerivations = alias: with lib;
             |                                 ^
            9|     if alias.recurseForDerivations or false

       … from call site

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/pkgs/top-level/aliases.nix:29:10:

           28|       removeDistribute
           29|         (removeRecurseForDerivations
             |          ^
           30|           (checkInPkgs n alias)))

       … while evaluating 'isDerivation'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/attrsets.nix:427:18:

          426|   */
          427|   isDerivation = x: x.type or null == "derivation";
             |                  ^
          428|

       … from call site

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/pkgs/top-level/aliases.nix:16:8:

           15|   removeDistribute = alias: with lib;
           16|     if isDerivation alias then
             |        ^
           17|       dontDistribute alias

       … while evaluating 'removeDistribute'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/pkgs/top-level/aliases.nix:15:22:

           14|   # sets from building on Hydra.
           15|   removeDistribute = alias: with lib;
             |                      ^
           16|     if isDerivation alias then

       … from call site

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/pkgs/top-level/aliases.nix:28:7:

           27|     lib.mapAttrs (n: alias:
           28|       removeDistribute
             |       ^
           29|         (removeRecurseForDerivations

       … while evaluating anonymous lambda

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/pkgs/top-level/aliases.nix:27:22:

           26|   mapAliases = aliases:
           27|     lib.mapAttrs (n: alias:
             |                      ^
           28|       removeDistribute

       … from call site

       … while evaluating the attribute 'value'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/types.nix:526:60:

          525|           # Push down position info.
          526|           (map (def: mapAttrs (n: v: { inherit (def) file; value = v; }) def.value) defs)));
             |                                                            ^
          527|       emptyValue = { value = {}; };

       … while evaluating 'dischargeProperties'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/modules.nix:806:25:

          805|   */
          806|   dischargeProperties = def:
             |                         ^
          807|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/modules.nix:735:137:

          734|         defs' = concatMap (m:
          735|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          736|         ) defs;

       … while evaluating definitions from `/nix/store/45811g7qihh83wrc7160idbq2afx3lny-darwin/darwin/modules/system/etc.nix':

       … while evaluating anonymous lambda

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/modules.nix:734:28:

          733|         # Process mkMerge and mkIf properties.
          734|         defs' = concatMap (m:
             |                            ^
          735|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/modules.nix:734:17:

          733|         # Process mkMerge and mkIf properties.
          734|         defs' = concatMap (m:
             |                 ^
          735|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/modules.nix:847:7:

          846|     in {
          847|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          848|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/modules.nix:748:9:

          747|       in {
          748|         values = defs''';
             |         ^
          749|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'optionalValue'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/modules.nix:766:5:

          765|
          766|     optionalValue =
             |     ^
          767|       if isDefined then { value = mergedValue; }

       … while evaluating anonymous lambda

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/types.nix:522:86:

          521|       merge = loc: defs:
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                                                                      ^
          523|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … from call site

       … while evaluating anonymous lambda

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/types.nix:522:51:

          521|       merge = loc: defs:
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                                   ^
          523|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … from call site

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/attrsets.nix:225:62:

          224|   filterAttrs = pred: set:
          225|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                                                              ^
          226|

       … while evaluating anonymous lambda

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/attrsets.nix:225:29:

          224|   filterAttrs = pred: set:
          225|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                             ^
          226|

       … from call site

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/attrsets.nix:225:18:

          224|   filterAttrs = pred: set:
          225|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                  ^
          226|

       … while evaluating 'filterAttrs'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/attrsets.nix:224:23:

          223|   */
          224|   filterAttrs = pred: set:
             |                       ^
          225|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));

       … from call site

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/types.nix:522:35:

          521|       merge = loc: defs:
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                   ^
          523|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … while evaluating 'merge'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/types.nix:521:20:

          520|       check = isAttrs;
          521|       merge = loc: defs:
             |                    ^
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:

       … from call site

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/modules.nix:756:59:

          755|       if isDefined then
          756|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                                                           ^
          757|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/modules.nix:754:5:

          753|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          754|     mergedValue =
             |     ^
          755|       if isDefined then

       … while evaluating the option `system.build':

       … while evaluating the attribute 'value'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/modules.nix:719:9:

          718|     in warnDeprecation opt //
          719|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          720|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/modules.nix:268:72:

          267|           # For definitions that have an associated option
          268|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          269|

       … from call site

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/attrsets.nix:401:20:

          400|               then recurse (path ++ [name]) value
          401|               else f (path ++ [name]) value;
             |                    ^
          402|         in mapAttrs g;

       … while evaluating 'g'

       at /nix/store/vxcy8nsfri3s1kryh00m83mgxsikxy95-nixpkgs/nixpkgs/lib/attrsets.nix:398:19:

          397|           g =
          398|             name: value:
             |                   ^
          399|             if isAttrs value && cond value

       … from call site
</details>

**Comment by water-sucks** [comment]
I'm running into the same problem. I dug a little into nixpkgs and saw that `runCommandNoCC` was completely deprecated and replaced with a `throw` a week ago in [this commit](https://github.com/NixOS/nixpkgs/commit/d06207386df9a53fe01f8a30130dfc9a839fc8fc), and using nixpkgs at this commit is where it begins for me. I don't know how to resolve it though, because I thought all references to `runCommandNoCC` in this repo were removed in PR #535.

**Comment by g5pw** [comment]
I was in the same position, and running `nix-channel --update darwin` fixes the issue. Remember that running `sudo nix-channel --update` does not update nix-darwin itself!

**Comment by water-sucks** [comment]
Interesting; I'm using flakes on my system so I have no configured channels. Using the latest commit for my nix-darwin input and also the latest on nixos-unstable; I'm still running into that issue.

**Comment by Boelensman1** [comment]
Can confirm that `nix-channel --update darwin` fixed the issue! Had to reboot first for that command to work as I had the same issue as described here: https://github.com/NixOS/nix/issues/1980.

Thanks for the help, issue resolved!
