### ISSUE TITLE
Ability to manage kernel modules

### ISSUE THREAD

**Issue by lukeadams** [LnL7/nix-darwin#54]
Darwin allows dynamic loading of kernel modules with `sudo kextload $kextpath` and unloading with `sudo kextunload $kextpath`.
Maybe we can have nix-darwin load kexts from nix packages (I'm thinking for the NVIDIA CUDA drivers). The kexts must have permissions of user=root, group=wheel so it may not work in the store.

```
# Scan packages for $out/Library/Extensions/*.kext
system.extraModulePackages = [ ];
```
Then we can add options for loading the modules from nixpkgs-generated store paths:
```
hardware.gpu.nvidiaCuda = true;
```
which would add the CUDA kext to `system.extraModulePackages`, in addition to adding the CUDA package to `systemPackages`

Hopefully that makes sense!

**Comment by LnL7** [comment]
I don't know how many kexts we have in nixpkgs (if any) but the idea sounds ok. SIP probably also needs to be disabled for this to work, but that can be checked with `csrutil status` during activation.

**Comment by lukeadams** [comment]
Just a few notes:
- I was able to load the CUDA kext after I relocated it and fixed permissions without disabling SIP. If  third party kexts don't have any references to frameworks loading should be possible without patching! I'm testing with the cuda driver this weekend.
- I don't see any mention of "kext" in nixpkgs, so as far as I can tell no packages explicitly produce kexts in $out. 
- [High Sierra adds an approval flow for new kexts](https://developer.apple.com/library/content/technotes/tn2459/_index.html#//apple_ref/doc/uid/DTS40017658) - but that's a side issue.

**Comment by lukeadams** [comment]
Just a quick update - 
Using my [nixpkgs](https://github.com/lukeadams/nixpkgs/tree/cuda-drivers-darwin) and [nix-darwin](https://github.com/lukeadams/nix-darwin/tree/kextload) forks one can add the following to darwin-configuration.nix:
```
system.kernel.extraModulePackages = [
  pkgs.darwin.nvidia-cuda-driver
];
```
Resulting in
<img width="490" alt="screen shot 2017-11-28 at 14 11 01" src="https://user-images.githubusercontent.com/3508077/33342038-4e679aec-d446-11e7-91a0-a53e7277291a.png">

I just need to write the activation scripts!
Thankfully the permissions are already correct, so no fixing is required (although I may set it to root:wheel just to be safe).

**Comment by LnL7** [comment]
Cool! You can't change the ownership/permissions of store paths, but if you use the daemon it will be owned by root.

**Comment by lukeadams** [comment]
My workaround for permission fixing would have been to copy the kexts into profile, but it turns out it's not necessary:
```
lukeadams@Lukes-Mac /> sudo kextutil /nix/store/q7nx63abwvcjg1l6b053myc9y7fqaa2c-nvidia-cuda-9.0.176-driver/Library/Extensions/CUDA.kext -v 3
Defaulting to kernel file '/System/Library/Kernels/kernel'
/nix/store/q7nx63abwvcjg1l6b053myc9y7fqaa2c-nvidia-cuda-9.0.176-driver/Library/Extensions/CUDA.kext appears to be loadable (not including linkage for on-disk libraries).
Reading loaded kext info from kernel.
Loading /nix/store/q7nx63abwvcjg1l6b053myc9y7fqaa2c-nvidia-cuda-9.0.176-driver/Library/Extensions/CUDA.kext.
Reading load info for 3 kexts.
Reading loaded kext info from kernel.
Adding /nix/store/q7nx63abwvcjg1l6b053myc9y7fqaa2c-nvidia-cuda-9.0.176-driver/Library/Extensions/CUDA.kext to mkext.
Created mkext for architecture x86_64 containing 1 kexts.
Loading /nix/store/q7nx63abwvcjg1l6b053myc9y7fqaa2c-nvidia-cuda-9.0.176-driver/Library/Extensions/CUDA.kext.
(kernel) Received request from user space to load kext com.nvidia.CUDA.
(kernel) Loading kext com.nvidia.CUDA.
(kernel) Allocated link buffer for kext com.nvidia.CUDA at 0xffffff7f9133f000 (12288 bytes).
(kernel) Kext com.nvidia.CUDA executable loaded; 3 pages at 0xffffff7f8233f000 (load tag 118).
(kernel) Kext com.nvidia.CUDA is now started.
(kernel) Kext com.nvidia.CUDA loaded.
Successfully loaded /nix/store/q7nx63abwvcjg1l6b053myc9y7fqaa2c-nvidia-cuda-9.0.176-driver/Library/Extensions/CUDA.kext.
/nix/store/q7nx63abwvcjg1l6b053myc9y7fqaa2c-nvidia-cuda-9.0.176-driver/Library/Extensions/CUDA.kext successfully loaded (or already loaded).

lukeadams@Lukes-Mac /> sudo kextstat | grep -i nvidia
  118    0 0xffffff7f8233f000 0x3000     0x3000     com.nvidia.CUDA (1.1.0) 4329B052-6C8A-3900-8E83-744487AEDEF1 <4 1>
```

**Comment by lukeadams** [comment]
Just got loading/unloading working!
```
bash-4.4# #pkgs.darwin.nvidia-cuda.driver added:
bash-4.4# darwin-rebuild switch -I darwin=/Volumes/SharedFolders/prl-osx-vmshare/nix-darwin -I nixpkgs=/Volumes/SharedFolders/nixpkgs-x11-upgrade/nixpkgs
building the system configuration...
writing defaults...
setting up user launchd services...
setting up ~/Applications...
setting up /etc...
setting up launchd services...
loading kext [CUDA.kext]
Defaulting to kernel file '/System/Library/Kernels/kernel'
/nix/store/q7nx63abwvcjg1l6b053myc9y7fqaa2c-nvidia-cuda-9.0.176-driver/Library/Extensions/CUDA.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /nix/store/q7nx63abwvcjg1l6b053myc9y7fqaa2c-nvidia-cuda-9.0.176-driver/Library/Extensions/CUDA.kext.
/nix/store/q7nx63abwvcjg1l6b053myc9y7fqaa2c-nvidia-cuda-9.0.176-driver/Library/Extensions/CUDA.kext successfully loaded (or already loaded).
configuring time...
configuring networking...

bash-4.4# #pkgs.darwin.nvidia-cuda.driver removed:
bash-4.4# darwin-rebuild switch -I darwin=/Volumes/SharedFolders/prl-osx-vmshare/nix-darwin -I nixpkgs=/Volumes/SharedFolders/nixpkgs-x11-upgrade/nixpkgs
building the system configuration...
writing defaults...
setting up user launchd services...
setting up ~/Applications...
setting up /etc...
setting up launchd services...
unloading kext [CUDA.kext]
com.nvidia.CUDA unloaded and personalities removed.
configuring time...
configuring networking...
```

**Comment by Enzime** [comment]
@lukeadams are you planning to make a pull request for this? I think this would be quite useful for osxfuse+sshfs.

**Comment by Enzime** [comment]
@lukeadams It's probably better to make new comments rather than editing as people won't get notified for an edit.

**Comment by lukeadams** [comment]
@Enzime True. It's a bad habit. :)
Moved to #91
