### ISSUE TITLE
Modifier key configuration

### ISSUE THREAD

**Issue by whiteley** [LnL7/nix-darwin#55]
I'd like to add support for modifier key configuration and I'm looking for some input on how to go about it.

The first challenge is that the configuration is stored per keyboard which is identified by the USB vendor and product IDs. This can be somewhat assumed for the internal keyboards on apple laptops since they all have the same vendor ID from what I've found so far. Users might want to configure for other keyboards though, should this require them to provide the IDs? Provide an option for applying to all keyboards by iterating through `ioreg`?

The mapping is the second question. The actual configuration I'm using consists of

```
(
        {
        HIDKeyboardModifierMappingDst = 30064771296;
        HIDKeyboardModifierMappingSrc = 30064771129;
    }
)
```

which translates to mapping caps lock to control but is rather opaque. The values required are described in https://developer.apple.com/library/content/technotes/tn2450/_index.html and system preferences exposes 4 keys with 5 options each. Would it be best to have the user provide the raw values? Have the options more closely follow the system preferences dialog and hide the numeric values from the end user?

I'm interested in working up a PR for this myself but am inexperienced enough with nix to feel I need some pointers to do it well. Any info and suggestions appreciated!

**Comment by cbarrett** [comment]
@whiteley 👋 Have you seen [Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements)? Would be more than happy to hack on packaging it; I'm [a happy user](https://github.com/cbarrett/etc/tree/master/karabiner) myself and would love to have my config managed by Nix.

**Comment by LnL7** [comment]
This would be very cool! You can add an option with the literal mappings and provide some helpers that extend the mappings with specific mappings, hiding the details for common things.

This probably won't work, but hopefully you get the idea:

```nix
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.system.keyboard;
in

{
  config = {
    system.keyboard.enableKeyMapping = mkOption {
      type = types.bool;
      default = false;
    };

    system.keyboard.remapAToB = mkOption {
      type = types.bool;
      default = false;
    };

    system.keyboard.userKeyMapping = mkOption {
      type = types.listOf (types.attrsOf types.int);
      default = [];
    };
  };

  options = {

    system.keyboard.enableKeyMapping = mkDefault (cfg.userKeyMapping != []);

    system.keyboard.userKeyMapping = mkMerge [
      (mkIf cfg.remapAToB [{ HIDKeyboardModifierMappingSrc = 30064771076; HIDKeyboardModifierMappingDst = 30064771077; }])
      # ...
    ];

    system.activationScripts.keyboard.text = optionalString cfg.enableKeyMapping ''
      # Configuring keyboard
      echo "remapping keys..." >&2
      hidutil property --set '{"UserKeyMapping":${builtins.toJSON cfg.userKeyMapping}}'
    '';

  };
}
```

**Comment by LnL7** [comment]
Whoa, this actually just works. 😃

**Comment by LnL7** [comment]
Adding options for more bindings should be pretty straightforward when you figure out how to convert the numbers in the table.

@whiteley Thank you for the info!
