### ISSUE TITLE
SSH `authorized_keys`

### ISSUE THREAD

**Issue by srid** [LnL7/nix-darwin#562]
What is the recommended way to specify `~/.ssh/authorized_keys` in Nix using nix-darwin?

ssh_known_hosts is global: https://github.com/LnL7/nix-darwin/blob/44da835ac40dab5fd231298b59d83487382d2fab/modules/programs/ssh/default.nix#L84

Is home-manager the only way?

**Comment by jamiesteven** [comment]
@srid Did you happen to find a way to do this? When I attempt to create the authorized_keys file using Home Manager like so:

```
home.file."/.ssh/authorized_keys".text = ''
    <keys go here>
  '';
```

~/.ssh/authorized_keys becomes a symlink to the a file in the store with less restrictive permissions than needed for OpenSSH to use it, unless you disable openssh StrictModes in /etc/ssh/sshd_config.

https://man.openbsd.org/sshd -- See StrictModes
https://unix.stackexchange.com/a/152590

**Comment by srid** [comment]
Duplicate of #152
