### ISSUE TITLE
System activation service possible race condition

### ISSUE THREAD

**Issue by choco** [LnL7/nix-darwin#563]
Hello, thanks for the great project. 
I was debugging some services that I wrote for myself where the executable was in the nix-store but the service itself was executed before the `/nix` volume is mounted. (the service than goes into a "penalty-box" and doesn't run until the user manually unloads it and loads it back) and saw that the service for system activation suffers from the same possible race condition `https://github.com/LnL7/nix-darwin/blob/a7492a8c76dcc702d0a65cd820a5f9baa8702684/modules/services/activate-system/default.nix#L22`.
Is there some reason why that one isn't guarded with a `wait4path`?

**Comment by Enzime** [comment]
Fixed by #1052
