### ISSUE TITLE
~/Applications still symlinked to store

### ISSUE THREAD

**Issue by higatowa** [LnL7/nix-darwin#565]
As far as I understood after the merge of #470 `~/Applications` should contain `Nix Apps` with the system-wide apps. In my case even after

`nix-channel --update darwin`

the entire `Applications` directory is symlinked to the store:

```
ls -lah Applications

lrwxr-xr-x  1 root  staff    76B Nov  9 00:23 Applications -> /nix/store/m8jman7mvpdikjrls5jsn4wgk5zy7xrz-system-applications/Applications
```

channel list:
```
nix-channel --list                                                ~
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
```

I'm pretty new to the nix ecosystem so maybe I'm missing something.

**Comment by lockejan** [comment]
> As far as I understood after the merge of #470 `~/Applications` should contain `Nix Apps` with the system-wide apps. In my case even after
> 
> 
> 
> `nix-channel --update darwin`
> 
> 
> 
> the entire `Applications` directory is symlinked to the store:
> 
> 
> 
> ```
> 
> ls -lah Applications
> 
> 
> 
> lrwxr-xr-x  1 root  staff    76B Nov  9 00:23 Applications -> /nix/store/m8jman7mvpdikjrls5jsn4wgk5zy7xrz-system-applications/Applications
> 
> ```
> 
> 
> 
> channel list:
> 
> ```
> 
> nix-channel --list                                                ~
> 
> darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
> 
> home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
> 
> ```
> 
> 
> 
> 
> 
> I'm pretty new to the nix ecosystem so maybe I'm missing something.
> 
> 

Nix-Darwin is a bit special when it comes to channels. Check if you have a Darwin channel under root. If so you want to update that instead and test again. 

sudo -i nix-channel ...

**Comment by higatowa** [comment]
```
sudo -i nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```
this is the only channel I have under root

**Comment by lockejan** [comment]
Ah, I see. I still haven't switched to flakes, which is why I keep using the old way with channels. If you are using flakes you are probably defining the channels directly in your flake file as an input. So my suggestion is probably irrelevant to your situation. Sorry.

**Comment by higatowa** [comment]
Ok,  solved the issue executing `nix flake update` in the directory where the flake is contained. Thanks for the help.
