### ISSUE TITLE
nix-darwin's configuration directory differs from Nixpkgs

### ISSUE THREAD

**Issue by Freed-Wu** [LnL7/nix-darwin#573]
In nix-darwin:
> Configuration lives in ~/.nixpkgs/darwin-configuration.nix

In [nix-pkgs](https://nixos.org/manual/nixpkgs/stable):
> A user’s nixpkgs configuration is stored in a user-specific configuration file located at ~/.config/nixpkgs/config.nix. For example:

Why nix-darwin's config is not `~/.config/nixpkgs`?

**Comment by Freed-Wu** [comment]
Default is defined at <https://github.com/LnL7/nix-darwin/blob/master/modules/environment/default.nix#L71>. Any thought to change it?

**Comment by Enzime** [comment]
The plan is to change the default directory to `/etc/nix-darwin` as nix-darwin configures the entire system not just a singular user

See #1203
