### ISSUE TITLE
Set executable permission on etc files?

### ISSUE THREAD

**Issue by corps** [LnL7/nix-darwin#59]
So I got chunkwm working with nix-darwin thanks to the provided module, but I had one hickup.

https://github.com/LnL7/nix-darwin/blob/master/modules/services/chunkwm.nix#L115

The rc file that is created uses the nix-darwin etc environment hook.  However, these files are always created with 444 (read only) with the `writeText` mechanism that backs it.  Unfortunately, chunkwm tries to execute this file, and fails, causing it to start without actually applying the settings.

I'd write a pull myself but i'm not sure how you feel the solution should look.  Should we just add an `isExecutable` property to the module?  Should it apply to all octets, or just the owner one?

**Comment by LnL7** [comment]
That's kind of odd, but the etc module has an option to provide a derivation rather than use the default writeText implementation.

```nix
{ config, lib, pkgs, ... }:
with lib;
{
    environment.etc."chunkwmrc".source = pkgs.writeScript "etc-chunkwmrc" ''
      chunkc core::plugin_dir ${toString cfg.plugins.dir}
      chunkc core::hotload ${if cfg.hotload then "1" else "0"}
      ...
    '';
}
```

**Comment by LnL7** [comment]
Fixed in https://github.com/LnL7/nix-darwin/commit/1779e06cd4ba51adbbe898f1bf9f891c4bd9882e
