### ISSUE TITLE
Writing arrays to system defaults

### ISSUE THREAD

**Issue by gshpychka** [LnL7/nix-darwin#590]
Currently, the defaults keys with array (and dict) types cannot be written with `system.defaults.CustomUserPreferences` per https://github.com/LnL7/nix-darwin/blob/3db1d870b04b13411f56ab1a50cd32b001f56433/modules/system/defaults-write.nix#L11:L15

Would it make sense to implement a way to write arrays as well? Sound simple enough, or am I missing something? I might be able to throw together a PR.

**Comment by freddydumont** [comment]
There's a PR from 2020 (#253) open that implements the change with the following line:

```nix
if isList value then "-array ${concatStringsSep " " (map (v: writeValue v)value)}" else
```

Haven't tested it but I guess a PR containing only this change would have a better chance of being merged.
