### ISSUE TITLE
`nix flake show` shows `darwinConfigurations: unknown`

### ISSUE THREAD

**Issue by diktomat** [LnL7/nix-darwin#617]
When using `nix-darwin` in a flake, `nix flake show` doesn't know how to display darwin configurations, and instead shows unknown. Compared with nixos configurations:

```nix
{
  outputs = {darwin, nixpkgs}: {
    darwinConfigurations.<hostname> = darwin.lib.darwinSystem {<omitted>};
    nixosConfigurations.<hostname> = nixpkgs.lib.nixosSystem {<omitted>};
  }
}
```
```
❯ nix flake show
git+file:///foo
├───darwinConfigurations: unknown
└───nixosConfigurations
    └───<hostname>: NixOS configuration
```

**Comment by reckenrode** [comment]
This is a Nix limitation. `nix flake show` only knows how to display certain outputs (e.g., `packages` and `nixosConfigurations`), and it’s not currently extensible.

There is an open issue (NixOS/nix#6454) about adding extensibility, but a desired was expressed for a different approach than the one proposed.

**Comment by roberth** [comment]
Regardless of plans for genericity (thanks @reckenrode for linking) this specific case has been solved in
 - https://github.com/NixOS/nix/pull/7606
