### ISSUE TITLE
powerline package deployment generated error install: cannot create directory '/var/empty/Library': Operation not permitted 

### ISSUE THREAD

**Issue by mudrii** [LnL7/nix-darwin#633]
I have encountered a veriyinteresting problem

If you try to deploy powerline package 

```nix
packages = with pkgs; [
      powerline
];
```

OR

```sh
(
        python39.withPackages (
          ps: with ps; [
            powerline
          ]
        )
      )
```

During `darwin-rebuild switch --flake`

getting a strange error

```sh
install: cannot create directory '/var/empty/Library': Operation not permitted
```

To reproduce just add powerline to your packages and run darwin-rebuild

**Comment by Fuzen-py** [comment]
Did you set `home.homeDirectory` ?

**Comment by Enzime** [comment]
Closing this issue, please comment if you're still having issues
