### ISSUE TITLE
Karabiner-elements refuses to list any devices

### ISSUE THREAD

**Issue by disbolog** [LnL7/nix-darwin#639]
I'm on Intel Mac with the following system:
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"darwin"`
 - nixpkgs: `/nix/store/22z4n4mxs2vz3l3lg41dz3mgnq1d4wxs-source`
```
The darwin-configuration.nix is the following bare minimum:
```nix
{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs;
    [
      vim
      tree
      karabiner-elements
    ];
  services.nix-daemon.enable = true;
  programs.zsh.enable = true;
  system.stateVersion = 4;
}
```
The karabiner-elements refuses to pick up any devices as evident from the devices tab, and I am not sure how to proceed from this.

**Comment by Enzime** [comment]
Did you try the option:

```
services.karabiner-elements.enable = true;
```

With this option, you shouldn't need to add `karabiner-elements` to your `environment.systemPackages`

**Comment by Enzime** [comment]
I'm gonna close this issue, please comment again if you're still having issues
