### ISSUE TITLE
Hitting `ln: failed to create symbolic link '/run': Read-only file system` during installation

### ISSUE THREAD

**Issue by nickgerace** [LnL7/nix-darwin#648]
This appears to be related to resolved issue #378.

## System details

- Nix version: 2.13.3
- macOS version: 13.0 (22A380) aarch64

## What happened

I executed the following today (2 May 2023) to install `nix-darwin`...

```bash
nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
./result/bin/darwin-installer
```

This is the output of the end of the script, from the last interactive prompt to the error(s):

```
Would you like to create /run? [y/n] y
setting up /run via /etc/synthetic.conf...
warning: apfs.util failed to symlink /run
setting up /run...
ln: failed to create symbolic link '/run': Read-only file system
```

EDIT: went to the manual instructions and ran this...

```bash
echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf
/System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -B
/System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t
```

...then hit the following error...

```
failed to stitch firmlinks and/or create synthetics for root volume (c00d) ..
```

Going to try some more things in the meantime.

## What I expected to happen

I expected the installation instructions to work "out of the box". I am happy to pursue any workarounds needed to get `nix-darwin` working and provide more details, as needed.

**Comment by robbins** [comment]
Running the apfs.util commands with sudo resolved this issue for me.

**Comment by andrewcrook** [comment]
> I expected the installation instructions to work "out of the box”.

They did for me with /run yesterday and several other days before that.
However, I have noticed inconsistencies between installations I am not sure why.

Could it be something was left from a previous installation?

**Comment by nickgerace** [comment]
Using `sudo` worked for me as well just for those commands. I installed Nix from [Zero to Nix](https://zero-to-nix.com/start/install). That might be relevant here.

**Comment by bestlem** [comment]
I am using ZeroToNix as well.
The synthetic.conf was created but got the link error.

The second apfs util command seemed to work with so do but the first


`/System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -B`

fails with 
`/System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util: illegal option -- B`

I am on Ventura 13.4

**Comment by Enzime** [comment]
What’s the contents of your `/etc/synthetic.conf`?

**Comment by winitzki** [comment]
It is created automatically, and it already had the last line `run  private/var/run`:

```
% cat /etc/synthetic.conf
nix
run     private/var/run
```

**Comment by laughingman-hass** [comment]
I'm also seeing this on a new install on a Mac Mini, macOS Sequoia 15.4.1.
I've installed Nix with `sh <(curl -L https://releases.nixos.org/nix/nix-2.28.0/install) --daemon --yes`
Trying to build and switch to this flake https://github.com/ghosts-of-razgriz/dotfiles-nix-darwin/tree/v2.2

contents of `/etc/synthetic.conf`
```
% cat /etc/synthetic.conf
nix
run     private/var/run
```
