### ISSUE TITLE
flakes: error when using `nix-darwin` input from registry

### ISSUE THREAD

**Issue by edrex** [LnL7/nix-darwin#649]
Hi, I'm just getting my first nix-darwin host set up using flakes and flake-parts, and I hit a little snag.

The flake registry entry is [called]([modules/system/flake-overrides.nix](https://github.com/LnL7/nix-darwin/blob/master/modules/system/flake-overrides.nix)) `nix-darwin`, while [modules/system/flake-overrides.nix](https://github.com/LnL7/nix-darwin/blob/master/modules/system/flake-overrides.nix) assumes the nix-darwin input is named `darwin` (along with all the example code I've seen). This results in the following error when omitting the explicit input from the flake:

```
error: attribute 'darwin' missing

       at /nix/store/pkwvghi6y6abzdfk4yfyxayixs5wzq77-source/modules/system/flake-overrides.nix:5:4:

            4|
            5| let
             |    ^
            6|   inherit (inputs) darwin nixpkgs;
```

Workaround:

```
    inputs.nix-darwin.inputs.nixpkgs.follows = "nixpkgs"; # this line included just for context
    inputs.darwin.follows = "nix-darwin";
```

I think the registry entry just needs to be renamed. Without context, `nix-darwin` does seem preferable since `darwin` sounds like the actual darwin codebase, but having the registry entry follow the established precedent seems like the right choice.

Reporting here rather than there first because the registry is a self-service commons, and it will affect this repo.

**Comment by emilazy** [comment]
This should be fixed by https://github.com/LnL7/nix-darwin/pull/723. Changing the flake registry entry is still an option, but it might be better for us to standardize on the `nix-darwin` name instead, as it matches the repository name and what people call the project in practice.
