### ISSUE TITLE
Nix 2.14  /etc symbolic link bug?

### ISSUE THREAD

**Issue by andrewcrook** [LnL7/nix-darwin#651]
This is a repost of #646  but only has the relevant information 

Every time I tried to setup nix-darwin on `nix 2.14` it will not create the `/etc/static` symbolic links properly as you can see below.
Using `nix 2.13` has solved this issue. 
The issue seems to be with nix 2.14 and the  `./result/action` script  (which I think is also used by `darwin-rebuild`) 

```
> tree /etc/static/   
/etc/static/
└── etc -> /nix/store/1xk4ypir42279hkgxy8rd34gpd7hpq4d-etc/etc
```

```
> tree 
/etc/static/etc
├── bashrc -> /nix/store/q5jjg7vp22fsg1bpnxsppv5mp9lan13b-etc-bashrc
├── nix
│   ├── nix.conf -> /nix/store/91j4y88z6al6cdl6bdzxj0jfi4ydxqkw-nix.conf
│   └── registry.json -> /nix/store/zvsi8bmc6zf3jbzg8wm0iiz84563vy64-etc-registry.json
├── ssh
│   └── ssh_known_hosts -> /nix/store/5y45aahllnwyyx1l6kpfmwvbskk2xwmj-etc-ssh_known_hosts
├── ssl
│   └── certs
│       └── ca-certificates.crt -> /nix/store/554gcphg8qxm45abgz3059kkk9bwwdqi-ca-certificates.crt
├── zprofile -> /nix/store/rb0xxj1akrgr6xad9bs0kcn9mp0ny9bg-etc-zprofile
├── zshenv -> /nix/store/lfrq5p0bwhxkmf1w30l2202xlfmnxabw-etc-zshenv
└── zshrc -> /nix/store/lrz98x881l75d82rr64wc9xjwv3jf5j4-etc-zshrc
```

I would also get `/etc/etc`

**Comment by gshpychka** [comment]
Same here with 2.15

**Comment by andrewcrook** [comment]
> Same here with 2.15

Added to subject

**Comment by gshpychka** [comment]
Actually, I was wrong, apologies for the confusion. `/etc/static` contents are as expected for me, no nested `etc` folder.

**Comment by bestlem** [comment]
I get no /etc/static with nix 2.15
