### ISSUE TITLE
Overlay for installing nix-darwin

### ISSUE THREAD

**Issue by pjan** [LnL7/nix-darwin#66]
[home-manager](https://github.com/rycee/home-manager) provides an overlay defined in the repository to have nix install it. I think that's pretty neat, and it would be great if a similar option would be provided here.

**Comment by LnL7** [comment]
I don't really see how an overlay is useful. But moving the installation functionality to activation and replacing the bootstrap script with a `builtins.fetchTarball` is a cool idea.

**Comment by LnL7** [comment]
I made a bunch of changes to the installer https://github.com/LnL7/nix-darwin#install and even added an uninstaller. The install/uninstall flow is also tested on travis. https://github.com/LnL7/nix-darwin/blob/4747989bc6f2b2f97233bb094adc1b39dea9ec97/.travis.yml#L9-L11
