### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by AleCandido** [LnL7/nix-darwin#666]
Running the installer as described in the README results in an infinite recursion error.

```sh
~ % nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
error:
       … in the left operand of the update (//) operator

         at /nix/store/sq0gp79s1kjhf6ilxfkxsqxasi5znh1c-nixpkgs/nixpkgs/lib/fixed-points.nix:69:64:

           68|   #
           69|   extends = f: rattrs: self: let super = rattrs self; in super // f self super;
             |                                                                ^
           70|

       … in the left operand of the update (//) operator

         at /nix/store/sq0gp79s1kjhf6ilxfkxsqxasi5znh1c-nixpkgs/nixpkgs/lib/fixed-points.nix:69:64:

           68|   #
           69|   extends = f: rattrs: self: let super = rattrs self; in super // f self super;
             |                                                                ^
           70|

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: infinite recursion encountered

       at «none»:0: (source not available)
```

I've just reinstalled `nix` from scratch, and this is the very first command I'm issuing with it.

```sh
~ % nix --version
nix (Nix) 2.15.0
~ % uname -a
Darwin --- 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:43 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8112 arm64
```

**Comment by bestlem** [comment]
I get this too - I have been fiddling uninstalling and installing nix over the last few days and this did work when I first tried it and the started failing so I suspect something in the commits for 16th or 17th May - or possibly 15th. I am using Ventura 13.4 which I also installed in the last few days so that might be the cause.

    ~ nix --version
    nix (Nix) 2.15.0
    ~ uname -a
    Darwin mini20 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103 arm64

**Comment by AleCandido** [comment]
I opened also an issue on `nixpkgs`, but (as written there) I suspect this to be actually a `nix` problem, or something like that.

So the current relevant issue is:
https://github.com/NixOS/nixpkgs/issues/232785
but I wonder if it is worth to open a new one (I still hope some maintainer will check it and transfer, but in a few days I will open by myself).

**Comment by AleCandido** [comment]
https://github.com/NixOS/nix/issues/8404#issuecomment-1637904635
