### ISSUE TITLE
Default prompt walters interferes with zsh printing output that doesn't contain new line.

### ISSUE THREAD

**Issue by takeda** [LnL7/nix-darwin#667]
So this looks like this has been forever (according to git blame it's been at least for 7 years).

The zsh has a mechanism where if output doesn't end with a new line, it will add it automatically and mark that with inverted percent sign:

https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol

The Walters default prompt which is defined if the user doesn't change `promgrams.zsh.promptInit` has a fancy way of showing current directory on the right side of the screen. This unfortunately interferes with the former and causes the last line that has no new line at the end to be covered by the prompt.

This happens even if one installs custom prompts, either via oh-my-zsh or via starship.

Since I use a custom prompt, so for me the solution to this problem was to set `promgrams.zsh.promptInit` to empty string. I think setting `prompt_cr` and `prompt_sp` options in zsh could also be solution if somebody wants to use prompt like Walters, but then setting prompt like Walters might have other unintended consequences for somebody who uses different prompt anyway.

**Comment by Enzime** [comment]
Closed by #954
