### ISSUE TITLE
Flake: When `inputs` are in `specialArgs` the wrong nixpkgs is used

### ISSUE THREAD

**Issue by dacioromero** [LnL7/nix-darwin#669]
https://github.com/LnL7/nix-darwin/issues/365#issuecomment-1445300112
https://github.com/LnL7/nix-darwin/issues/365#issuecomment-1490761162

---

I also ran into the same oddity as @n8henrie and I thought it deserved a new issue.

I pass all of my Flake `inputs` to `specialArgs` as `{ inherit inputs }`. This ended up meaning even when I attempted to have nix-darwin's `nixpkgs` input follow my own `nixpkgs-unstable` input (nixos-22.11) it would still use my `nixpkgs` input (nixos-unstable).

In NixOS `_module.args.pkgs` is actually set by the nixpkgs module (https://github.com/NixOS/nixpkgs/blob/c2f6e54e7ffd06d8976846d1dfd94df68912cb17/nixos/modules/misc/nixpkgs.nix#L339-L341) and the line linked before (https://github.com/NixOS/nixpkgs/blob/463643afa8b70b153ef1728493afce53817514ff/nixos/lib/eval-config.nix#L57) is for if you provide `pkgs` to `nixosSystem`.

I'm not sure what the best solution is, but my gut feeling is that the inputs of nix-darwin's flake could be `_inputs` as to not collide with user-provided inputs.

**Comment by dacioromero** [comment]
Related problem I've had is that https://github.com/LnL7/nix-darwin/blob/master/modules/system/flake-overrides.nix will error if the name of my input for this repo is just `darwin` instead of `nix-darwin`.

**Comment by n8henrie** [comment]
Hmmm, I'm AFK at the moment but the merged PR mentions it is a breaking change.

Is there a summary somewhere of what changes may be required, and under what conditions? Based on my quick-and-dirty read of the PR, it looks like this brings nix-darwin in line with NixOS with regards to handling specialArgs. Does that sound right?

**Comment by emilazy** [comment]
Nothing should break unless you were importing `eval-config.nix` directly (and you'd know if you were). Any working configuration used via `darwin-rebuild`, flakes or not, should act as before, modulo some potential very minor changes (different/missing Nixpkgs revisions in system configuration labels and the manual). The main change is an overhaul of how `pkgs` and `lib` are constructed and passed to fix some nasty bugs, but as a side effect nix-darwin now doesn't care what your `inputs` are at all.

**Comment by n8henrie** [comment]
Thanks for clarification.
