### ISSUE TITLE
Doc: Introduction

### ISSUE THREAD

**Issue by angerman** [LnL7/nix-darwin#68]
I believe the `README.md` could use an introduction section that answers the following questions:
- how does `nix-darwin` relate to https://nixos.org/nix/download.html
- what the provided `darwin-rebuild` and `darwin-option` tools are and how they relate to `nixos-rebuild`.

The Install section should probably say, that you want to install nixos via https://nixos.org/nix/download.html first?

Also, I guess a note that `bash` is required for the script to work, and there is no `zsh` support?

**Comment by angerman** [comment]
I've changed the `/etc/static/bashrc` into `/etc/static/zshrc` with minor modifications: https://gist.github.com/angerman/fe35f73071a25bee66e53c0c4a30643a, but I'm not sure where such a change would need to be pushed to. Also as it says it's auto generated, I'm afraid I would need to find the generator.

**Comment by angerman** [comment]
Maybe the right thing would be to just say the only `bash` is a supported shell?

**Comment by LnL7** [comment]
I agree, it's currently just a dump of information without any context.

Both zsh and fish are supported, but the installer and default configuration don't enable it. See `programs.zsh.enable` and `programs.fish.enable`.
