### ISSUE TITLE
does not provide attribute 'packages.aarch64-darwin.darwinConfigurations.143.system'

### ISSUE THREAD

**Issue by kaihendry** [LnL7/nix-darwin#698]
When I run `darwin-rebuild switch --flake ~/mac-nix/.#` I get this error I've not seen before:

`error: flake 'git+file:///Users/hendry/mac-nix' does not provide attribute 'packages.aarch64-darwin.darwinConfigurations.143.system', 'legacyPackages.aarch64-darwin.darwinConfigurations.143.system' or 'darwinConfigurations.143.system'`

https://github.com/kaihendry/mac-nix/

**Comment by kaihendry** [comment]
Ahhh!

```
❯ hostname
143.180.187.81.in-addr.arpa
```

Can I get nix darwin to set the hostname? I think it's set by DHCP or something atm, dunno why.

**Comment by Enzime** [comment]
Yeah you can https://daiderd.com/nix-darwin/manual/index.html#opt-networking.hostName
