### ISSUE TITLE
Nix was not compiled with libsodium

### ISSUE THREAD

**Issue by pkdahl** [LnL7/nix-darwin#7]
After installing nix-darwin I get the error message below when trying to
- `darwin-rebuild build`, or
- install a package with `nix-env`

```
download-from-binary-cache.pl: Nix was not compiled with libsodium, required for signed binary cache support at /nix/store/qfwm0b5qkr8v8gsv9dh2z3arky9p1myg-nix-1.11.5/lib/perl5/site_perl/5.22.2/darwin-2level/Nix/Manifest.pm line 479.
error: substituter ‘download-from-binary-cache.pl’ died unexpectedly
```

I got this error message earlier today and after that I
- removed `/nix`, `/etc/nix` and `/etc/static`
- installed Nix again
- setup nix-darwin

The system was up again, but after making a change to my darwin-configuration.nix I tried `darwin-rebuild build` and got the above error message again. I also tried to install something with `nix-env`, but got the above error message again.

To see if it is an issue with nix and not nix-darwin, I again removed `/nix`, `/etc/nix` and `/etc/static` and did a new installation of Nix. I confirmed that I could install something with `nix-env`. Then setup nix-darwin. The system is up again, but now if try to install something with `nix-env` I get the above error message again.

I hope the information I have provided is helpful. I'm not experienced with Nix at all.

Thanks for making this! Please let me know if I can be of any assistance :)

**Comment by LnL7** [comment]
This doesn't look good 🙁. I have a feeling this might happen when `SSL_CERT_FILE` is not configured properly.
What configuration did you use?

**Comment by pkdahl** [comment]
Doing `echo $SSL_CERT_FILE` says `/Users/pkdahl/.nix-profile/etc/ssl/certs/ca-bundle.crt`

**Comment by LnL7** [comment]
And I assume the file exists, what version of nix are you using? `nix-env --version`

**Comment by pkdahl** [comment]
I can confirm that the certfile exists. Nix version is 1.11.5.

**Comment by LnL7** [comment]
Let me check aparently I'm still on `1.11.4`, I'm thinking it might be because of this in `nix.conf`

```
binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
signed-binary-caches = *
```

**Comment by LnL7** [comment]
I did find a [bug](https://github.com/LnL7/nix-darwin/commit/e925a2d50e2d5dd26d1f8d9335d91fa6cf218265) with `nix.conf` caused by the `build-users-group` option, but I'm pretty sure that's unrelated.

**Comment by yurrriq** [comment]
I'm having the same issue sporadically and my workaround for now was to add this to my `darwin-configuration.nix`:

```nix
{ config, lib, pkgs, ... }:
{
  # ...
  nix.requireSignedBinaryCaches = false;
}
```

I've also had success adding `--option use-binary-caches false` to `nix-*` and `darwin-rebuild` calls, but obviously that's not ideal as you then have to build everything by hand...

**Comment by LnL7** [comment]
@yurrriq is that also with 1.11.5 or are you on another version?

**Comment by yurrriq** [comment]
I'm on `1.11.4`.

**Comment by LnL7** [comment]
I found the cause of this issue with the help from some of the people on `##nix-darwin`. It turns out that the version of nix in the installer does not have `libsodium` support, while the one in nixpkgs does, knowing that makes the issue here pretty obvious.
Installing the one from nixpkgs after using the installer will fix this:

```
nix-env -f -iA nixpkgs.nix
```

**Comment by yurrriq** [comment]
Awesome, thanks! I'll try it out later.

**Comment by LnL7** [comment]
I also added a not about this to the installation instructions.

**Comment by yurrriq** [comment]
Seems to be working for me.

**Comment by pkdahl** [comment]
Seems to be working for me too. Thanks!
