### ISSUE TITLE
Github pages doc site broken

### ISSUE THREAD

**Issue by vedkothavade** [LnL7/nix-darwin#709]
[The doc site](https://daiderd.com/nix-darwin/manual/index.html#sec-options) now returns the error `The nix-darwin documentation now requires nixpkgs 23.05 to build.`

I'd guess the Github Action which is used for the site was not correctly updated in #707, but not familiar enough with Nix or Github Actions to be sure.

For anyone else looking for an alternative for the time being, as the README says, you can use `man 5 configuration.nix`

**Comment by emilazy** [comment]
Yeah I missed https://github.com/LnL7/nix-darwin/blob/ace0ef2a26bc428e768a5926eae95a63cfcf8b52/.github/workflows/update-manual.yml, whoops. I'll send a PR later if nobody else gets to it first.
