### ISSUE TITLE
rebuilding causes screen to go black and reboot into an empty OS session

### ISSUE THREAD

**Issue by JoshuaBatty** [LnL7/nix-darwin#720]
Hey guys, I'm trying to get everything set up for the first time on my new M2 machine. 

When I run `darwin-rebuild switch --flake ~/src/system-config/.#`  my whole graphical interface shutsdown and reboots with none of the previous programs running. 

Running `nix-channel --update` also causes the same problem to occur. Running `nix build --show-trace` also does the same. 

See below for some context. Has anyone seen this error happen before or can point me what to debug next. I've been trying to find some answers for a few days now and completely lost. 

Thanks in advance!

```zsh
josh@Josh> echo $NIX_PATH                                                                              
/Users/josh/.nix-defexpr/channels:darwin-config=/Users/josh/.nixpkgs/darwin-configuration.nix:/nix/var/nix/profiles/per-user/root/channels

josh@Josh> which nix                                                                                   
/nix/var/nix/profiles/default/bin/nix

josh@Josh> nix-channel --list                                                                          
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
home-manager https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

**Comment by LnL7** [comment]
This reminds me of the behaviour caused by a kernel bug a few years ago.
Did you add the admin user to the `nixbld` group by any chance? You can check with `id -Gn $USER`.

**Comment by JoshuaBatty** [comment]
I ended up wiping my whole computer and starting again with a fresh OS. Everything worked perfectly next time around, not sure what happened to my system the first time but seemed like there was no coming back from it. Easier to just wipe and start again. Will close this. Thanks.
