### ISSUE TITLE
yabai extraConfig can only be set once

### ISSUE THREAD

**Issue by yusefnapora** [LnL7/nix-darwin#729]
Hey, first, nix-darwin is the business, and I really appreciate all the work that went into it!

I'm trying to set up my yabai config using two "feature" `.nix` files, one for my base config, and one for the scripting additions, which require SIP to be partially disabled.

I'd like to set the `extraConfig` option in both configs, but I get the error:

```
error: The option `services.yabai.extraConfig' has conflicting definition values:
       - In `/nix/store/c6a3c4vm09083a5vf4qr4zjf8gblnvdf-source/darwin/features/yabai-scripting-additions.nix':
           ''
             yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
             sudo yabai --load-sa
           ''
       - In `/nix/store/c6a3c4vm09083a5vf4qr4zjf8gblnvdf-source/darwin/features/yabai.nix':
           ''
             yabai -m rule --add app='System Settings' manage=off
             yabai -m rule --add app='Zoom' manage=off
             yabai -m rule --add app='zoom.us' manage=off
             yabai -m config layout bsp
           ''
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```

This could be solved by setting the option type to `types.lines` instead of `types.str`, which would merge the definitions together instead of flagging them as conflicting. 

I'd be happy to open a quick PR if you'd be open to the change. Thanks :)

**Comment by Enzime** [comment]
That would be great if you could make a PR
