### ISSUE TITLE
`nix.linux-builder` needs a `maxJobs` configuration

### ISSUE THREAD

**Issue by lilyball** [LnL7/nix-darwin#751]
The new `nix.linux-builder` module is great, but it has no way to customize the `nix.buildMachines` entry. In particular, I can't set the `maxJobs` key, which means it defaults to 1 job at a time. This is rather unfortunate as I'm configuring my builder to use multiple cores and so I want to be able to dispatch multiple jobs at a time to it. I don't know if there are any other knobs on the builder that should be exposed for configuration, but `maxJobs` definitely should be.

Incidentally, speaking of the builder, it doesn't set `protocol`, and so it defaults to `ssh`; perhaps it should be setting `protocol = "ssh-ng"` as well?

**Comment by lilyball** [comment]
I'm also thinking that perhaps `hostPort` needs to be exposed as a configuration option, given that it's currently hard-coded in the SSH config file.

**Comment by Enzime** [comment]
PRs are definitely welcome, I just wanted to keep the initial PR simple so I didn't add many options for customizing the builder.

According to https://github.com/NixOS/nix/issues/4665, `ssh-ng://` doesn't support `builders-use-substitutes` which we currently use in the `linux-builder` module, although it would probably be fine to disable this.

**Comment by lilyball** [comment]
That issue needs to be updated, `builders-use-substitutes` was fixed for `ssh-ng` back in version 2.4. I don't know right now what the tradeoff is between `ssh` and `ssh-ng`, just that the latter is the modern version and I would hope at this point it's an improvement to use.

In any case, the `maxJobs` thing is definitely important. It took me far too long to build my updated raspberry pi system yesterday with the default of 1 job.

**Comment by lilyball** [comment]
PR submitted. I only included `maxJobs` as that's the most important and I personally am fine with the default 31022 port, but it's probably a good idea for someone to add configuration for the port as well.
