### ISSUE TITLE
`fonts.fonts` has been renamed to `fonts.packages` on NixOS, consider changing for nix-darwin as well

### ISSUE THREAD

**Issue by ToyVo** [LnL7/nix-darwin#752]
Here is the PR that made the change in nixpkgs: https://github.com/NixOS/nixpkgs/pull/244332

**Comment by Enzime** [comment]
Thanks for the issue, PRs are welcome as we aim to match NixOS's interface as much as we can.

However, we might wait for #727 before merging it to reduce the amount of refactoring necessary.

**Comment by emilazy** [comment]
Renaming an option is pretty easy, I don't think we need to wait on branches for that given we already liberally use `mkRenamedOptionModule`.

However, this might be a good time to tackle https://github.com/LnL7/nix-darwin/issues/722. `fonts.fonts` could throw an error explaining to use `fonts.packages` and that fonts left in `/Library/Fonts` will need manual cleanup, and `fonts.packages` could use the new implementation. I already have an implementation of the latter so I might look into doing this soon.

**Comment by marcusramberg** [comment]
Given that #754 seems to have stalled, maybe a simpler pr that only renames the option would be a start?

**Comment by ChaosInTheCRD** [comment]
Is there any progress on this? Just hit this issue after updating my config on my NixOS machine 😊
