### ISSUE TITLE
configure homebrew packages with home-manager

### ISSUE THREAD

**Issue by tnxz** [LnL7/nix-darwin#756]
I am looking for a way where i can configure homebrew installed packages with home-manager

say, chromium in home-manager config 
[programs.chromium.package](https://nix-community.github.io/home-manager/options.html#opt-programs.chromium.package) = homebrew.chromium

is there a workaround to get this functionality

**Comment by azuwis** [comment]
You can provider a fake package to home-manager:

```
programs.chromium.enable = true;
programs.chromium.package = pkgs.runCommand "chromium-0.0.0" { } "mkdir $out";
```

And use nix-darwin to manage homebrew casks:
```
homebrew.enable = true;
homebrew.casks = [ "chromium" ];
```

**Comment by tnxz** [comment]
let me give it a try and get back to you

**Comment by tnxz** [comment]
tried it with brave browser but doesnt seem to work

**Comment by azuwis** [comment]
Use `programs.brave` for brave browser.

**Comment by tnxz** [comment]
yes thats what i used with all instances of chromium to brave in your code with a ublock extension, but no luck.

**Comment by tnxz** [comment]
moved on, using a brave overlay
