### ISSUE TITLE
Brewfile.drv error after upgrading

### ISSUE THREAD

**Issue by gil0mendes** [LnL7/nix-darwin#759]
Hi people,

After upgrading nix and run `flakeup` I'm getting the following error:

```
error: a 'aarch64-darwin' with features {} is required to build '/nix/store/zb7z6b71k1446hwgrmk0p91csxjhwq4q-Brewfile.drv', but I am a 'x86_64-darwin' with features {benchmark, big-parallel, nixos-test}
```

Anyone already seen this and knows a way to get around?

This is my system info:

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(gil0mendes): `""`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by emilazy** [comment]
Sounds like what you'd expect if you were trying to build an `aarch64-darwin` system on `x86_64-darwin`. Can you share any of your configuration, especially around your `flake.nix`/`darwin-configuration.nix` and any Homebrew-related options?

**Comment by gil0mendes** [comment]
Hi @emilazy, thanks for trying to help me out.

Here is the [repo with my dotfiles]( https://github.com/gil0mendes/dotfiles/blob/master/flake.nix).

**Comment by emilazy** [comment]
Thanks for the pointer! I ran `nix flake update` on your repository and made the following change (to deal with the since-reverted but not yet in channels https://github.com/NixOS/nixpkgs/pull/247848):

```diff
diff --git a/modules/darwin/users.nix b/modules/darwin/users.nix
index 9ff8ff3..9a27e6b 100644
--- a/modules/darwin/users.nix
+++ b/modules/darwin/users.nix
@@ -7,19 +7,19 @@ in
 {
   options.users.primaryUser = {
     username = mkOption {
-      type = with types; nullOr string;
+      type = with types; nullOr str;
       default = null;
     };
     fullName = mkOption {
-      type = with types; nullOr string;
+      type = with types; nullOr str;
       default = null;
     };
     email = mkOption {
-      type = with types; nullOr string;
+      type = with types; nullOr str;
       default = null;
     };
     nixConfigDirectory = mkOption {
-      type = with types; nullOr string;
+      type = with types; nullOr str;
       default = null;
     };
   };
```

I was able to build the `pmbp` and `work` configurations on my Intel machine. Are you sure you're not trying to build `g0m`, which is an AArch64 configuration, on an x86-64 machine? (`g0m` itself seems to be broken because of `emacsMacport` wanting to use an old LLVM that doesn't work on AArch64; not sure why I'm getting a different error to you.)

**Comment by gil0mendes** [comment]
OMG! 🤣 🤦🏾  Now I'm a little embarrassed 😅 I was so used to running the command on that machine that I simply switched names 😬

I really appreciated your help and for going one step forward and changing the types 🤗 

I'll buy you a coffee via GitHub sponsor ☕️ 😊

**Comment by emilazy** [comment]
Glad I could help :)

FWIW, if you name your `darwinConfigurations.*` attributes after your system hostnames, then `darwin-rebuild switch --flake /path/to/flake` will select the correct one automatically.
