### ISSUE TITLE
Can not darwin-rebuild after channel --update

### ISSUE THREAD

**Issue by zgagnon** [LnL7/nix-darwin#766]
darwin-rebuild switch
building the system configuration...
these 6 derivations will be built:
  /nix/store/10718fg0l978q7mca02a6psk6g8vyv6h-darwin-manual-html.drv
  /nix/store/97dfxchslk8jl2s4ip7cl53gxh8dd12x-darwin-help.drv
  /nix/store/xxbqmc48vz4vkgdj21hdzj12ihkrmmd9-darwin-manpages.drv
  /nix/store/bdrykf60ghcgx95llszf6p1yjailqzaa-system-path.drv
  /nix/store/vy9sm78h8nmqv03zj2q6dpvqczmz2p7r-system-applications.drv
  /nix/store/5qhyjp7gb5k8943y7zdlg4vs2x4jmpxb-darwin-system-23.05pre-git+darwin4.drv
building '/nix/store/xxbqmc48vz4vkgdj21hdzj12ihkrmmd9-darwin-manpages.drv'...
building '/nix/store/10718fg0l978q7mca02a6psk6g8vyv6h-darwin-manual-html.drv'...
usage: nixos-render-docs manual
       [-h]
       {docbook}
       ...
nixos-render-docs manual: error: argument format: invalid choice: 'html' (choose from 'docbook')
error: builder for '/nix/store/10718fg0l978q7mca02a6psk6g8vyv6h-darwin-manual-html.drv' failed with exit code 2;
       last 5 log lines:
       > usage: nixos-render-docs manual
       >        [-h]
       >        {docbook}
       >        ...
       > nixos-render-docs manual: error: argument format: invalid choice: 'html' (choose from 'docbook')
       For full logs, run 'nix log /nix/store/10718fg0l978q7mca02a6psk6g8vyv6h-darwin-manual-html.drv'.
error: 1 dependencies of derivation '/nix/store/vy9sm78h8nmqv03zj2q6dpvqczmz2p7r-system-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5qhyjp7gb5k8943y7zdlg4vs2x4jmpxb-darwin-system-23.05pre-git+darwin4.drv' failed to build

**Comment by Enzime** [comment]
Should be fixed by #707
