### ISSUE TITLE
`nix.linux-builder` loses certs after a few days

### ISSUE THREAD

**Issue by lilyball** [LnL7/nix-darwin#768]
I use `nix.linux-builder` and twice now I've had the linux builder lose its SSL certificates. The symptom is a remote build on the builder fails with an SSL error, and if I SSH into the builder I find that the `/etc/ssl/certs` mount has vanished.

I'm pretty sure what's going on is this mount is mapped to a directory located inside of `/tmp`, and macOS will, by default, clean up anything in `/tmp` that hasn't been accessed in 3 days. So I think what's going on is if I don't use the builder for a few days (or possibly this happens if I leave my laptop asleep for several days in a row) the temporary directory being used by the linux builder is deleted, and this causes the mount to vanish.

There's also a sibling directory `xchg` in the temporary directory, I'm not sure what that's for but it's also being set up by `qemu-vm.nix` as a shared directory, and presumably that's vanishing as well. Also a `store.img` file.

I'm not entirely sure what the right solution here is. Perhaps the launchd daemon could simply point `$TMPDIR` at some location that isn't periodically cleaned up, although it would presumably have to then manually clean it up.

**Comment by roberth** [comment]
`xchg` is mostly an artifact of the NixOS test infrastructure. I suppose `linux-builder` could explicitly disable it, or we could leave it in place for transferring files during admin stuff, if anyone needs that.

Regarding the rest of the issue, I believe this logic, such as the choice of `/tmp` is also in `nixpkgs`.

**Comment by ldtjcdrs** [comment]
I see this also:
```
sudo ls -lt /tmp/nix-vm.XXXXXXXXXX
total 1024
-rw-r--r--  1 root  wheel  524288 Sep  8 12:13 store.img
drwxr-xr-x  2 root  wheel      64 Sep  8 12:13 certs
drwxr-xr-x  2 root  wheel      64 Sep  8 12:13 xchg
sudo ls -lt /tmp/nix-vm.XXXXXXXXXX/certs
total 0
```
Copying the system `ca-certificates.crt` file to the VM certs shared directory and then starting a build fixes the issue:
```
cp -L /etc/ssl/certs/ca-certificates.crt  /tmp/nix-vm.XXXXXXXXXX/certs/
```

**Comment by lilyball** [comment]
I just tried recreating the tmp dir (by looking at `ps xaww | grep qemu` to find the actual suffix on the `/tmp/nix-vm.XXXXX` dir) but that didn't work, the mounted dir inside of the builder was still empty. This is presumably because the directory itself had been deleted. So the only workaround for me is still running `sudo launchctl kickstart -k system/org.nixos.linux-builder`.

@roberth 

> Regarding the rest of the issue, I believe this logic, such as the choice of `/tmp` is also in `nixpkgs`.

The `nixpkgs` logic looks like

```bash
      # Create a directory for storing temporary data of the running VM.
      if [ -z "$TMPDIR" ] || [ -z "$USE_TMPDIR" ]; then
          TMPDIR=$(mktemp -d nix-vm.XXXXXXXXXX --tmpdir)
      fi
```

The `mktemp` utility will default to `/tmp` if `$TMPDIR` is unset, but that's it. If `$TMPDIR` is set but `$USE_TMPDIR` is unset, it will use a subdirectory of whatever `$TMPDIR` is set to.

This means nix-darwin can control the location here by setting `$TMPDIR` on the launch daemon (and optionally setting `$USE_TMPDIR` if `$TMPDIR` is already set to a unique location). So the launch daemon could optionally do something like

```nix
let script = pkgs.writeShellScript "linux-builder-start" ''
  export TMPDIR=/run/org.nixos.linux-builder USE_TMPDIR=1
  rm -rf $TMPDIR
  mkdir -p $TMPDIR
  trap "rm -rf $TMPDIR" EXIT
  ${builderWithOverrides}/bin/create-builder
''; in
{
  launchd.daemons.linux-builder = {
    serviceConfig.ProgramArguments = [
      "/bin/sh" "-c"
      "/bin/wait4path /nix/store &amp;&amp; exec ${script}"
    ];
}
```

This way it would use the path `/run/org.nixos.linux-builder` as the mount point, clearing it before launch (and then cleaning it up again after).

I haven't actually tested this myself, although at this point I'm tempted to do this locally.

**Comment by lilyball** [comment]
I've been running with the `/run/org.nixos.linux-builder` approach for 2 weeks now and it's been working fine.

**Comment by roberth** [comment]
@lilyball would you mind opening a PR for this?
