### ISSUE TITLE
What is the correct way to set fish as the user's default shell?

### ISSUE THREAD

**Issue by dstcruz** [LnL7/nix-darwin#779]
After digging around, I'm still not able to get the user's default shell to point to fish. Regardless of what I try, the following command always reports zsh:

```shell
> dscl . -read ~/ UserShell
UserShell: /bin/zsh

> echo $SHELL
/bin/zsh
```

Here are the things I have tried:

* Setting `environment.loginShell = "${pkgs.fish}/bin/fish -l";` after adding `pkgs.fish` to `environment.shells`, following the example provided in `modules/examples/lnl.nix`.
* Setting `environment.loginShell = pkgs.fish;` as I have found user configs in GitHub that are using that, but no dice.
* Setting `programs.fish.enable = true;` as this seems to work for `zsh` but not for `fish` (see #146).
* Setting `users.users.my-user.shell = pkgs.fish;` this seems to do nothing.
* Setting `programs.fish.enable = true;` in my `home-manager` section. Tried this just in case. Does not change `UserShell`. My understanding is that `home-manager` might not be able to set the user's shell as that requires root (??).

At this point, I have to manually use `chsh -s /run/current-system/sw/bin/fish`. If that's what is required it would be nice to have that documented somewhere. None of the `fish` related issues explicitly say that "that's the right way to do it", only that that's what people are using to force the change.

Also, while digging around, it seems that `environments.loginShell` is defined in line 79 of `modules/environment/default.nix`, but I could not find anywhere where it is actually used. Did I miss something?

**Comment by iriscanavan** [comment]
> At this point, I have to manually use `chsh -s /run/current-system/sw/bin/fish`.

I have the same issue, but how would `chsh -s /run/current-system/sw/bin/fish` work here since it's a symlink to the Nix store?

**Comment by ian-h-chamberlain** [comment]
> I have the same issue, but how would `chsh -s /run/current-system/sw/bin/fish` work here since `/run/current-system/sw/bin/fish` a symlink to the Nix store?

This worked for me, I had to manually append `/run/current-system/sw/bin/fish` to `/etc/shells` as well first. I guess the OS doesn't have a problem with symlink shells as long as they actually exist?

**Comment by Enzime** [comment]
Updating `/etc/shells` manually or via `environment.shells` should no longer be necessary since #1118 as long as you set the shell you want to use with `users.users.<user>.shell = pkgs.fish;`
