### ISSUE TITLE
How can I add my user to `wheel` group?

### ISSUE THREAD

**Issue by sukanka** [LnL7/nix-darwin#796]
I noticed that `nix-darwin` created `/run` for me and its group is `wheel`. If I want to run programs (like `mysqld`) as an unprivileged user, I must have write permission to `/run`. 
Thus I have to add my user to the group `wheel`.

I have read [Darwin Configuration Options](https://daiderd.com/nix-darwin/manual/index.html), and the options seem relevant are `users.users.<name>` ( there is no additional group option) and `users.groups.<name>.members`.
I set 
```nix
users.groups.wheel.members=["MY_USERNAME"]; 
```
and run 
```sh
darwin-rebuild switch --flake ~/.config/nix-darwin
```
But `groups` still shows my user does not in group `wheel`.

```
$ sudo ls -al /run                                                            ~
Password:
lrwxr-xr-x 1 root wheel 15 10 22 15:53 /run -> private/var/run
```
```
$ groups                                                                      ~
staff everyone localaccounts _appserverusr admin _appserveradm _lpadmin com.apple.sharepoint.group.1 _appstore _lpoperator _developer _analyticsusers com.apple.access_ftp com.apple.access_screensharing com.apple.access_ssh com.apple.access_remote_ae
```

How can I add my user to the `wheel` group or should the `wheel` group be renamed to `staff`?

Any suggestions are welcome.

**Comment by Enzime** [comment]
I would suggest using `sudo` to create the subfolder inside `/run` like `/run/mysql` then use `sudo chown -R <user>:<group> /run/mysql` to change the owner to the user/group `mysqld` will run as.

Currently nix-darwin only supports adding a user to groups when that user is first created, if you want to add a user to `wheel`, you'll have to do it manually with `dseditgroup`

**Comment by sukanka** [comment]
It works! Thanks for your suggestion.
