### ISSUE TITLE
Configuring system launchd daemons

### ISSUE THREAD

**Issue by martijnarts** [LnL7/nix-darwin#797]
Does this line:

https://github.com/LnL7/nix-darwin/blob/afe83cbc2e673b1f08d32dd0f70df599678ff1e7/modules/launchd/default.nix#L161

mean that I should be able to use `launchd.daemons` to enable and configure system daemons?

Cause I've tried to find out where that happens, or how I can do that, but it doesn't seem to work. Any guidance, or is this incorrect documentation?

**Comment by Enzime** [comment]
Here's an example launchd daemon you can take a look at: https://github.com/LnL7/nix-darwin/blob/afe83cbc2e673b1f08d32dd0f70df599678ff1e7/modules/services/netbird.nix#L18-L33

**Comment by martijnarts** [comment]
Thanks @Enzime. I realize my question was unclear! I'm specifically looking to configure packaged system daemon that come with macOS in `/System/Library/LaunchDaemons/`. Is that possible?

**Comment by Enzime** [comment]
I believe there’s currently no logic implemented to manage any system provided LaunchDaemons/LaunchAgents.

If all you're looking to do is to enable them, you can do something like this:

https://github.com/Enzime/dotfiles-nix/blob/b4bbdeffe2e42d37c7409bc9ca64baa31a41fa3a/modules/base.nix#L113

**Comment by martijnarts** [comment]
I see. So the documentation in incorrect then, right? Cause it says it loads those in also.

Would you accept a doc fix PR in that case? Or maybe be able to chat about how I could go about implementing it so the documentation is correct?

**Comment by Enzime** [comment]
From my understanding of the documentation, it's describing how launchd in general starts up the system, rather than describing what this module actually manages, I think it would be a good idea to add an explanation to explain that currently `nix-darwin` does not support managing system provided launch daemons/agents

**Comment by martijnarts** [comment]
Oh you're totally right! Looks like I fully misread the documentation. Thanks!
