### ISSUE TITLE
README.MD should mention flake section within installation section

### ISSUE THREAD

**Issue by vegabook** [LnL7/nix-darwin#802]
https://github.com/LnL7/nix-darwin/blob/master/README.md?plain=1#L14-L21

These lines warn that the "Using `darwin-installer` is no longer necessary on flake based systems", but does not provide an explanation on how to install if _are_ using a flake based system. 

Flakes are mentioned lower but might be worth adding this right here (as in "see below") so that it is part of the "installation" section.

**Comment by Enzime** [comment]
Would you be able to make a PR? It would be great if you could add a link to the flake installation instructions so users could click to go straight there

**Comment by vegabook** [comment]
> Would you be able to make a PR? It would be great if you could add a link to the flake installation instructions so users could click to go straight there

https://github.com/LnL7/nix-darwin/pull/810

**Comment by MunsMan** [comment]
Should the issue be closed, after the pull request was successfully merged?

**Comment by emilazy** [comment]
yep
