### ISSUE TITLE
Include the uninstaller in the default closure?

### ISSUE THREAD

**Issue by grahamc** [LnL7/nix-darwin#804]
As part of the Determinate Nix Installer work, we've run into a lot of users having frustrating experiences uninstalling nix-darwin. We've moved to detecting nix-darwin in the uninstall step to prevent breaking stuff, but actually doing the uninstall is still a bit frustrating for users.

My thinking is it might be nicer to install `darwin-uninstaller` by default in the system, so the uninstall experience is just running that command.

Another thing I think people would appreciate is if the uninstall command didn't need to run nix-build, and came with the closure and nix-darwin system built in to the script. Something like this:

```nix
{ stdenv, nix, pkgs, makeDarwinSystem }:

let
  uninstallSystem = makeDarwinSystem [ ./configuration.nix ];
in

stdenv.mkDerivation {
  name = "darwin-uninstaller";


  # ...

  shellHook = ''
    #!${stdenv.shell}
    set -e

    # ...

    ${uninstallSystem.system}/sw/bin/darwin-rebuild switch

    # ...
```

Would a PR implementing these two pieces be interesting / wanted?

**Comment by Enzime** [comment]
Yeah, both of those ideas sound good, would very much appreciate any PRs that improve the uninstall experience :+1:
