### ISSUE TITLE
How to disable macos startup sound?

### ISSUE THREAD

**Issue by rmgpinto** [LnL7/nix-darwin#885]
I've searched the documentation but haven't found a way to disable MacOS startup sound: `System Settings -> Sound -> Play sound on startup`

**Comment by Samasaur1** [comment]
Looks like even after they added a toggle to System Preferences, the actual setting is still backed by NVRAM (specifically the `StartupMute` key). nix-darwin doesn't currently have an option for this, but you could achieve the same effect by adding `nvram StartupMute=%01` to a system activation script, like so:
```nix
system.activationScripts.postActivation.text = ''
  nvram StartupMute=%01
'';
```
I'll also probably get around to adding a nice option at some point.

**Comment by Samasaur1** [comment]
@rmgpinto There is now a [`system.startup.chime`](https://daiderd.com/nix-darwin/manual/index.html#opt-system.startup.chime) option

**Comment by rmgpinto** [comment]
thanks @Samasaur1, it worked.

**Comment by rmgpinto** [comment]
@Samasaur1 related to this, what about disabling the `Play user interface sounds`? I didn't find anything on docs.

**Comment by Samasaur1** [comment]
> @Samasaur1 related to this, what about disabling the `Play user interface sounds`? I didn't find anything on docs.

@rmgpinto Looks like that's backed by the UserDefaults setting `com.apple.sound.uiaudio.enabled` in NSGlobalDomain. So you should be able to enable it with:
```nix
system.defaults.CustomSystemPreferences.NSGlobalDomain."com.apple.sound.uiaudio.enabled" = 1;
```
and disable it with
```nix
system.defaults.CustomSystemPreferences.NSGlobalDomain."com.apple.sound.uiaudio.enabled" = 0;
```
***
If you're curious, I found this out by running `defaults read > before`, changing the setting, running `defaults read > after`, and then running `diff before after`

**Comment by rmgpinto** [comment]
I had it as `CustomUserPreferences` and not `CustomSystemPreferences`.
Are you able to help on other issues as well? Just added one related to `persistent-others` property for the Dock.
Thanks!

**Comment by Samasaur1** [comment]
It's possible it should be `CustomUserPreferences`. I don't really know the difference.
