### ISSUE TITLE
disable nix-daemon?

### ISSUE THREAD

**Issue by sellout** [LnL7/nix-darwin#9]
I “accidentally” enabled nix-daemon, and now (after disabling it) whenever I try `darwin-rebuild build`, it errors with “the group ‘nixbld’ specified in ‘build-users-group’ does not exist”

How can I get it to not try to start nix-daemon now?

**Comment by yurrriq** [comment]
FWIW I've written and used [this script](https://github.com/yurrriq/dotfiles/blob/nix/nixbld-setup.sh) (modified from outdated NixOS docs) to set up the proper groups and users for `nix-daemon`.

**Comment by yurrriq** [comment]
N.B. The hard-coded `gid=502` might need to be adjusted on your system.

**Comment by LnL7** [comment]
If you remove `/etc/nix/nix.conf` and stop the daemon you can rebuild again.

**Comment by sellout** [comment]
@LnL7 I’ve removed /etc/nix/nix.conf, stopped the daemon, and I still get the same error whenever I try `darwin-rebuild` or `nix-build '<darwin>' -A system --no-out-link` (as part of `$(nix-build '<darwin>' -A system --no-out-link)/sw/bin/darwin-rebuild build`).

I suppose I may as well use @yurrriq’s script and run the daemon anyway – my only reservation is basically having to remember to run that script whenever my nix config moves to a new machine.

**Comment by LnL7** [comment]
I wrote this when I first installed the daemon on my machine https://gist.github.com/LnL7/ed6a23cd803fdb371e853fe970a848a3, I'm planning to include this in the repo or provide a proper installer sometime.
