### ISSUE TITLE
Launch Raycast at Login

### ISSUE THREAD

**Issue by rmgpinto** [LnL7/nix-darwin#902]
Is there a way to automate `"Launch Raycast at Login"`?

I've poked around `defaults read` but couldn't find anything.
I assume this is achieved using either the LaunchDaemons or LaunchAgents functionality of nix-darwin.

**Comment by Enzime** [comment]
https://github.com/Enzime/dotfiles-nix/blob/ba28c8e0902bbb3e1fc9b4d04cd8b4804e8ddcc4/modules/graphical.nix#L8-L12
