### ISSUE TITLE
wget not in flake(s)?

### ISSUE THREAD

**Issue by emladevops** [LnL7/nix-darwin#904]
Hi there, I'm trying to update my Nix system, but when I try to get wget installed on my system, I got this: 
```
error: The option `programs.wget' does not exist. Definition values:
```

Not sure if I'm doing anything wrong, any help would be appreciated!

**Comment by Samasaur1** [comment]
There is no `programs.wget` option in nix-darwin. You probably want to add `pkgs.wget` to `environment.systemPackages` instead

**Comment by emladevops** [comment]
Thanks, I appreciate it.
