### ISSUE TITLE
Enable GitHub Sponsorship

### ISSUE THREAD

**Issue by gshpychka** [LnL7/nix-darwin#914]
Thank you for the project. Please consider enabling [GitHub sponsorship](https://docs.github.com/en/sponsors/getting-started-with-github-sponsors/about-github-sponsors) in the repository settings or adding other information about supporting the project via [`.github.com/FUNDING.yml`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository)

**Comment by gshpychka** [comment]
@LnL7 have you given this any consideration?

**Comment by Enzime** [comment]
Currently 2 of the 4 maintainers of this repo have sponsorship enabled on their GitHub accounts:

https://github.com/sponsors/emilazy
https://github.com/sponsors/Enzime

Feel free to support us :)

**Comment by gshpychka** [comment]
> Currently 2 of the 4 maintainers of this repo have sponsorship enabled on their GitHub accounts:
> 
> https://github.com/sponsors/emilazy https://github.com/sponsors/Enzime
> 
> Feel free to support us :)

Done, waitinf for @LnL7 to enable sponsorship as well :)

**Comment by LnL7** [comment]
Looks to me like the just the file is needed, so I think the active maintainers can just add their info.

**Comment by gshpychka** [comment]
@LnL7 you're not willing to accept sponsorships yourself?
