### ISSUE TITLE
mtr is missing option to set setuidbit

### ISSUE THREAD

**Issue by basn** [LnL7/nix-darwin#916]
As in normal NixOS
mtr needs to be called with sudo
To avoid the need to escalate privileges when calling mtr create a setcap wrapper by setting

https://nixos.wiki/wiki/Mtr

It can be fixed by:
sudo chmod 4755 /run/current-system/sw/bin/mtr-packet
https://blog.dave-bell.co.uk/2020/01/06/using-mtr-on-os-x-without-sudo/

is it possible to add programs.mtr.enable = true;?

**Comment by Samasaur1** [comment]
There's an open issue (https://github.com/LnL7/nix-darwin/issues/618) for this already. I have an open PR (https://github.com/LnL7/nix-darwin/pull/890) that needs to be reviewed, but should solve the issue.

**Comment by basn** [comment]
As there is an open issue i did not find i will close this :)
