### ISSUE TITLE
Add a uninstaller for flakes

### ISSUE THREAD

**Issue by bernes1** [LnL7/nix-darwin#918]
add this comand for uninstaller if you are using flakes becuase the other uninstaller dont work if you are using flakes 

https://github.com/LnL7/nix-darwin/issues/853#issuecomment-1897541986

**Comment by OJFord** [comment]
I needed this even with the non-flake installation. I think the issue is that the readme flake/non-flake is about how nix-darwin is installed, but the non-flake uninstallation section still assumes nix is configured to support flakes.

**Comment by Enzime** [comment]
https://github.com/LnL7/nix-darwin?tab=readme-ov-file#uninstalling

I don't think this command should require flakes

**Comment by noghartt** [comment]
Any update on that? I having an issue with the uninstaller too into my flake setup

`$NIX_PATH` won't be set into macOS with flake

```
nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A uninstaller
error:
       … while calling the 'import' builtin

         at /nix/store/v644prfh8sbnr9fx4kzisrpmixl07yss-source/default.nix:4:10:

            3| , lib ? pkgs.lib
            4| , pkgs ? import nixpkgs { inherit system; }
             |          ^
            5| , system ? builtins.currentSystem

       … while calling the 'findFile' builtin

         at /nix/store/v644prfh8sbnr9fx4kzisrpmixl07yss-source/default.nix:1:13:

            1| { nixpkgs ? <nixpkgs>
             |             ^
            2| , configuration ? <darwin-config>

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)
``

**Comment by foxmean** [comment]
> Any update on that? I having an issue with the uninstaller too into my flake setup
> 
> `$NIX_PATH` won't be set into macOS with flake
> 
> ```
> nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A uninstaller
> error:
>        … while calling the 'import' builtin
> 
>          at /nix/store/v644prfh8sbnr9fx4kzisrpmixl07yss-source/default.nix:4:10:
> 
>             3| , lib ? pkgs.lib
>             4| , pkgs ? import nixpkgs { inherit system; }
>              |          ^
>             5| , system ? builtins.currentSystem
> 
>        … while calling the 'findFile' builtin
> 
>          at /nix/store/v644prfh8sbnr9fx4kzisrpmixl07yss-source/default.nix:1:13:
> 
>             1| { nixpkgs ? <nixpkgs>
>              |             ^
>             2| , configuration ? <darwin-config>
> 
>        error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
> 
>        at «none»:0: (source not available)
> ``
> ```

I have exactly the same error
