### ISSUE TITLE
`cachix-agent` service dies at launch

### ISSUE THREAD

**Issue by dhess** [LnL7/nix-darwin#924]
This started happening sometime in the last month or two with `nixpkgs-unstable`:

```
cachix: security: createProcess: posix_spawnp: does not exist (No such file or directory)
```

It has something to do with the `PATH` set by the `launchd` service. I looked at the Cachix agent source and didn't see anything obvious, and have run out of time to debug it properly, but FYI adding `/usr/bin` to the `launchd` service's `PATH` fixes the problem.

(I suspected `coreutils` and added `coreutils-full` to the path, but that did not fix the issue on my system.)

**Comment by domenkozar** [comment]
I've only seen it now, looks similar to https://github.com/NixOS/nixpkgs/issues/297775

**Comment by sandydoo** [comment]
So one of the Haskell TLS libraries is calling `security`, which isn't in the path.

We can either add `/usr/bin` to the launchctl `paths`, or do something like this https://github.com/tweag/rules_haskell/commit/31171a520f49f263895112678ac93c7ed958ead1

**Comment by sandydoo** [comment]
`config.environment.systemPaths` would probably also work?
