### ISSUE TITLE
Flake installation fails if `~/.config` is a Git repository and `nix-darwin/flake.nix` is not committed

### ISSUE THREAD

**Issue by fmckeogh** [LnL7/nix-darwin#948]
On macOS 14.4.1 (23E224), after installing Nix from the Determinate Nix installer and following the flake `nix-darwin` guide in the README I got the following error:

```
~ $ nix run nix-darwin -- switch --flake ~/.config/nix-darwin
error: path '/nix/store/0lqnbrvn12aq3702vvxx00k31ga2sg2g-source/nix-darwin/flake.nix' does not exist
```

This is resolved by committing `nix-darwin/flake.nix`.

I'm new to Nix so apologies if I've misunderstood something, but given that it was pretty hard to search for this problem it might be helpful if anyone else encounters this.

**Comment by slice** [comment]
I believe this is by design: https://nixos.wiki/wiki/Flakes :)

> For flakes in git repos, only files in the working tree will be copied to the store.

(This should probably say "index" or "staging area" instead of "working tree".)

> When a git folder exists, flake will only copy files added in git to maximize reproducibility […]

**Comment by Samasaur1** [comment]
Yeah, if you set up your config as a git repo, your files need to be tracked by Git or they'll be ignored by Nix
