### ISSUE TITLE
sdate builds and installs but will not run

### ISSUE THREAD

**Issue by pmarreck** [LnL7/nix-darwin#949]
I know it's not a particularly useful app but I unfortunately used it as an example to demo nix on macOS with (without trying it first) and of course it is the first binary I've ever installed with nix that didn't work...

```bash
bash> nix-shell -p sdate
this path will be fetched (0.00 MiB download, 0.06 MiB unpacked):
  /nix/store/bn53yi5rz17pzc0zvpjpf3aqcv3rc4dg-sdate-0.7
copying path '/nix/store/bn53yi5rz17pzc0zvpjpf3aqcv3rc4dg-sdate-0.7' from 'https://cache.nixos.org'...
bash> sdate
sdate: preload library not found in /nix/store/bn53yi5rz17pzc0zvpjpf3aqcv3rc4dg-sdate-0.7/lib:/nix/store/bn53yi5rz17pzc0zvpjpf3aqcv3rc4dg-sdate-0.7/lib64/libsdate, aborting.
```

EDIT: Tried it on NixOS and it installed and ran without fail.

**Comment by jeeftor** [comment]
First I install nix via determinate ... and I have `nix-shell -p xxxx` then when I install Darwin I only have: `nix shell nixpkgs#xxxx`

**Comment by joaothallis** [comment]
@pmarreck sdate is nixpkgs package. You should open the issue in this repo: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/tools/misc/sdate/default.nix#L18

**Comment by emilazy** [comment]
Not a nix-darwin bug, closing. Please do report an issue upstream to Nixpkgs, although I’m not sure to what degree macOS even supports the library preloading functionality that `sdate` depends on these days.
