### ISSUE TITLE
Deprecation warning mkPackageOptionMD should be changed to mkPackageOption

### ISSUE THREAD

**Issue by nklmilojevic** [LnL7/nix-darwin#989]
Just updated my flake and got this:

`warning: mkPackageOptionMD is deprecated and will be removed in 25.05; please use mkPackageOption.`

It is coming from nix-darwin as it is used in several places.

**Comment by emilazy** [comment]
I will fix this soon if nobody beats me to it (dealing with OpenSSH security fix stuff right now); PRs welcome (should be a trivial find–replace).

**Comment by nklmilojevic** [comment]
done https://github.com/LnL7/nix-darwin/pull/990
